### ISSUE TITLE
reimplements the min/max option for collection

### ISSUE THREAD

**Issue by rande** [sonata-project/SonataAdminBundle#319] opened 2011-09-26 22:35 UTC
The min/max option features has been deleted after the form refactoring. So it's make the one-to-many relation with ``edit=list `` unusable

**Comment by core23** [comment] 2016-08-27 15:11
Duplicate of https://github.com/sonata-project/SonataAdminBundle/issues/1704

**Closed by core23** 2016-08-27 15:11 UTC
