### ISSUE TITLE
Type name check prevents extension of autocomplete model

### ISSUE THREAD

**Issue by maurermax** [sonata-project/SonataAdminBundle#3406] opened 2015-11-06 08:23 UTC
A check that is done here that checks for the type name of the form component disallows me from extending the sonata_type_model_autocomplete myself because autocomplete requests are then denied.

https://github.com/sonata-project/SonataAdminBundle/blob/master/Controller/HelperController.php#L465

This should perhaps be removed or replaced with a check that also allows any parent to be of type "sonata_type_model_autocomplete".

**Comment by pulzarraider** [comment] 2015-11-06 09:21
Duplicate of #3164

**Closed by pulzarraider** 2015-11-06 09:21 UTC
