### ISSUE TITLE
Sonata Admin 2.4.x@dev (dev-master) crashes sonata_type_collection 

### ISSUE THREAD

**Issue by maxdmg** [sonata-project/SonataAdminBundle#2942] opened 2015-04-22 14:30 UTC
Followed the [File Uploads Recipe in the Soanata Cookbook](https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_file_uploads.html), but used a ```sonata_type_collection``` instead, like this:

```
$formBuilder
[...]
->add('images', 'sonata_type_collection', array(
                            'by_reference' => false
                        ), array(
                            'edit' => 'inline',
                            'inline' => 'table',
                            'sortable' => 'id',
                    ))
```

According to documentation, in my ```composer.json``` I had: 

```
"require": {
    "sonata-project/admin-bundle": "dev-master",
    "sonata-project/doctrine-orm-admin-bundle": "dev-master",
}
```

Everything worked fine until I installed another package and ran ```composer update```. The command also updated the sonata-project packages.

After the update, when I try to add an image I get this error:

```
ContextErrorException: Catchable Fatal Error: Argument 1 passed to AppBundle\Entity\Product::removeImage() must be an instance of AppBundle\Entity\Image, null given in /var/www/cmmp/src/AppBundle/Entity/Product.php line 549
```

The stack trace:

```
1. in /var/www/cmmp/src/AppBundle/Entity/Product.php line 549
2. at ErrorHandler->handle('4096', 'Argument 1 passed to AppBundle\Entity\Product::removeImage() must be an instance of AppBundle\Entity\Image, null given', '/var/www/cmmp/src/AppBundle/Entity/Product.php', '549', array()) in /var/www/cmmp/src/AppBundle/Entity/Product.php line 549
3. at Product->removeImage(null)
4. at call_user_func(array(object(Product), 'removeImage'), null) in /var/www/cmmp/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 328
5. at PropertyAccessor->writeProperty(object(Product), 'images', null, object(PersistentCollection)) in /var/www/cmmp/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 81
6. at PropertyAccessor->setValue(object(Product), object(PropertyPath), object(PersistentCollection)) in /var/www/cmmp/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php line 93
7. at PropertyPathMapper->mapFormsToData(object(RecursiveIteratorIterator), object(Product)) in /var/www/cmmp/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 628
8. at Form->submit(object(Request)) in /var/www/cmmp/vendor/sonata-project/admin-bundle/Controller/CRUDController.php line 407
9. at CRUDController->editAction('1', object(Request))
10. at call_user_func_array(array(object(CRUDController), 'editAction'), array('1', object(Request))) in /var/www/cmmp/app/bootstrap.php.cache line 2924
11. at HttpKernel->handleRaw(object(Request), '1') in /var/www/cmmp/app/bootstrap.php.cache line 2898
12. at HttpKernel->handle(object(Request), '1', true) in /var/www/cmmp/app/bootstrap.php.cache line 3027
13. at ContainerAwareHttpKernel->handle(object(Request), '1', true) in /var/www/cmmp/app/bootstrap.php.cache line 2306
14. at Kernel->handle(object(Request)) in /var/www/cmmp/web/app_dev.php line 28
```

If I use:

```
"require": {
    "sonata-project/admin-bundle": "2.3.*@dev",
    "sonata-project/doctrine-orm-admin-bundle": "2.3.*@dev",
}
```

everything works fine, the debugger never reaches the breakpoint at ```PropertyAccessor.php line 328```, so I'm gonna use it like that, but I thought you should know about the issue.

If you need more details that might help you reproduce the problem. Please ask.

**Comment by rifats** [comment] 2015-04-28 20:08
Try the new configuration of the sonata_type_collection:

    ->add('sales', 'sonata_type_collection', array(
                'type_options' => array(
                    // Prevents the "Delete" option from being displayed
                    'delete' => false,
                    'delete_options' => array(
                        // You may otherwise choose to put the field but hide it
                        'type'         => 'hidden',
                        // In that case, you need to fill in the options as well
                        'type_options' => array(
                            'mapped'   => false,
                            'required' => false,
                        )
                    )
                )
            ), array(
                'edit' => 'inline',
                'inline' => 'table',
                'sortable' => 'position',
            ))
        ;

Нelped me.

**Comment by anvanza** [comment] 2015-04-29 10:13
@rifats , the only difference is that you're not using 'by_reference'. Therefore the solution is not working.

**Comment by pulzarraider** [comment] 2015-06-07 21:01
Duplicate of #2951

**Closed** 2015-06-08 12:56 UTC
