### ISSUE TITLE
Bottom checkbox in list view should behave like top checkbox to select all items

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3393] opened 2015-10-28 14:07 UTC
Inside the `list` there are a top and a bottom checkbox to check all elements.
![sonata_admin_list_view_bottom_checkbox_issue](https://cloud.githubusercontent.com/assets/3479626/10790794/96963ec8-7d85-11e5-9350-806e7d3e7eda.png)

The bottom one does not work for this purpose in current `dev-master`.

A crazy thing happened once when I checked it anyway and submitted a batch action e.g. `delete`.
After the action was confirmed I was redirected to the `list` view and it got a warning that the object was not found. Maybe in some commit the checkbox thought it would represent an object.

The HTML:

``` html
<label class="checkbox" for="s5630d4957fc4a_all_elements">
<div class="icheckbox_square-blue" style="position: relative;">
<input id="s5630d4957fc4a_all_elements" type="checkbox" name="all_elements" style="position: absolute; opacity: 0;">
<ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;"></ins>
</div>
Alle Elemente (198)
</label>
```

Possibly related to the recent changes:
- https://github.com/sonata-project/SonataAdminBundle/issues/3276
- https://github.com/sonata-project/SonataAdminBundle/pull/3277

**Comment by pulzarraider** [comment] 2015-11-15 06:24
@webdevilopers I have tried the current `dev-master` and the batch `delete` action, but I can't reproduce your issue. Please check if it's not related to your ORM mapping (object A was deleted, but maybe some object B is still referencing to the deleted object A).

**Comment by webdevilopers** [comment] 2015-11-15 09:24
I no longer have access to the project. Besides the ORM the initial issue was that one of the "mark all"
checkboxes did not work. I think.

**Comment by pulzarraider** [comment] 2015-11-15 14:02
I am closing this issue, if you will get more informations that can help reproduce the issue, we can reopned it.

**Comment by webdevilopers** [comment] 2015-11-17 09:24
I can now confirm that with current `dev-master` the top checkbox inside `listView` does select all checkboxes but the bottom one DOES NOT.

The firebug console throws no error. Can you please re-open @pulzarraider ?

**Comment by pulzarraider** [comment] 2015-11-17 11:23
@webdevilopers  the bottom checkbox is not here to check all checkboxes. It's an option to do some batch operation on ALL items, not just on those, which are displayed on current page.

**Comment by OskarStark** [comment] 2015-11-17 11:30
@pulzarraider but you have to know this, this is not documented somewhere, isn't it?

IMO this is not an expected behaviour

i would prefer a button next to the ``OK`` Button
![bildschirmfoto 2015-11-17 um 12 29 28](https://cloud.githubusercontent.com/assets/995707/11210229/e7af75a8-8d26-11e5-8445-6084b7a573bf.png)


``Box`` ``Dropdown`` ``Selected Items`` ``All Items``

**Comment by pulzarraider** [comment] 2015-11-17 12:01
It has the label `All elements` (maybe `All items` will be better) with the number that tells you the number of all items on which the batch action will be applied. I think it's self-explaining.

To improve it we can add there some help message (help tooltip) that can explain what this feature do.

**Comment by webdevilopers** [comment] 2015-11-18 06:47
Unfortunately none of my customers understands this "feature".

When selecting single checkboxes manually or selecting them all they are done - they simple submit the (batch) action.

Everyone yet expected the bottom checkbox to do the "select all" behaviour.

If they want a batch action on all elements - like in your explanation @pulzarraider - they let the list view show more items thanks to the paginator option on the bottom right.

I understand why it is useful to actually GET ALL items. Since the paginator only allows a maximum of e.g. *192* sometimes - depending on your settings.

Wouldn't it be more intuitive - not necessarily make more sense - to add a "Show all" option to the pager instead and make the bottom checkbox behave like the top one?

**Comment by jordisala1991** [comment] 2018-03-10 18:00
This is not a bug but an expected behavior, closing this one.

If you want to propose a change, feel free to submit a new issue with a proposal on how should be the behavior of that checkbox and how to apply batch actions to all items

**Closed by jordisala1991** 2018-03-10 18:00 UTC
