### ISSUE TITLE
Help option not rendered in embed admins

### ISSUE THREAD

**Issue by soerenmartius** [sonata-project/SonataAdminBundle#2676] opened 2015-01-15 15:52 UTC
Hi,

I have a class FileAdmin which comes with a Image Preview through the Fieldoption "help". As long as i use this admin as a single admin the preview works fine. When i embed this admin into another one, the help option won't be rendered.

I am on dev-master.

```
class FileAdmin extends Admin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $media = $this->getSubject();
        // use $fileFieldOptions so we can add other options to the field
        $fileFieldOptions = array('required' => false,'label' => 'Files', 'attr' => array("multiple" => "multiple"), 'by_reference' => false);
        if ($media && ($webPath = $media->getWebPath())) {
            $fileFieldOptions['help'] = '<img src="'.$webPath.'" class="admin-preview" />';
        }
    $formMapper
        ->add('title','text',array('label'=>'Title'))
        ->add('abstract','textarea',array('label'=>'Abstract'))
        ->add('language')
        ->add('format')
        ->add('file', 'file', $fileFieldOptions)
        ->add('quality')
    ;
}
```

}

**Comment by caramba1337** [comment] 2015-05-12 09:00
Can anyone provide a solution?

**Comment by amine26tz** [comment] 2015-05-12 09:10
@caramba1337, you can provide a solution in a PR ;)

**Comment by core23** [comment] 2016-08-13 05:59
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by jordisala1991** [comment] 2018-04-15 21:35
Closing in favor of #5073 

Seems like a duplicate, if it is not, please ping me to reopen.

**Closed by jordisala1991** 2018-04-15 21:35 UTC
Labels: pending author
