### ISSUE TITLE
Suggestion: put "Form" classes into a separate library

### ISSUE THREAD

**Issue by vyshkant** [sonata-project/SonataAdminBundle#4819] opened 2017-12-03 15:56 UTC
My suggestion is to put some of the classes for working with forms into a separate library.

For example, in my project I'm going to create some (non-admin) filterable and sortable view of my entities. Following this goal, I will have to create my own classes like `Sonata\AdminBundle\Form\Type\ModelType`, `Sonata\AdminBundle\Form\DataTransformer\ModelsToArrayTransformer`, etc, and then use them to build forms.

My idea is to create reusable classes (a separate library, like Symfony "component") that can be used in `SonataAdminBundle` and beyond.

**Comment by core23** [comment] 2017-12-03 16:31
We could move some Form's of the CoreBundle too (https://github.com/sonata-project/dev-kit/issues/348)

**Comment by kunicmarko20** [comment] 2017-12-15 20:44
Also, there is CollectionType Form in AdminBundle and in CoreBundle, so one of those could get a rename.

**Comment by VincentLanglet** [comment] 2020-10-18 18:22
There is now https://github.com/sonata-project/form-extensions, right time to move some forms ?

**Comment by core23** [comment] 2020-10-18 20:10
Not sure if we should move `ModelType` and the other form types, because they are too admin specific

**Comment by VincentLanglet** [comment] 2020-10-18 20:40
> Not sure if we should move `ModelType` and the other form types, because they are too admin specific

The issue is old. Let's close this and see if mutiple contributors are asking for it ; which I doubt.

**Closed by VincentLanglet** 2020-10-18 20:40 UTC
Labels: enhancement, keep, pending author
