### ISSUE TITLE
InlineContraint: Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by uwej711** [sonata-project/SonataAdminBundle#2265] opened 2014-07-31 11:39 UTC
We have a problem when enabling caching of Validation constraints:

```
framework:
    validation:
        cache: apc
```

since InlineConstraint uses a Closure when created via attachInlineValidator.

Any ideas?

**Comment by core23** [comment] 2016-04-15 17:12
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @uwej711

**Comment by jordisala1991** [comment] 2018-02-03 15:44
I did track some of the issues on symfony and seems to be solved. Also the issue is very old. Closing. If this should remain opened just ping me

**Closed by jordisala1991** 2018-02-03 15:44 UTC
