### ISSUE TITLE
Help message sonata_help not showing for subfields

### ISSUE THREAD

**Issue by gremo** [sonata-project/SonataAdminBundle#4656] opened 2017-09-17 19:00 UTC
#### Sonata packages

```
sonata-project/admin-bundle              3.23.0 = 3.23.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  = 3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  = 1.0.7  Cache library
sonata-project/cache-bundle              2.3.1  = 2.3.1  This bundle provides caching services
sonata-project/classification-bundle     3.3.1  = 3.3.1  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.4.0  = 3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  = 2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  = 1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.7  = 3.1.7  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  = 2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  = 1.7.1  Lightweight Exporter library
sonata-project/formatter-bundle          3.2.2  = 3.2.2  Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2  ! 1.1.0  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.3.2  = 2.3.2  Symfony SonataIntlBundle
sonata-project/media-bundle              3.6.0  = 3.6.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.2.0  = 3.2.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.5.2  = 3.5.2  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.2.0  = 2.2.0  Symfony SonataSeoBundle
sonata-project/user-bundle               3.2.4  = 3.2.4  Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/assetic-bundle     v2.8.2  = v2.8.2  Integrates Assetic into Symfony2
symfony/monolog-bundle     v3.1.0  = v3.1.0  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.27 ~ v3.3.9  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.5.0  = v1.5.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.5.0  = v1.5.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.5.0  = v1.5.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.5.0  = v1.5.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.5.0  = v1.5.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.5.0  = v1.5.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.5.0  = v1.5.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.5.0  = v1.5.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v2.8.0  = v2.8.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.3  ~ v3.0.3  Symfony SwiftmailerBundle
symfony/symfony            v2.8.27 = v2.8.27 The Symfony PHP framework
```

#### PHP version

```
PHP 5.5.38 (cli) (built: Jul 20 2016 11:16:05)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

## Subject

Sonata help for subfields isn't shown, but it should be as explained [here](https://sonata-project.org/bundles/admin/master/doc/reference/form_help_message.html#help-messages-in-a-sub-field). When aan error occurs in a subfield, error message is not in red color as other form fields with errors.

## Steps to reproduce

Add a new form of type `sonata_type_immutable_array` like explained [here](https://sonata-project.org/bundles/admin/master/doc/reference/form_help_message.html#help-messages-in-a-sub-field) and add the help message.

## Expected results

Help is shown right under the field.

## Actual results

Help is not shown.

**Comment by core23** [comment] 2017-09-17 19:20
Looks like a duplicate of https://github.com/sonata-project/SonataAdminBundle/issues/2874

**Comment by gremo** [comment] 2017-09-17 19:26
@core23 it fixes the help for subfields but not for other types (like checkbox). Not exactly the same issue but related.

**Closed** 2017-09-18 13:01 UTC
