### ISSUE TITLE
Not implemented, please send us your usecase

### ISSUE THREAD

**Issue by kemor** [sonata-project/SonataAdminBundle#3484] opened 2015-12-10 07:26 UTC
Entity:
```php
    /**
     * @var \AppBundle\Entity\Classification\Tag
     *
     * @ORM\ManyToMany(targetEntity="\AppBundle\Entity\Classification\Tag")
     * @ORM\JoinTable(name="lms__training_disability")
     */
    private $disabilityDegree;
```

Admin:
```php
                ->add('disabilityDegree', 'sonata_type_model', array(
                    'multiple' => true,
                    'choices' => array()
                        ),
                )
```
The above throws an Exception.

I need also add a "context" filter to this field (like I can do in 'sonata_type_model_list' ). How can I do it?

**Comment by ethernal** [comment] 2015-12-10 12:13
I have the same issue - any Entity that references another will throw that error when trying to edit it in Admin panel. It should instead get values of that entity and return them to Admin as choices - that was the usual behavior.

How can we fix this or is this sonata error?

**Comment by rande** [comment] 2015-12-10 12:28
This is generated by https://github.com/sonata-project/SonataAdminBundle/blob/d9c85b2a76f72e23b861e33d0f67abdc4ea2c963/Form/ChoiceList/ModelChoiceLoader.php#L132-L143 ... Can you try to implement those methods ? I don't have yet the current use cases ? Can help a lot...

**Comment by ethernal** [comment] 2015-12-10 12:40
I just wanted to add a stack trace that points to this file.



RuntimeException: Not implemented, please send us your usecase
    at n/a
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\sonata-project\admin-bundle\Form\ChoiceList\ModelChoiceLoader.php line 142

    at Sonata\AdminBundle\Form\ChoiceList\ModelChoiceLoader->loadValuesForChoices(array(null), null)
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\Form\ChoiceList\LazyChoiceList.php line 134

    at Symfony\Component\Form\ChoiceList\LazyChoiceList->getValuesForChoices(array(null))
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\DataTransformer\ChoiceToValueTransformer.php line 37

    at Symfony\Component\Form\Extension\Core\DataTransformer\ChoiceToValueTransformer->transform(null)
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\Form\Form.php line 1150

    at Symfony\Component\Form\Form->normToView(null)
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\Form\Form.php line 353

    at Symfony\Component\Form\Form->setData(null)
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper.php line 59

    at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(null, object(RecursiveIteratorIterator))
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\Form\Form.php line 386

    at Symfony\Component\Form\Form->setData(null)
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\Form\Form.php line 478

    at Symfony\Component\Form\Form->initialize()
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\Form\FormBuilder.php line 226

    at Symfony\Component\Form\FormBuilder->getForm()
        in D:\dev\server\www\Apache24\htdocs\symfony28\var\cache\dev\classes.php line 3679

    at Sonata\AdminBundle\Admin\Admin->buildForm()
        in D:\dev\server\www\Apache24\htdocs\symfony28\var\cache\dev\classes.php line 3942

    at Sonata\AdminBundle\Admin\Admin->getForm()
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\sonata-project\admin-bundle\Controller\CRUDController.php line 403

    at Sonata\AdminBundle\Controller\CRUDController->editAction('4', object(Request))
        in  line 

    at call_user_func_array(array(object(CRUDController), 'editAction'), array('4', object(Request)))
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php line 139

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php line 62

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel.php line 69

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Request), '1', true)
        in D:\dev\server\www\Apache24\htdocs\symfony28\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php line 185

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in D:\dev\server\www\Apache24\htdocs\symfony28\web\app_dev.php line 39



I am passing 2 null values from what I could see to that function, between CRUDController and Symfony's getForm something wrong happens as it sets form data to null.

If you can help me with how should I implement this I'll do it, but I have no experience with this, so please be as specific as possible.

**Comment by rande** [comment] 2015-12-10 12:43
I have not look yet at this, maybe @webmozart can provide some tips ;)

**Comment by webmozart** [comment] 2015-12-10 13:35
I can't help much here :) Seems like your throwing an exception in ModelChoiceLoader?

**Comment by ethernal** [comment] 2015-12-10 13:51
@webmozart 

ModelChoiceLoader looks like this:

/**
     * {@inheritdoc}
     */
    public function loadChoicesForValues(array $choices, $value = null)
    {
        throw new \RuntimeException('Not implemented, please send us your usecase');
    }

    /**
     * {@inheritdoc}
     */
    public function loadValuesForChoices(array $choices, $value = null)
    {
        throw new \RuntimeException('Not implemented, please send us your usecase');
    }

These methods should be implemented as I understand.

What I do not get is why getForm and setData from my stack trace show null data.
The forms changed in 2.8 a lot and passing data with:

    $form = $this->createForm(new MyType(),$MyTypeInstance);

used to work, now we need to pass it as $options value as I understand see my answer to the SO question:

http://stackoverflow.com/questions/34027711/passing-data-to-buildform-in-symfony-2-8-3-0/34159802#34159802

**Comment by rande** [comment] 2015-12-10 15:05
@webmozart I guess that ;) but what I add a hard time trying to get what is a ``choice`` and the ``values`` . ``Key`` is the ``choice`` and ``value`` the ``label`` ? So I am not sure what to do in those functions ;)

**Comment by webmozart** [comment] 2015-12-10 15:09
"choice" = model representation of your choices
"value" = string representation of your choices (used in the `value` attributes)
"key" = arbitrary array keys (string or integer)
"label" = string labels displayed in the UI

**Comment by ethernal** [comment] 2015-12-15 08:05
@rande 
Are there any required changes to *Admin classes? If the error is caused by improper implementation on our side then there should be a notice added to Upgrade 2.4.md but I could not find anything there.

I had to checkout the version before Symfony3 integration and sonataAdmin works again properly. Could you explain why the changes where introduced that break fetching the data from related entities?

Do you know what the exact problem is and how it can be fixed? How could I help?

**Comment by paquitodev** [comment] 2015-12-16 16:44
I am on the same as you, trying to find how to fix this issue but without help I think I can't be so helpful so @webmozart @rande give us some tips in order to help you guys. 

@ethernal `loadChoicesForValues()` and `loadValuesForChoices()` doesn't exists on 2.3 branch, take a look [here](https://github.com/sonata-project/SonataAdminBundle/blob/2.3/Form/ChoiceList/ModelChoiceList.php) I think those are new and comes from `Symfony\Component\Form\ChoiceList\ChoiceListInterface`

**Comment by rande** [comment] 2015-12-16 16:52
@webmozart cannot provide much information as it is related to sonata. Now, I am currently working on fixing sonata's bundles to work with sf2.8 and sf3.0. This is not an easy task. 

If you want to help, just remove the exception and try to implements the related methods. Then send a PR.

**Comment by paquitodev** [comment] 2015-12-16 17:19
@rande yes I can do that but could you explain me or at least give me a light in what to implement?

**Comment by blogrammierer** [comment] 2015-12-21 14:53
With commit https://github.com/sonata-project/SonataAdminBundle/commit/b039fd706d6b89936a37b11ff9d2abb47ec0af9c my AdminInterface crashed. The commit changed the "block-bundle" version range, so I assume this issue depends on Sonata Block Bundle - or?

**Comment by rande** [comment] 2015-12-23 09:43
should be fixed by https://github.com/sonata-project/SonataAdminBundle/pull/3504

**Closed by rande** 2015-12-23 09:43 UTC

**Comment by blogrammierer** [comment] 2015-12-23 16:33
The exception is fixed, but now "no results" message is shown on "sonata_type_model" without any options added. 

My fieldconfiguration in adminClass:
`->add('field', 'sonata_type_model', array(), array())`
