### ISSUE TITLE
Sonata try to remove 'null' entity

### ISSUE THREAD

**Issue by UnDeleteRU** [sonata-project/SonataAdminBundle#2951] opened 2015-04-24 12:44 UTC
We have enity Place, entity PlaceType and OneToMany relation between. We have PlaceAdmin with field 'placeTypes' type 'sonata_type_collection'. placeTypes is collection of PlaceType`s and it's manage with add and remove methods. When we add new PlaceType to Place an error occurs: **Argument 1 passed to Place::removePlaceType() must be an instance of \PlaceType, null given.**

Problem starts in this commit https://github.com/sonata-project/SonataAdminBundle/commit/1a5ba565a75c6c43867c52210cb78ec29a2b6748

If using revision before this commit all work fine
Current version of our symfony 2.3.27

**Comment by rande** [comment] 2015-04-27 12:33
You model setter need to accept null value.

**Comment by idetia** [comment] 2015-05-20 09:13
If you accept null values, the methods add and remove are not recognized when you use 'by_reference = false' with the 'sonata_type_collection' type.

The problem is in AdminType.php, when you try to access the property value with $p->getValue(...), but I don't know the reason.

**Comment by pulzarraider** [comment] 2015-05-26 21:06
@rande I am afraid that commit https://github.com/sonata-project/SonataAdminBundle/commit/1a5ba565a75c6c43867c52210cb78ec29a2b6748 should be reverted or fixed. It breaks functionality of `sonata_type_collection`.

**Comment by rande** [comment] 2015-05-26 21:11
@pulzarraider can you elaborate ?

**Comment by rande** [comment] 2015-05-26 21:21
Should we push this code to a specific event ?

**Comment by pulzarraider** [comment] 2015-05-27 06:37
The problem occurs in newly added rows in `sonata_type_collection`. I didn't go in depth, but it shows the errors specified in this issue above - some uneeded null value is called as paramer of remove method. After commenting out the lines https://github.com/sonata-project/SonataAdminBundle/blob/master/Form/Type/AdminType.php#L55-L68 it works without any problem and no null value occurs. I will try to look at this problem this evening to examine it closer.

**Comment by rande** [comment] 2015-05-27 08:38
@pulzarraider for information, this code allows this kind of behavior: https://github.com/sonata-project/sandbox/blob/2.4-develop/src/Sonata/Bundle/DemoBundle/Admin/InspectionAdmin.php#L57-L67

**Comment by BaptN** [comment] 2015-06-08 02:20
Hi ....
I'm experiencing the same kind of issue.
On a 1-to-many relationship, I was using the old sonata_type_collection format to embed many "Artists" in a "Album" admin page. 

When saving, I had the same exception described here. The issue was the same after switching to the new sonata_type_collection format, but it passed when commenting the lines as suggested by @pulzarraider  ...

**Comment by pulzarraider** [comment] 2015-07-31 06:01
This bug occurs in Symfony 2.3 (old version of `PropertyAccessor`).
Fixed with #3128.Thank you for reporting the problem.

**Closed by pulzarraider** 2015-07-31 06:01 UTC
