### ISSUE TITLE
Conflict with DI extra bundle

### ISSUE THREAD

**Issue by Nightbr** [sonata-project/SonataAdminBundle#4292] opened 2017-01-26 11:16 UTC
Hi !

I have an issue with the last release of SonataAdminBundle (3.11.*). 

### Environment

* Environment dev
* Debug enabled
* PHP version 5.6.29-0+deb8u1

#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.10.3             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.0              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.2.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           dev-master 9c6f293 Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.0.0              Symfony Sonata / Integrate Doctrine...
sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0              Lightweight Exporter library
sonata-project/intl-bundle               dev-master d2eab1c Symfony SonataIntlBundle
sonata-project/media-bundle              dev-master master  

```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP v...
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower...
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower...
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower...
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower...
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.16 The Symfony PHP framework

```

#### PHP version

PHP version 5.6.29-0+deb8u1

## Subject

With the last release of SonataAdmin, I have some issues with DI Extra Bundle see this issue https://github.com/schmittjoh/JMSDiExtraBundle/issues/266

All services are not found with basic service annotation:

```
/**
 * @DI\Service("app.indexer.category")
 */
class CategoryIndexer
```

Also, it could be a conflict with my JMS configuration:

```
jms_di_extra:
    locations:
        all_bundles: false
        bundles: [AppBundle, ApiBundle]
        directories: ["%kernel.root_dir%/../src"]
```

I tried to use `"jms/di-extra-bundle": "^1.7"` but the problem still persists...

My workaround so far: rollback to SonataAdminBundle 3.10.* :confused: 

## Steps to reproduce

1. Update to SonataAdminBundle 3.11.*
2. Declare services with JMSDiExtraBundle @DI\service()
3. Try to get the service (dep injection or get from container)

## Expected results

All services in AppBundle which uses DI annotation must be found as service.

## Actual results

Services declared with DI annotation are not found.

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                           
  The service "fos_elastica.listener.app.category" has a dependency on a non-existent service "app.indexer.category". 
```

Any idea ?

Thanks for your amazing work and your help !

If you need anything ask for it ! ;)

**Comment by maarekj** [comment] 2017-01-26 17:32
I had the same issue, and I fixed it with this lines in config.yml

```yaml
jms_di_extra:
   annotation_patterns:
      - "JMS\\DiExtraBundle\\Annotation"
```

**Comment by Nightbr** [comment] 2017-01-26 17:43
@maarekj Thanks made the trick! Hope we find a better solution that SonataAdminBundle doesn't break main App.

**Comment by greg0ire** [comment] 2017-01-26 18:42
Can one of you use `git bisect` to find the offending commit?

**Comment by Nightbr** [comment] 2017-01-27 07:45
Hey, the only change related to JMSDIExtra is this one:

https://github.com/sonata-project/SonataAdminBundle/commit/216933fa18e8beb3d1dfe7f4a1aaed78da652a3c#diff-d81fe8cfe0444cbcab9e87a76c5e9970R219

**Comment by greg0ire** [comment] 2017-01-27 09:04
If it is already set, our values should be merged with existing values, right? That sounds like a bug to me…

**Comment by Nightbr** [comment] 2017-01-27 09:17
Nop it's not a bug but a misunderstanding of the default value.

For example, with this jms_di_extra configuration:

```
jms_di_extra:
    locations:
        all_bundles: false
        bundles: [AppBundle, ApiBundle]
        directories: ["%kernel.root_dir%/../src"]
```

When I called prependExtensionConfig my annotation_patterns if empty so the config for annotation_patterns will be only 

```
  'annotation_patterns' => array(
       'Sonata\AdminBundle\Annotation',
 ),
```

And now, the annotation_patterns config is not empty (contains ` 'Sonata\AdminBundle\Annotation'`) so the default value `JMS\DiExtraBundle\Annotation` is replace by ` 'Sonata\AdminBundle\Annotation'`.

It's the correct behavior of DepInjection configuration.

**Comment by greg0ire** [comment] 2017-01-27 09:23
Oh ok I get it, but I'm not sure I agree with your fix… because that would mean that any bundle that wants to prepend any configuration would have to do the same.

**Comment by greg0ire** [comment] 2017-01-27 09:23
Very similar problem : https://github.com/sonata-project/SonataAdminBundle/issues/2425#issuecomment-275610613

**Comment by greg0ire** [comment] 2017-01-27 09:25
Maybe `cannotBeOverwritten` would be it ? http://symfony.com/doc/current/components/config/definition.html#merging-options

**Comment by Nightbr** [comment] 2017-01-27 09:25
No problem, I don't say that my fix is ideal ;)
We can discuss here for an ideal fix with pleasure !

**Comment by greg0ire** [comment] 2017-01-27 09:27
If there is no native way I think your fix might be the best course of action… can you check if `cannotBeOverwritten` works? I have some doubts, I think it might mean that the first thing to configure the bundle wins, not sure it has anything to do with defaults.

**Comment by Nightbr** [comment] 2017-01-27 09:29
Seems the `cannotBeOverwritten` doesn't work with Default value...

**Comment by greg0ire** [comment] 2017-01-27 09:33
Ping @core23 @gremo, what do you think?

**Comment by greg0ire** [comment] 2017-01-27 09:43
> because that would mean that any bundle that wants to prepend any configuration would have to do the same.

Actually in that case, [the first bundle wins](https://symfony.com/doc/3.1/bundles/prepend_extension.html#more-than-one-bundle-using-
prependextensioninterface)

**Comment by gremo** [comment] 2017-01-27 09:49
@greg0ire are you sure about? Because while writing and testing https://github.com/sonata-project/SonataUserBundle/pull/829 and https://github.com/sonata-project/SonataClassificationBundle/pull/271I've found that actually the configuration is merged (controller paths from both bundles get merged and dumped). I'm going to test it right now.

**Comment by greg0ire** [comment] 2017-01-27 09:50
Are you talking about merging with default values, or merging with existing configuration?

**Comment by Nightbr** [comment] 2017-01-27 10:04
After some research, I confirm what I said later, the `prependExtensionConfig` doesn't take into account the defaultValue set in configuration.php.

https://github.com/symfony/dependency-injection/blob/74b310dbf6a5e717e4c8aafcb2e1ba2eab116a52/ContainerBuilder.php#L535

https://github.com/symfony/dependency-injection/blob/93f50bfe952da569c1185c718ef41b61fa9d3461/ParameterBag/EnvPlaceholderParameterBag.php#L42

**Comment by greg0ire** [comment] 2017-01-27 16:23
So I asked on the symfony slack, and I was told this by @xabbuh : 

> @greg0ire using `array_merge()` in the "before normalization“ step should work

Here are [the related docs](https://symfony.com/doc/current/components/config/definition.html#normalization), can you try something like that in the DI bundle?

**Comment by xabbuh** [comment] 2017-01-27 16:37
The change to the `Configuration` class would have to be done in the JMSDiExtraBundle where it is defined. However, I am not sure that is intended.

**Comment by gremo** [comment] 2017-01-27 17:07
I can't check right now (in phone) but I would do the following. Please correct me if I'm wrong.

In prependExtensionConfig just check for annotation_pattern. If key doesn't exist, that would mean we need to prepend the default pattern from JMSDiExtraBundle plus the SonataAdmin pattern, this way we don't break the bundle.

If key actualy exists it means that those values come from config.yml and not from defaults. Just prepend the sonata pattern, it's the developer responsibility to add any other pattern.

This is a temporary Fox but it's necessary because how symfony do merging/prepending is not going ti chance in the near future.

**Comment by greg0ire** [comment] 2017-01-27 17:12
@gremo that's exactly what @Nightbr proposed I think. I was just wondering if that would be something that would make more sense to fix in the DI bundle, but I'm starting to think there is no way to do that properly, b/c you could not guess if the value comes from Sonata and needs to be merged, or if it comes from the developer, in which case they probably want to get it overwritten. However, for the other problems you had with other bundles, since it's internal, we could go ahead and use what @xabbuh said (@stof says it should actually take place in the `validate()` method). See https://symfony-devs.slack.com/messages/support/

**Comment by gremo** [comment] 2017-01-27 17:23
Ok then, lets see what @Nightbr says. I could be wrong but checking for keys (just the presence/absence) should be enought to guess if values come from the developer. Unfortunatly (or not) I'm on holidays until next week and I can't check :)

**Comment by greg0ire** [comment] 2017-01-27 17:27
Yeah @Nightbr , I think you can go ahead and make PR Sonata-side…

**Comment by Nightbr** [comment] 2017-01-30 08:24
@greg0ire hey, I will make the PR sonata-side next week, I'm on holidays right now too.

**Comment by greg0ire** [comment] 2017-01-30 10:09
Happy holiday then!

**Comment by Padam87** [comment] 2017-01-31 15:26
Is it a good idea to prepend `Sonata\AdminBundle\Annotation`?

It has caused extreme slowness in dev mode on my projects. Just tried upgrading, and my dev mode runtime went from 0.8 seconds to 2.6.

**Comment by greg0ire** [comment] 2017-01-31 15:29
We didn't do it yet…

**Comment by Padam87** [comment] 2017-01-31 15:32
https://github.com/sonata-project/SonataAdminBundle/commit/216933fa18e8beb3d1dfe7f4a1aaed78da652a3c#diff-d81fe8cfe0444cbcab9e87a76c5e9970

This commit landed in 3.11, and fixed the prepending.

**Comment by greg0ire** [comment] 2017-01-31 15:33
Oh you're right, sorry! Are you positive that line causes the drop in performance?

**Comment by Padam87** [comment] 2017-01-31 15:36
Yep. I've reverted to 3.10, all good. Tried adding the annotation manually, took pics :)
![before](https://cloud.githubusercontent.com/assets/776488/22471694/6f7e492a-e7d3-11e6-8341-b1d331687911.png)
![after](https://cloud.githubusercontent.com/assets/776488/22471701/728cfed6-e7d3-11e6-9471-0946c382d04d.png)

**Comment by greg0ire** [comment] 2017-01-31 15:39
That's very serious :/ @stefnoten can you advise?

**Comment by Padam87** [comment] 2017-01-31 15:59
https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/Config/ServiceFilesResource.php#L40

This seem to be the problem. Always looks for `JMS\DiExtraBundle\Annotation`, therefore it is never fresh.

Providing the pattern as a constructor argument solves the problem... I will submit a PR soon

**Comment by SebastienTainon** [comment] 2017-02-02 13:25
I can confirm your issue @Padam87, it is blocking to update SonataAdmin to the current version when using JMSDiExtraBundle. I've noticed similar slowness on my project.

Thanks for your PR!

**Comment by SebastienTainon** [comment] 2017-02-02 13:47
I can confirm the issue, it is blocking to update SonataAdmin to the current version when using JMSDiExtraBundle. I've noticed similar slowness on my project.

Even when using the PR from @Padam87 which corrects most of the performance issues, I still have my project ~ 30% slower than before this update in SonataAdmin.

**Comment by Padam87** [comment] 2017-02-02 14:04
@SebastienTainon Yes, that is correct, the difference is still measurable. The problem is in the way DI extra handles multiple patterns.

https://github.com/schmittjoh/JMSDiExtraBundle/blob/9ca75398f0e5fb03e11c9f7f1c6843e27c24ccf6/DependencyInjection/Compiler/AnnotationConfigurationPass.php#L62

There is a new lookup for every pattern, in my setup each pattern takes about 200ms to do.

**Comment by greg0ire** [comment] 2017-02-02 14:35
So this means it is a JMSDIExtraBundle issue, right?

**Comment by Padam87** [comment] 2017-02-02 14:47
Yes, i've opened a separate issue for it. https://github.com/schmittjoh/JMSDiExtraBundle/issues/272

**Comment by andreasferber** [comment] 2017-02-09 15:54
This is causing other issues as well:

    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                       
    The service "security.firewall" has a dependency on a non-existent service "security.request_ma  
    tcher.5314eeb91110adf24b9b678372bb11bbe00e8858c519c088bfb65f525181ad3bf573fd1d".                 

I don't know exactly what is happening there, however I `git bisect`ed it down to commit 216933fa18e8beb3d1dfe7f4a1aaed78da652a3c as well.

Please don't unconditionally and unoverridably mess with the configuration of another completely unrelated bundle. The configuration prepend in symfony isn't meant for that, it's there so that closely related bundles can share a common configuration. The way you are adding the pattern, there is no way a user can remove it from annotation_patterns if she doesn't want it (frankly, I don't see the point of the Admin annotation anyway, AFAICT there's nothing you can do with it that you can't do with DiExtraBundle's Tag annotation). You aren't changing a default value, you are in essence editing the users `config.yml` without asking (or even telling) him.

The way this should be done properly is by not adding something magically and documenting that in order to use the Admin annotation you have to configure di_extra_bundle appropriately.

**Comment by greg0ire** [comment] 2017-02-09 16:00
> The way this should be done properly is by not adding something magically and documenting that in order to use the Admin annotation you have to configure DiExtraBundle appropriately.

I agree with you, that's why I'm not 100% fine with #4312 . I think we should merge it, and then introduce a deprecation mechanism to tell people they should do that manually. Would you be willing to contribute it?

**Comment by Nightbr** [comment] 2017-02-09 16:05
I think we don't need a deprecation with this because it has never worked. It has been introduced in 3.11.* and directly conflict with JMSDiExtra. We should remove this part and documenting the thing as @andreadelfino said. I can modify my PR if you want.

**Comment by greg0ire** [comment] 2017-02-09 16:11
> I think we don't need a deprecation with this because it has never worked

You mean that no one currently is not configuring these annotations, and expecting it to work? Apparently 216933f fucks some things up for some people, but not for people who are using it exclusively with Sonata, right?

**Comment by Nightbr** [comment] 2017-02-09 16:17
Yep kind of ^^
https://github.com/sonata-project/SonataAdminBundle/commit/216933fa18e8beb3d1dfe7f4a1aaed78da652a3c inverts the condition and when you have configure JMSDiExtra Bundle it automatically add the configuration (which breaks JMSDiExtra default conf).

At 3.10 => works fine but you have to specify manually the AdminAnnotation in your config.yml
At 3.11 => SonataAdminBundle try to (force) add the AdminAnnotation into config when JMSDiExtra is detected. But there is our issue (with default config).

I think we just need to document this properly and remove the part where SonataAdminBundle try to (force) add the AdminAnnotation.

**Comment by greg0ire** [comment] 2017-02-09 16:20
So since 3.11, it's fair to say new users could have been successfully using this for Sonata. Removing the auto-config would be a BC-break, and should be treated as such (by throwing a deprecation notice telling people they need to do it manually).

**Comment by Nightbr** [comment] 2017-02-09 16:27
ok why not create a patch 3.11.n with the deprecation notice and remove this code in 3.12. Fair enough 👌

**Comment by greg0ire** [comment] 2017-02-09 16:28
Deprecation notices are minor, and removals are major… so… your PR : 3.11.n, the deprecation => 3.12, the removal => 4.0.0

**Comment by Nightbr** [comment] 2017-02-09 16:33
I don't know if we really should merge my PR... It's not a best practice to modify other bundle config on runtime... Wait and see others though on this subject.

**Comment by greg0ire** [comment] 2017-02-09 16:33
But we're already doing it, right? Might as well do it a bit better…

**Comment by greg0ire** [comment] 2017-02-09 16:35
If we don't, people will be stuck with this bug until 4.0, because we don't do BC-breaks.

**Comment by Nightbr** [comment] 2017-02-09 16:40
Or we can right now remove the auto-config JMSDi code and finally the code works (without workaround) and I think it's not a BC-breaks. And If you want to use AdminAnnotation, you have to add it into your config.yml (we just need to document this a bit).

**Comment by greg0ire** [comment] 2017-02-09 16:42
So it boils down to : is this a BC-break?

My thoughts:
1. new user arrives , uses 3.11
2. expects DI to work with sonata without configuring anything
3. updating to 3.12 should work the same

@sonata-project/contributors WDYT? Should this be considered a BC-break or not?

**Comment by andreasferber** [comment] 2017-02-09 16:43
It's definitely a BC break for users using 3.10 or earlier and updating to 3.11 or later right now...

**Comment by Nightbr** [comment] 2017-02-09 16:45
agree with @andreasferber and it was my case and the primary reason I opened the issue. It creates a BC-breaks when updates from 3.10 to 3.11 it breaks all Symfony app with JMSDiExtra setup...

**Comment by greg0ire** [comment] 2017-02-09 16:46
@andreasferber : yes, it is, don't rub it in. What's the lesson we get from reading your sarcasm? That people do not like BC-breaks. Right now you are proposing to create a second BC-break… What I'm proposing is having the right solution in 3.12, but also keep the "bad but better" solution from #4312 work too, but be deprecated.

**Comment by greg0ire** [comment] 2017-02-09 16:48
What you guys don't understand is that the BC-break from 3.10 to 3.11 is done. Now it's the new behavior, and it might work for some people. You're trying to fix your use case, but what about people using the other use case, which, by the way, is the documented one? What about people that did not do the upgrade from 3.10 to 3.11 , but will update from 3.10 or lower to 3.12?

**Comment by andreasferber** [comment] 2017-02-09 16:50
The solution from #4312 doesn't work, see my comment there.

**Comment by Nightbr** [comment] 2017-02-09 16:52
Wait and see what other contributors think about this and take a decision.

**Comment by andreasferber** [comment] 2017-02-09 17:07
Since it appears right now that someone has to "bite the dust", the question is, what is the larger user base, the ones that just started using Sonata admin with version 3.11 to 3.13 and *might* be using the Admin annotation, or the ones that use Sonata admin for years and want to update their project to the latest version.

Also please think about the impact it has: "Some users have to add a line to their config.yml when updating admin-bundle" vs. "some users are stuck with version 3.10 until 4.0 is eventually released".

**Comment by greg0ire** [comment] 2017-02-09 17:08
> "some users are stuck with version 3.10 until 4.0 is eventually released".

What?

**Comment by greg0ire** [comment] 2017-02-09 17:10
> What I'm proposing is having the right solution in 3.12, but also keep the "bad but better" solution from #4312 around, but deprecated.

They would have to wait until 3.12… so… a few days?

**Comment by andreasferber** [comment] 2017-02-09 17:43
"keep the solution from #4312 around" would mean right now, that SonataAdminExtension would keep adding its own annotation_pattern without any way to completely disable it. See my first post, the error I'm getting happens *as soon as the Admin annotation gets enabled in any way*, even if I use 3.10 and add the pattern manually to `config.yml`. This means, if I can't completely disable the tampering with annotation_patterns, I'm stuck with 3.10 (which only works because of the broken if).

**Comment by andreasferber** [comment] 2017-02-09 21:17
In addition to fixing the general issue with JMSDiExtraBundle, my PR also adds a new config option to disable the whole stuff, which provides a workaround to avoid the performance hit (until JMSDiExtraBundle gets fixed) and helps people with a problem like mine.

**Closed** 2017-02-10 09:08 UTC
