### ISSUE TITLE
Problem in getFilterName with mongodb embedded filtering.

### ISSUE THREAD

**Issue by piron4o** [sonata-project/SonataAdminBundle#2966] opened 2015-05-04 09:50 UTC
When I try to filter by embedded document field in mongodb document the method getFieldName() in Sonata\AdminBundle\Filter\Filter(https://github.com/sonata-project/SonataAdminBundle/blob/master/Filter/Filter.php#L137)  returns incorrect field name. 
Here is code example in admin: 

```
  protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper            
            ->add('account')
            ->add('address.country')
            ->add('address.city')
        ;
    }
```

And when you try to filter in list by address.country getFieldName() (https://github.com/sonata-project/SonataAdminBundle/blob/master/Filter/Filter.php#L137)  returns only "country".
This is dumped queryArray: 

```
array(1) { ["country"]=> object(stdClass)#1377 (3) { ["__CLASS__"]=> string(10) "MongoRegex" ["regex"]=> string(8) "Bulgaria" ["flags"]=> string(1) "i" } } 

```

**Comment by core23** [comment] 2016-08-13 06:02
Can you check this against the latest master version @piron4o ?

Sure this issues is related to the admin bundle? Looks like this is a [mongo bug](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle).

**Comment by jordisala1991** [comment] 2018-04-05 06:26
This looks like a duplicate of : https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/issues/158

Closing because this issue makes sense on the DoctrineMongoDbAdminBundle

If you think those issues are not related please ping me to reopen

**Closed by jordisala1991** 2018-04-05 06:26 UTC
Labels: pending author
