### ISSUE TITLE
AdminInterface::getNewInstance doesn't work in embedded admin classes

### ISSUE THREAD

**Issue by vyshkant** [sonata-project/SonataAdminBundle#4492] opened 2017-05-23 20:55 UTC
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.18.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.3.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.4  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/media-bundle              3.5.1  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0  Symfony SonataNotificationBundle
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1 Integrates Assetic into Symfony2
symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.2.8 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.4 Symfony SwiftmailerBundle
symfony/symfony            v3.2.8 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.1.5-1+deb.sury.org~xenial+2 (cli) (built: May 22 2017 12:48:42) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.5-1+deb.sury.org~xenial+2, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

I'm trying to embade the `ClildAdminClass` to the `ParentAdminClass` and use the feature of `AdminInterface::getNewInstance` to modify the `ClildAdminClass` object after form submit. My idea is to fill some default values and hide these fields from the form.

In my `ParentAdminClass` I've added field `someProperty` as shown below:

```php
class ParentAdminClass extends \Sonata\AdminBundle\Admin\AbstractAdmin {
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
                    ->add('someProperty', 'sonata_type_admin', array(
                        'required' => false
                    ), array(
                        'admin_code' => 'admin.child_admin_class'
                    ))
    }
}
```

This works great, and I can see the expected embedded form on the admin page.

Next I've overridden the `AdminInterface::getNewInstance` method by creating it's `ClildAdminClass::getNewInstance` implementation:

```php
class ClildAdminClass extends \Sonata\AdminBundle\Admin\AbstractAdmin {
    public function getNewInstance()
    {
        $instance = parent::getNewInstance();

        $instance->setFooProperty('Bar');

        return $instance;
    }
}
```

And this doesn't work: the code of `ClildAdminClass::getNewInstance` is never executed, whereas the new instance of the expected class is created (and causes persist fail). if the `fooProperty` is mandatory property of the `ClildAdminClass` it causes the MySQL error "Integrity constraint violation: 1048 Column 'foo_property' cannot be null".

So I can't use this feature for embadded admins.

**Comment by greg0ire** [comment] 2017-05-23 20:59
Closing as duplicate of #4275

**Closed by greg0ire** 2017-05-23 20:59 UTC
