### ISSUE TITLE
Bad RuntimeExpection in AdminPool: 'Unable to found a valid admin for the class: %s, get too many admin registered

### ISSUE THREAD

**Issue by Gladhon** [sonata-project/SonataAdminBundle#2424] opened 2014-09-22 11:26 UTC
Hi there

Currently theres coming up a RuntimeException if there are more than one Admin per Class.
https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Pool.php#L152

I wish that I can mark one of the Admins as default, so I dont have to use an admin_code on all related Admins. On the other side, it would be nice to throw a Custom Exception, so that it can be catched easy

**Comment by core23** [comment] 2016-08-27 15:09
Duplicate of https://github.com/sonata-project/SonataAdminBundle/issues/3908

**Closed by core23** 2016-08-27 15:09 UTC
