### ISSUE TITLE
editable field validation error

### ISSUE THREAD

**Issue by buxom-man** [sonata-project/SonataAdminBundle#5868] opened 2020-02-03 15:07 UTC
Hello. 
When trying to save an empty value to a field in listing (editing in place) the `validate()` method is not called and it just gives an error. I don't think it is an intentional behaviour, is it?

<img width="863" alt="Screenshot 2020-02-03 at 18 02 14" src="https://user-images.githubusercontent.com/60614904/73664133-f1e8ac00-46af-11ea-9059-4dab2c53f419.png">

**Comment by core23** [comment] 2020-02-03 15:59
Duplicate of https://github.com/sonata-project/SonataAdminBundle/issues/5693

**Closed by core23** 2020-02-03 15:59 UTC
Labels: bug, unconfirmed
