### ISSUE TITLE
Cannot add custom template via yaml config

### ISSUE THREAD

**Issue by mikemix** [sonata-project/SonataAdminBundle#5337] opened 2018-12-06 14:16 UTC
### Environment

Docker container `apache:7.1-apache`

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'

sonata-project/admin-bundle              3.42.0 3.42.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.13.0 3.13.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.12.0 3.12.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.2  1.1.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.3  3.6.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.9.1  1.9.1  Lightweight Exporter library
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'

Restricting packages listed in "symfony/symfony" to "4.1.*"
symfony/asset                 v4.1.8  v4.1.8  Symfony Asset Component
symfony/browser-kit           v4.1.8  v4.1.8  Symfony BrowserKit Component
symfony/cache                 v4.1.8  v4.1.8  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                v4.1.8  v4.1.8  Symfony Config Component
symfony/console               v4.1.8  v4.1.8  Symfony Console Component
symfony/css-selector          v4.1.8  v4.1.8  Symfony CssSelector Component
symfony/debug                 v4.1.8  v4.1.8  Symfony Debug Component
symfony/dependency-injection  v4.1.8  v4.1.8  Symfony DependencyInjection Component
symfony/doctrine-bridge       v4.1.8  v4.1.8  Symfony Doctrine Bridge
symfony/dom-crawler           v4.1.8  v4.1.8  Symfony DomCrawler Component
symfony/dotenv                v4.1.8  v4.1.8  Registers environment variables from a .env file
symfony/event-dispatcher      v4.1.8  v4.1.8  Symfony EventDispatcher Component
symfony/expression-language   v4.1.8  v4.1.8  Symfony ExpressionLanguage Component
symfony/filesystem            v4.1.8  v4.1.8  Symfony Filesystem Component
symfony/finder                v4.1.8  v4.1.8  Symfony Finder Component
symfony/flex                  v1.1.8  v1.1.8  Composer plugin for Symfony
symfony/form                  v4.1.8  v4.1.8  Symfony Form Component
symfony/framework-bundle      v4.1.8  v4.1.8  Symfony FrameworkBundle
symfony/http-foundation       v4.1.8  v4.1.8  Symfony HttpFoundation Component
symfony/http-kernel           v4.1.8  v4.1.8  Symfony HttpKernel Component
symfony/inflector             v4.1.8  v4.1.8  Symfony Inflector Component
symfony/intl                  v4.1.8  v4.1.8  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/messenger             v4.1.8  v4.1.8  Symfony Messenger Component
symfony/monolog-bridge        v4.1.8  v4.1.8  Symfony Monolog Bridge
symfony/monolog-bundle        v3.3.1  v3.3.1  Symfony MonologBundle
symfony/options-resolver      v4.1.8  v4.1.8  Symfony OptionsResolver Component
symfony/orm-pack              v1.0.5  v1.0.5  A pack for the Doctrine ORM
symfony/panther               v0.2.0  v0.2.0  A browser testing and web scraping library for PHP and Symfony.
symfony/phpunit-bridge        v4.2.0  v4.2.0  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu     v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring     v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72        v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process               v4.1.8  v4.1.8  Symfony Process Component
symfony/profiler-pack         v1.0.3  v1.0.3  A pack for the Symfony web profiler
symfony/property-access       v4.1.8  v4.1.8  Symfony PropertyAccess Component
symfony/routing               v4.1.8  v4.1.8  Symfony Routing Component
symfony/security              v4.1.8  v4.1.8  Symfony Security Component
symfony/security-acl          v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle       v4.1.8  v4.1.8  Symfony SecurityBundle
symfony/stopwatch             v4.1.8  v4.1.8  Symfony Stopwatch Component
symfony/swiftmailer-bundle    v3.2.4  v3.2.4  Symfony SwiftmailerBundle
symfony/templating            v4.1.8  v4.1.8  Symfony Templating Component
symfony/test-pack             v1.0.4  v1.0.4  A pack for functional and end-to-end testing within a Symfony app
symfony/translation           v4.1.8  v4.1.8  Symfony Translation Component
symfony/twig-bridge           v4.1.8  v4.1.8  Symfony Twig Bridge
symfony/twig-bundle           v4.1.8  v4.1.8  Symfony TwigBundle
symfony/validator             v4.1.8  v4.1.8  Symfony Validator Component
symfony/var-dumper            v4.1.8  v4.1.8  Symfony mechanism for exploring and dumping PHP variables
symfony/web-profiler-bundle   v4.1.8  v4.1.8  Symfony WebProfilerBundle
symfony/webpack-encore-bundle v1.0.0  v1.0.0  Integration with your Symfony app & Webpack Encore!
symfony/yaml                  v4.1.8  v4.1.8  Symfony Yaml Component

```

#### PHP version

```
$ php -v

PHP 7.1.23 (cli) (built: Oct 16 2018 01:03:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

## Subject

I cannot [add custom template](https://sonata-project.org/bundles/admin/master/doc/reference/templates.html) via `sonata_admin.yaml` config:

```
sonata_admin:
    templates:
        custom: 'SonataAdmin/CRUD/list__custom.html.twig'
```

## Actual results

```
 (1/1) InvalidConfigurationException
Unrecognized option "custom" under "sonata_admin.templates"
```

**Comment by kunicmarko20** [comment] 2018-12-06 14:30
[Here](https://sonata-project.org/bundles/admin/master/doc/reference/templates.html#configuring-templates)  you can see the list of templates that you can configure, `custom` is not a key there. Closing as this is not a bug.

**Closed by kunicmarko20** 2018-12-06 14:30 UTC
