### ISSUE TITLE
[BUG] Scrolling down nav bar menu not working on mobi

### ISSUE THREAD

**Issue by artggd** [sonata-project/SonataAdminBundle#4289] opened 2017-01-24 15:07 UTC
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.11.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.0              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.2.0              Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.1.3              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.0              Lightweight Exporter library
sonata-project/intl-bundle               2.3.0              Symfony SonataIntlBundle

```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/monolog-bundle                   v2.12.1            Symfony MonologBundle
symfony/phpunit-bridge                   v3.2.2             Symfony PHPUnit Bridge
symfony/polyfill-apcu                    v1.3.0             Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu                v1.3.0             Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring                v1.3.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                   v1.3.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70                   v1.3.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                    v1.3.0             Symfony utilities for portability of PHP codes
symfony/security-acl                     v3.0.0             Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle               v2.4.2             Symfony SwiftmailerBundle
symfony/symfony                          v3.1.9             The Symfony PHP framework

```

#### PHP version

```bash
$ php -v
PHP 7.0.14 
```

## Subject

On a small screen, the nav menu doesn't scroll when the page content's height is smaller than the menu itself.

## Steps to reproduce
1. Find a page with as little content as possible.
1. Open it on a mobile device (landscape mode ideally).
1. Scroll down the very bottom.
## Expected results
<img width="747" alt="capture d ecran 2017-01-24 a 15 57 54" src="https://cloud.githubusercontent.com/assets/1837559/22252306/01504758-e24e-11e6-9d44-e8fdca0a7fb5.png">

_Note:_ This screenshot is from AdminLTE, showing that the bug appears on SonataAdmin's side.

## Actual results
<img width="708" alt="capture d ecran 2017-01-24 a 15 58 15" src="https://cloud.githubusercontent.com/assets/1837559/22252310/06fda768-e24e-11e6-86de-2764ea31c65f.png">
(Screenshot from Sonata Admin demo)

As shown here, the last item of the menu is barely visible, though the bottom of the page is reached.

Cheers

**Comment by jordisala1991** [comment] 2018-04-02 19:42
Probably fixed since: https://github.com/sonata-project/SonataAdminBundle/pull/4335

I can't reproduce your issue, so closing for now. If you still having this issue with new versions of Sonata, please ping me to reopen.

**Closed by jordisala1991** 2018-04-02 19:42 UTC
