### ISSUE TITLE
SonataAdmin and it's bundles Symfony 2.8/3.0 support, docs?

### ISSUE THREAD

**Issue by reypm** [sonata-project/SonataAdminBundle#3467] opened 2015-12-05 15:06 UTC
As specified in [this][1] document SonataAdmin supports Symfony 2.8/3.0 but what about the rest of the bundles? I mean: SonataDoctrineORMAdminBundle, SonataUserBundle and so on? They are compatible too or is a work in progress? I would like to start a new fresh project using Symfony 2.8 LTS but I need to know first if I can use SonataAdmin as I did in Symfony 2.7 meaning without problems. Also where I can find the updated documentation for installation?
 [1]: https://docs.google.com/spreadsheets/d/1GOxJ2lNpLxN12YyZ87Bhsxb0iLAQ7e4UDZbJSly8Sy8/edit#gid=0

**Comment by sylvaindeloux** [comment] 2015-12-08 13:54
I think this is coming, just wait a few days more… #soon

**Comment by paquitodev** [comment] 2015-12-08 14:33
@sylvaindeloux great, I can waits a few days

**Comment by rande** [comment] 2015-12-08 14:47
@paquitodev the more occurate doc about bundles version support is : https://docs.google.com/spreadsheets/d/1fSpS10nzlEj9HE-GdZ-BHcxileEzHwRIzLlNfdNtZ2k/edit#gid=0

**Comment by paquitodev** [comment] 2015-12-08 14:51
@rande I know I shouldn't ask for ETA but in a big word how many time will you plan to release a stable Symfony 2.8/Symfony 3.0 release of SonataAdmin bundle and Features (I mean for example UserBundle)? I did see here https://docs.google.com/spreadsheets/d/1GOxJ2lNpLxN12YyZ87Bhsxb0iLAQ7e4UDZbJSly8Sy8/edit#gid=0 that Sonata is already fully compatible with SF 3.0 but I don't think so, I am wrong?

**Comment by rande** [comment] 2015-12-08 14:56
The core bundles : Core, Block, Admin and DoctrineOrm should work with SF2.8 and 3.0 with potentials regressions but I least I have something working (https://twitter.com/sonataproject/status/673895649386057728).

Other feature bundles does not work with SF3.0 due to dependencies issues. They should work with 2.8.

**Comment by paquitodev** [comment] 2015-12-08 15:00
@rande can you share a working `composer.json` (if possible with Sonata User) since I am trying to get all working on Symfony 2.8 but I can't get it to work as should be

**Comment by ejkun** [comment] 2015-12-15 13:39
I'm trying to use Symfony 3.0 with SonataAdmin but apparently SonataAdmin is trying to use a interface that don't exist in Symfony 3.0.

**Comment by rande** [comment] 2015-12-15 13:43
@ejkun Can you named the interface ?

**Comment by ejkun** [comment] 2015-12-15 13:44
DomainObjectInterface

**Comment by rande** [comment] 2015-12-15 13:46
The Interface is part of https://github.com/symfony/security-acl/blob/master/composer.json

**Comment by pmithrandir** [comment] 2015-12-30 10:36
Hello,
This is indeed a bug then... as symfony/security-acl should be required by sonata if it's a dependency in composer.json.

Pierre

**Comment by Soullivaneuh** [comment] 2016-05-17 14:30
Closing this for now. If the problem still persist on admin-bundle 3.x, feel free to open another one.

**Closed by Soullivaneuh** 2016-05-17 14:30 UTC
