### ISSUE TITLE
Missing argument 1 for FOS\UserBundle\Model\Group::__construct() when trying to add FOSGroup

### ISSUE THREAD

**Issue by vasilvestre** [sonata-project/SonataAdminBundle#4212] opened 2016-11-23 10:23 UTC
#### Basic Sonata package ORM 

sonata-project/admin-bundle              3.9.0 The missing Symfony Admin Ge...
sonata-project/block-bundle              3.2.0 Symfony SonataBlockBundle
sonata-project/cache                     1.0.7 Cache library
sonata-project/core-bundle               3.1.1 Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.1.1 Symfony Sonata / Integrate D...
sonata-project/exporter                  1.7.0 Lightweight Exporter library

#### Symfony packages

symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.1.3  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* func...
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related ...
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5....
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7....
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP...
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access...
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v3.1.3  The Symfony PHP framework

#### PHP version

```bash
PHP 7.0.13-1+deb.sury.org~yakkety+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-1+deb.sury.org~yakkety+1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

## Subject

I was trying to add group when an error come, only at creation, not at edit

## Steps to reproduce

Typical instalation, create GroupAdmin and try to add a group

## Expected results

Just a form with information to create

## Actual results

```
[2016-11-23 10:49:47] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: Missing argument 1 for FOS\UserBundle\Model\Group::__construct(), called in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/sonata-project/doctrine-orm-admin-bundle/Model/ModelManager.php on line 516 and defined" at /home/vsilvestre/Projets/DemandAdministratorApp/vendor/friendsofsymfony/user-bundle/Model/Group.php line 40 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Missing argument 1 for FOS\\UserBundle\\Model\\Group::__construct(), called in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/sonata-project/doctrine-orm-admin-bundle/Model/ModelManager.php on line 516 and defined at /home/vsilvestre/Projets/DemandAdministratorApp/vendor/friendsofsymfony/user-bundle/Model/Group.php:40)"}
```

## FIX

I've overriden `getNewInstance()` method in `GroupAdmin` in this way :

```php
    public function getNewInstance()
    {
        return new Group('');
    }
```

Now it work. Don't know if it's normal or whatever else project, but now it work.

**Comment by greg0ire** [comment] 2016-11-23 10:42
Can you show us a strack trace?

**Comment by vasilvestre** [comment] 2016-11-23 11:09
@greg0ire that's the only one left, I clean my logs so often, sorry !

**Comment by greg0ire** [comment] 2016-11-23 11:11
> that's the only one left

What? I don't understand… please reproduce the bug on your development environment and provide us with a stack trace.

**Comment by vasilvestre** [comment] 2016-11-23 11:22
`[2016-11-23 12:21:44] php.INFO: This class is deprecated since 3.2 and will be removed with the 4.0 release.Use Sonata\BlockBundle\Block\Block\Service\AdminBlockServiceInterface instead. {"type":16384,"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":14776,"level":28928,"stack":[{"function":"handleError","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":14776,"function":"trigger_error"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php","line":88,"args":["/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php"],"function":"require_once"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":374,"function":"load","class":"Symfony\\Component\\ClassLoader\\ClassCollectionLoader","type":"::"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":110,"function":"doLoadClassCache","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":166,"function":"boot","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/web/app_dev.php","line":30,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"}]} []
[2016-11-23 12:21:44] php.INFO: This class is deprecated since 3.2 and will be removed with the 4.0 release.Use Sonata\BlockBundle\Block\Block\Service\AbstractBlockService instead. {"type":16384,"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":14833,"level":28928,"stack":[{"function":"handleError","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":14833,"function":"trigger_error"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php","line":88,"args":["/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php"],"function":"require_once"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":374,"function":"load","class":"Symfony\\Component\\ClassLoader\\ClassCollectionLoader","type":"::"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":110,"function":"doLoadClassCache","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":166,"function":"boot","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/web/app_dev.php","line":30,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"}]} []
[2016-11-23 12:21:44] request.INFO: Matched route "{route}". {"route":"admin_mobileangelo_core_group_create","route_parameters":{"_controller":"Sonata\\AdminBundle\\Controller\\CRUDController::createAction","_sonata_admin":"admin.group","_sonata_name":"admin_mobileangelo_core_group_create","_route":"admin_mobileangelo_core_group_create"},"request_uri":"http://dispatch.mobileangelo/app_dev.php/admin/mobileangelo/core/group/create","method":"GET"} []
[2016-11-23 12:21:44] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2016-11-23 12:21:44] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.locked AS locked_9, t0.expires_at AS expires_at_10, t0.confirmation_token AS confirmation_token_11, t0.password_requested_at AS password_requested_at_12, t0.roles AS roles_13, t0.credentials_expire_at AS credentials_expire_at_14, t0.id AS id_15, t0.firstname AS firstname_16, t0.lastname AS lastname_17, t0.path_picture AS path_picture_18 FROM fos_user t0 WHERE t0.id = ? LIMIT 1 [17] []
[2016-11-23 12:21:44] security.DEBUG: User was reloaded from a user provider. {"username":"valentin.silvestre@laposte.net","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-11-23 12:21:44] php.DEBUG: The Sonata\AdminBundle\Admin\AbstractAdmin::setTranslator method is deprecated since version 3.9 and will be removed in 4.0.16384 {"type":1024,"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":8812,"level":28928} []
[2016-11-23 12:21:44] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: Missing argument 1 for FOS\UserBundle\Model\Group::__construct(), called in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/sonata-project/doctrine-orm-admin-bundle/Model/ModelManager.php on line 516 and defined" at /home/vsilvestre/Projets/DemandAdministratorApp/vendor/friendsofsymfony/user-bundle/Model/Group.php line 40 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Missing argument 1 for FOS\\UserBundle\\Model\\Group::__construct(), called in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/sonata-project/doctrine-orm-admin-bundle/Model/ModelManager.php on line 516 and defined at /home/vsilvestre/Projets/DemandAdministratorApp/vendor/friendsofsymfony/user-bundle/Model/Group.php:40)"} []
[2016-11-23 12:21:44] php.INFO: The possibility to register the same extension twice ("Text") is deprecated since version 1.23 and will be removed in Twig 2.0. Use proper PHP inheritance instead. {"type":16384,"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":3856,"level":28928,"stack":[{"function":"handleError","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":3856,"function":"trigger_error"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/appDevDebugProjectContainer.php","line":7744,"function":"addExtension","class":"Twig_Environment","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php","line":275,"function":"getTwigService","class":"appDevDebugProjectContainer","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/appDevDebugProjectContainer.php","line":7772,"function":"get","class":"Symfony\\Component\\DependencyInjection\\Container","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php","line":275,"function":"getTwig_Controller_ExceptionService","class":"appDevDebugProjectContainer","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":2974,"function":"get","class":"Symfony\\Component\\DependencyInjection\\Container","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":2424,"function":"createController","class":"Symfony\\Bundle\\FrameworkBundle\\Controller\\ControllerResolver","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/TraceableControllerResolver.php","line":58,"function":"getController","class":"Symfony\\Component\\HttpKernel\\Controller\\ControllerResolver","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php","line":136,"function":"getController","class":"Symfony\\Component\\HttpKernel\\Controller\\TraceableControllerResolver","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php","line":68,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php","line":50,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->"},{"function":"onKernelException","class":"Symfony\\Component\\HttpKernel\\EventListener\\ExceptionListener","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php","line":61,"function":"call_user_func"},{"function":"__invoke","class":"Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":2144,"function":"call_user_func"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":2059,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php","line":136,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php","line":230,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php","line":79,"function":"handleException","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":169,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/web/app_dev.php","line":30,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"}]} []
[2016-11-23 12:21:44] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2016-11-23 12:21:44] php.INFO: This class is deprecated since 3.2 and will be removed with the 4.0 release.Use Sonata\BlockBundle\Block\Block\Service\AdminBlockServiceInterface instead. {"type":16384,"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":14776,"level":28928,"stack":[{"function":"handleError","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":14776,"function":"trigger_error"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php","line":88,"args":["/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php"],"function":"require_once"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":374,"function":"load","class":"Symfony\\Component\\ClassLoader\\ClassCollectionLoader","type":"::"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":110,"function":"doLoadClassCache","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":166,"function":"boot","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/web/app_dev.php","line":30,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"}]} []
[2016-11-23 12:21:44] php.INFO: This class is deprecated since 3.2 and will be removed with the 4.0 release.Use Sonata\BlockBundle\Block\Block\Service\AbstractBlockService instead. {"type":16384,"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":14833,"level":28928,"stack":[{"function":"handleError","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":14833,"function":"trigger_error"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php","line":88,"args":["/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php"],"function":"require_once"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":374,"function":"load","class":"Symfony\\Component\\ClassLoader\\ClassCollectionLoader","type":"::"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":110,"function":"doLoadClassCache","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":166,"function":"boot","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/web/app_dev.php","line":30,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"}]} []
[2016-11-23 12:21:44] request.INFO: Matched route "{route}". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"fcddb0","_route":"_wdt"},"request_uri":"http://dispatch.mobileangelo/app_dev.php/_wdt/fcddb0","method":"GET"} []
[2016-11-23 12:21:44] php.INFO: The possibility to register the same extension twice ("Text") is deprecated since version 1.23 and will be removed in Twig 2.0. Use proper PHP inheritance instead. {"type":16384,"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":3856,"level":28928,"stack":[{"function":"handleError","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":3856,"function":"trigger_error"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/appDevDebugProjectContainer.php","line":7744,"function":"addExtension","class":"Twig_Environment","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php","line":275,"function":"getTwigService","class":"appDevDebugProjectContainer","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/appDevDebugProjectContainer.php","line":8019,"function":"get","class":"Symfony\\Component\\DependencyInjection\\Container","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php","line":275,"function":"getWebProfiler_Controller_ProfilerService","class":"appDevDebugProjectContainer","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":2974,"function":"get","class":"Symfony\\Component\\DependencyInjection\\Container","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php","line":2424,"function":"createController","class":"Symfony\\Bundle\\FrameworkBundle\\Controller\\ControllerResolver","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/TraceableControllerResolver.php","line":58,"function":"getController","class":"Symfony\\Component\\HttpKernel\\Controller\\ControllerResolver","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php","line":136,"function":"getController","class":"Symfony\\Component\\HttpKernel\\Controller\\TraceableControllerResolver","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php","line":68,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":169,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->"},{"file":"/home/vsilvestre/Projets/DemandAdministratorApp/web/app_dev.php","line":30,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->"}]} []
`
@greg0ire

**Comment by greg0ire** [comment] 2016-11-23 11:28
from `CONTRIBUTING.md` : 

> If your issue is an error page, you must provide us with a stack trace. With recent versions of Symfony, you can even get stack traces as plain text at the end of the page. Just look for "Stack Trace (Plain Text)", and copy/paste what you see. Do not make a screenshot of the stack trace, as screenshots are not indexed by search engines and will make it difficult for other people to find your bug report. If you have an issue when using the Symfony CLI, use the -vvv option to get a stack trace.

Is this what you did? Because this stack trace is very hard to read.

**Comment by vasilvestre** [comment] 2016-11-23 12:15
@greg0ire Sorry you just leaned me stack trace..
`[1] Symfony\Component\Debug\Exception\ContextErrorException: Warning: Missing argument 1 for FOS\UserBundle\Model\Group::__construct(), called in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/sonata-project/doctrine-orm-admin-bundle/Model/ModelManager.php on line 516 and defined
    at n/a
        in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/friendsofsymfony/user-bundle/Model/Group.php line 40

    at Symfony\Component\Debug\ErrorHandler->handleError('2', 'Missing argument 1 for FOS\UserBundle\Model\Group::__construct(), called in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/sonata-project/doctrine-orm-admin-bundle/Model/ModelManager.php on line 516 and defined', '/home/vsilvestre/Projets/DemandAdministratorApp/vendor/friendsofsymfony/user-bundle/Model/Group.php', '40', array())
        in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/friendsofsymfony/user-bundle/Model/Group.php line 40

    at FOS\UserBundle\Model\Group->__construct()
        in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/sonata-project/doctrine-orm-admin-bundle/Model/ModelManager.php line 516

    at Sonata\DoctrineORMAdminBundle\Model\ModelManager->getModelInstance('MobileAngelo\CoreBundle\Entity\Group')
        in /home/vsilvestre/Projets/DemandAdministratorApp/var/cache/dev/classes.php line 8331

    at Sonata\AdminBundle\Admin\AbstractAdmin->getNewInstance()
        in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/sonata-project/admin-bundle/Controller/CRUDController.php line 492

    at Sonata\AdminBundle\Controller\CRUDController->createAction()
        in  line 

    at call_user_func_array(array(object(CRUDController), 'createAction'), array())
        in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 153

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 68

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /home/vsilvestre/Projets/DemandAdministratorApp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 169

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /home/vsilvestre/Projets/DemandAdministratorApp/web/app_dev.php line 30
`

**Comment by greg0ire** [comment] 2016-11-23 22:29
I've edited your message and deleted our exchange about the stack trace to make this a bit more readable.

**Comment by greg0ire** [comment] 2016-11-23 22:36
Your fix is exactly what is done in [SonataUserBundle](https://github.com/sonata-project/SonataUserBundle/blob/3.x/Admin/Model/GroupAdmin.php#L35). Why not point out you were not using it, and instead say "Typical installation" ? It's not typical at all… Closing.

**Closed by greg0ire** 2016-11-23 22:36 UTC
