### ISSUE TITLE
Form model list missing reference to Media entity

### ISSUE THREAD

**Issue by coryjb** [sonata-project/SonataAdminBundle#2181] opened 2014-06-09 20:45 UTC
Hello!

I am having issues with showing the reference to a Media entity in an Admin. Here's my notes while I track down the issue:

This will say "no selection" (or whatever is used as the placeholder) even after I've verified that the relationship between entities exists in the database.

``` php
->add('logo', 'sonata_type_model_list', ['required' => false], [
    'link_parameters' => array(
        'context' => 'venue',
        'provider' => '',
        'filter' => ['context' => ['value' => 'sonata.media.provider.image']]
    )
])
```

![Reference](http://imgur.com/lz8bC7s.jpg)

After selecting an object, but before saving, the thumbnail/reference shows up. After saving the record the label returns to "no selection."

composer.json excerpt:

``` javascript
"sonata-project/core-bundle": "2.2.*@dev",
"sonata-project/admin-bundle": "2.3.*@dev",
"sonata-project/media-bundle": "2.3.*@dev",
"sonata-project/doctrine-orm-admin-bundle": "2.3.*@dev",
"sonata-project/intl-bundle": "2.2.*@dev",
```

**Comment by core23** [comment] 2016-04-15 17:07
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @coryjb

**Comment by jordisala1991** [comment] 2018-01-31 06:52
Probably a duplicate of the other issue on SonataDoctrineORMAdminBundle. Also very old. Closing

**Closed by jordisala1991** 2018-01-31 06:52 UTC
