### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by mouad-mahfoud** [sonata-project/SonataAdminBundle#5788] opened 2019-12-11 08:48 UTC
I am trying to install sonata admin bundle in a fresh Symfony 5 installation but I get this error :
Problem 1
    - Conclusion: don't install sonata-project/admin-bundle 3.56.1
    - Conclusion: remove twig/twig v3.0.0
    - Installation request for sonata-project/admin-bundle ^3.56 -> satisfiable by sonata-project/admin-bundle[3.56.0, 3.56.1].
    - Conclusion: don't install twig/twig v3.0.0
    - sonata-project/admin-bundle 3.56.0 requires twig/twig ^2.10 -> satisfiable by twig/twig[v2.10.0, v2.11.0, v2.11.1, v2.11.2, v2.11.3, v2.12.0, v2.12.1, v2.12.2].
    - Can only install one of: twig/twig[v2.10.0, v3.0.0].
    - Can only install one of: twig/twig[v2.11.0, v3.0.0].
    - Can only install one of: twig/twig[v2.11.1, v3.0.0].
    - Can only install one of: twig/twig[v2.11.2, v3.0.0].
    - Can only install one of: twig/twig[v2.11.3, v3.0.0].
    - Can only install one of: twig/twig[v2.12.0, v3.0.0].
    - Can only install one of: twig/twig[v2.12.1, v3.0.0].
    - Can only install one of: twig/twig[v2.12.2, v3.0.0].
    - Installation request for twig/twig (locked at v3.0.0) -> satisfiable by twig/twig[v3.0.0].

**Comment by core23** [comment] 2019-12-11 09:07
Feel free to help us supporting symfony 5 @mouad-mahfoud

**Comment by michaelKaefer** [comment] 2019-12-19 07:04
How can we help? Would it be correct to clone the latest version, then upgrade all symfony packages via composer to 5.*, then run the tests and fix all errors? Is that enough? I want to do this in the holidays.

**Comment by core23** [comment] 2019-12-19 07:09
> Would it be correct to clone the latest version, then upgrade all symfony packages via composer to 5.*, then run the tests and fix all errors? 

That's the way you go.

But keep in mind, that we have version lock because of required (dev-)dependencies: https://github.com/sonata-project/SonataAdminBundle/pull/5797#issuecomment-567165651. There are also more third party dependencies that may need an update to work with symfony 5

>  I want to do this in the holidays.

:100: !

**Comment by michaelKaefer** [comment] 2019-12-20 20:17
I think this is too much for me, sorry, somebody else has to do it..

**Comment by Bodarev** [comment] 2019-12-23 12:54
https://github.com/sonata-project/SonataAdminBundle/issues/5786#issuecomment-567935452

help please

**Comment by core23** [comment] 2019-12-23 12:56
Feel free to help with this by contributing @Bodarev

**Comment by MrPoliteGrizlyM** [comment] 2019-12-29 07:23
Have same problem, but with assets: 
```
Problem 1
    - sonata-project/admin-bundle 3.56.1 requires symfony/asset ^3.4.30 || ^4.2 -> no matching package found.
    - sonata-project/admin-bundle 3.56.0 requires symfony/asset ^3.4.30 || ^4.2 -> no matching package found.
    - Installation request for sonata-project/admin-bundle ^3.56 -> satisfiable by sonata-project/admin-bundle[3.56.0, 3.56.1]. 
```

**Comment by VincentLanglet** [comment] 2020-01-27 15:29
> I am trying to install sonata admin bundle in a fresh Symfony 5 installation but I get this error :
> Problem 1
> - Conclusion: don't install sonata-project/admin-bundle 3.56.1
> - Conclusion: remove twig/twig v3.0.0
> - Installation request for sonata-project/admin-bundle ^3.56 -> satisfiable by sonata-project/admin-bundle[3.56.0, 3.56.1].
> - Conclusion: don't install twig/twig v3.0.0
> - sonata-project/admin-bundle 3.56.0 requires twig/twig ^2.10 -> satisfiable by twig/twig[v2.10.0, v2.11.0, v2.11.1, v2.11.2, v2.11.3, v2.12.0, v2.12.1, v2.12.2].
> - Can only install one of: twig/twig[v2.10.0, v3.0.0].
> - Can only install one of: twig/twig[v2.11.0, v3.0.0].
> - Can only install one of: twig/twig[v2.11.1, v3.0.0].
> - Can only install one of: twig/twig[v2.11.2, v3.0.0].
> - Can only install one of: twig/twig[v2.11.3, v3.0.0].
> - Can only install one of: twig/twig[v2.12.0, v3.0.0].
> - Can only install one of: twig/twig[v2.12.1, v3.0.0].
> - Can only install one of: twig/twig[v2.12.2, v3.0.0].
> - Installation request for twig/twig (locked at v3.0.0) -> satisfiable by twig/twig[v3.0.0].

This is not an issue with Symfony 5 but only Twig 3.
I think two different issues should be created. One for Sf5 and one for Twig 3.

**Comment by greg0ire** [comment] 2020-01-27 19:49
Yeah plus, starting with just Twig 3 might be easier.

**Comment by jorrit** [comment] 2020-01-30 15:54
It is clear that Sonata Admin doesn't work with Symfony 5. Until support is added, perhaps a warning could be added to the installation instructions? I can submit a PR for this, but first I'd like to know if this sounds like a good idea.

**Comment by core23** [comment] 2020-01-30 15:58
> It is clear that Sonata Admin doesn't work with Symfony 5. Until support is added, perhaps a warning could be added to the installation instructions? I can submit a PR for this, but first I'd like to know if this sounds like a good idea.

If I got you right: You want a warning, that we don't support symfony 5? You have composer for that

**Comment by jorrit** [comment] 2020-01-30 16:06
What I mean is that it could be helpful to list somewhere in the docs, let's say at https://sonata-project.org/bundles/admin/3-x/doc/getting_started/installation.html, which Symfony version(s) are supported.

Composer does give warnings when installing on Symfony 5, but the warnings given refer to symfony/asset not being the right version, it does not clearly say what the root problem is: Sonata Admin is compatible with Symfony up to 4, not 5.

Perhaps the message currently given by composer is sufficient for most users, but a small addition to the manual would not hurt, I think.

**Comment by core23** [comment] 2020-01-30 16:12
IMHO it's overhead to update two places for every depedency. If we start to list supported symfony versions, we must also list supported versions of php, doctrine, twig, phpunit, ...

**Comment by VincentLanglet** [comment] 2020-01-30 16:15
> IMHO it's overhead to update two places for every depedency. If we start to list supported symfony versions, we must also list supported versions of php, doctrine, twig, phpunit, ...

I agree

In the initial issue, composer return the following message.
```
sonata-project/admin-bundle 3.56.0 requires twig/twig ^2.10
```
This seems pretty clear.

**Comment by greg0ire** [comment] 2020-01-30 18:48
If anyone wants to help, here is where to start:

```
composer why-not twig/twig 3   
jms/translation-bundle       1.4.4   requires  twig/twig (^1.27 || ^2.0)  
sonata-project/block-bundle  3.18.3  requires  twig/twig (^1.34 || ^2.0)  
sonata-project/core-bundle   3.18.0  requires  twig/twig (^1.34 || ^2.0)  
sonata-project/intl-bundle   2.7.0   requires  twig/twig (^2.9)           
twig/extensions              v1.5.4  requires  twig/twig (^1.27|^2.0)
```

**Comment by jaikdean** [comment] 2020-02-20 15:30
As an update to @greg0ire's last comment…

- There is [an issue open](https://github.com/schmittjoh/JMSTranslationBundle/issues/517) for updating `jms/translation-bundle`
- `sonata-project/block-bundle` 4.0.0 [added support](https://github.com/sonata-project/SonataBlockBundle/blob/4.x/CHANGELOG.md#400---2019-11-24) for Symfony 4 and Twig 3
- It appears `sonata-project/core-bundle` is being dropped (see #5906)
- It appears `sonata-project/intl-bundle` is being dropped (see #5835)
- It appears `twig/extensions` is [abandoned](https://github.com/twigphp/Twig-extensions)

**Comment by VincentLanglet** [comment] 2020-02-20 16:44
> * It appears `twig/extensions` is [abandoned](https://github.com/twigphp/Twig-extensions)

And you create the issue https://github.com/sonata-project/SonataAdminBundle/issues/5909

**Comment by greg0ire** [comment] 2020-02-20 18:00
See also: 
- https://github.com/schmittjoh/JMSTranslationBundle/pull/519
- https://github.com/schmittjoh/JMSTranslationBundle/pull/520

**Comment by goetas** [comment] 2020-02-21 21:20
> schmittjoh/JMSTranslationBundle#519
> schmittjoh/JMSTranslationBundle#520

Both PR have been merged

**Comment by greg0ire** [comment] 2020-02-27 21:25
@goetas here is one more : https://github.com/schmittjoh/JMSTranslationBundle/pull/522 :)

**Comment by VincentLanglet** [comment] 2020-03-05 00:05
> * `sonata-project/block-bundle` 4.0.0 [added support](https://github.com/sonata-project/SonataBlockBundle/blob/4.x/CHANGELOG.md#400---2019-11-24) for Symfony 5 and Twig 3

The AdminBundle will need to drop support of 3.x blockbundle to be Symfony is 5 compatible.

**Comment by jaikdean** [comment] 2020-03-05 09:20
> The AdminBundle will need to drop support of 3.x blockbundle to be Symfony is 5 compatible or we'll need to fix some deprecation on the 3.x version.

AdminBundle will need to add support for 4.x of BlockBundle. It wouldn't necessarily need to drop support for 3.x.

**Comment by VincentLanglet** [comment] 2020-03-05 09:24
Oh yeah indeed.
It will use both Symfony 5 and BlockBundle 4 or both Symfony 4 and BlockBundle 3.

**Comment by bhyassine** [comment] 2020-03-05 14:26
So it is not possible yet to install Sonata on a Symfony 5 that uses Twig 3?

**Comment by VincentLanglet** [comment] 2020-03-05 14:41
> So it is not possible yet to install Sonata on a Symfony 5 that uses Twig 3?

No

**Comment by greg0ire** [comment] 2020-03-05 20:02
> Does updating the major version of a dependency is a BC-break @greg0ire ?

No it is not.

**Comment by parijke** [comment] 2020-03-13 10:56
@greg0ire how can I help?

**Comment by VincentLanglet** [comment] 2020-03-13 12:30
@parijke You can run `composer why-not`
![image](https://user-images.githubusercontent.com/9052536/76620236-02046e80-652d-11ea-922a-0a47db4065e9.png)

And try to fix one by one the dependency.

For example, the admin-bundle should support `block-bundle@5` and stop using the `core-bundle`. And then, we'll have to fix all the deprecation in the admin-bundle.

**Comment by parijke** [comment] 2020-03-15 09:20
@greg0ire dont know exactly what you mean. Can you delegate me some simple tasks or explain what we'll have to do?

**Comment by greg0ire** [comment] 2020-03-15 10:11
@parijke I've had a look at the situation on the admin bundle, and it's complicated, because it depends on other bundles… maybe you could start with https://github.com/sonata-project/exporter ? It has no dependencies with sonata bundles.

If I run `composer show symfony/*` on that project, I get the following list:

```
symfony/config                     v4.4.5  Symfony Config Component
symfony/console                    v4.4.5  Symfony Console Component
symfony/debug                      v4.4.5  Symfony Debug Component
symfony/dependency-injection       v4.4.5  Symfony DependencyInjection Component
symfony/error-handler              v4.4.5  Symfony ErrorHandler Component
symfony/event-dispatcher           v4.4.5  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.7  Generic abstractions related to dispatching event
symfony/filesystem                 v5.0.5  Symfony Filesystem Component
symfony/http-foundation            v4.4.5  Symfony HttpFoundation Component
symfony/http-kernel                v4.4.5  Symfony HttpKernel Component
symfony/inflector                  v5.0.5  Symfony Inflector Component
symfony/mime                       v5.0.5  A library to manipulate MIME messages
symfony/phpunit-bridge             v4.4.5  Symfony PHPUnit Bridge
symfony/polyfill-ctype             v1.14.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-idn          v1.14.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring          v1.14.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.14.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.14.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/property-access            v4.4.5  Symfony PropertyAccess Component
symfony/routing                    v4.4.5  Symfony Routing Component
symfony/service-contracts          v2.0.1  Generic abstractions related to writing services
symfony/var-dumper                 v5.0.5  Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                       v5.0.5  Symfony Yaml Component
```

If I ask composer why the config component is not in version 5, I can see that it's only because we don't allow it in `composer.json`: https://github.com/sonata-project/exporter/blob/2.x/composer.json#L30

Simple task you can do:
1. clone the exporter project
2. make sure you successfully run the tests
3. allow symfony/config 5 and run the test again
4. fix the tests that are broken
5. repeat steps above with `symfony/console`, and so on.

**Comment by greg0ire** [comment] 2020-03-17 07:11
Regarding Twig 3: issues with JMSTranslationBundle are fixed :)

```
composer why-not twig/twig 3
sonata-project/admin-bundle  3.x-dev  requires  twig/twig (^2.12)          
sonata-project/block-bundle  3.18.4   requires  twig/twig (^1.34 || ^2.0)  
sonata-project/core-bundle   3.18.0   requires  twig/twig (^1.34 || ^2.0)  
twig/extensions              v1.5.4   requires  twig/twig (^1.27|^2.0)
```

**Comment by parijke** [comment] 2020-03-17 11:53
Gonna try it

**Comment by VincentLanglet** [comment] 2020-03-17 12:21
> Ok, so I cloned the repo... but then step 2. how do I run the tests?

`make test` works if you have `phpunit` installed.

But you can use `vendor/bin/simple-phpunit` too I think

**Comment by parijke** [comment] 2020-03-17 12:46
ok, I had to do a composer install before step 2? Otherwise I do not have a vendor directory. Now it outputs:
../vendor/bin/simple-phpunit ExporterTest.php
PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

Testing Sonata\Exporter\Tests\ExporterTest
FFWEEEEE                                                            8 / 8 (100%)

Time: 26 ms, Memory: 6.00 MB

There were 5 errors:

1) Sonata\Exporter\Tests\ExporterTest::testGetResponse with data set #0 ('json', 'foo.json', 'application/json', '#foo#')
Error: Class 'Sonata\Exporter\Source\ArraySourceIterator' not found

/home/paul/www/exporter/tests/ExporterTest.php:63

2) Sonata\Exporter\Tests\ExporterTest::testGetResponse with data set #1 ('xml', 'foo.xml', 'text/xml', '#foo#')
Error: Class 'Sonata\Exporter\Source\ArraySourceIterator' not found

/home/paul/www/exporter/tests/ExporterTest.php:63

3) Sonata\Exporter\Tests\ExporterTest::testGetResponse with data set #2 ('xls', 'foo.xls', 'application/vnd.ms-excel', '#foo#')
Error: Class 'Sonata\Exporter\Source\ArraySourceIterator' not found

/home/paul/www/exporter/tests/ExporterTest.php:63

4) Sonata\Exporter\Tests\ExporterTest::testGetResponse with data set #3 ('csv', 'foo.csv', 'text/csv', '#foo#')
Error: Class 'Sonata\Exporter\Source\ArraySourceIterator' not found

/home/paul/www/exporter/tests/ExporterTest.php:63

5) Sonata\Exporter\Tests\ExporterTest::testGetResponse with data set #4 ('made-up', 'foo.made-up', 'application/made-up', '##')
Error: Class 'Sonata\Exporter\Source\ArraySourceIterator' not found

/home/paul/www/exporter/tests/ExporterTest.php:63

--

There was 1 warning:

1) Sonata\Exporter\Tests\ExporterTest::testGetAvailableFormats
Cannot stub or mock class or interface "Sonata\Exporter\Writer\TypedWriterInterface" which does not exist

--

There were 2 failures:

1) Sonata\Exporter\Tests\ExporterTest::testFilter
Failed asserting that exception message 'Cannot stub or mock class or interface "Sonata\Exporter\Source\SourceIteratorInterface" which does not exist' contains 'Invalid "foo" format'.

2) Sonata\Exporter\Tests\ExporterTest::testConstructorRejectsNonTypedWriters
Failed asserting that exception of type "Error" matches expected exception "TypeError". Message was: "Class 'Sonata\Exporter\Exporter' not found" at
/home/paul/www/exporter/tests/ExporterTest.php:45
.

ERRORS!
Tests: 8, Assertions: 3, Errors: 5, Failures: 2, Warnings: 1.

**Comment by VincentLanglet** [comment] 2020-03-17 12:52
> ok, I had to do a composer install before step 2? Otherwise I do not have a vendor directory. 

Yes. You always have to run `composer install` if you want to correctly work on a repository ;)

When I
- Clone
- Run composer install
- Run vendor/bin/simple-phpunit

This is what I get
![image](https://user-images.githubusercontent.com/9052536/76857634-25455b80-6856-11ea-9732-d793a6457990.png)

Just run `vendor/bin/simple-phpunit` in the root of the project ; not in the `/tests/` folder @parijke

**Comment by parijke** [comment] 2020-03-17 13:18
Ahhhh ok, that worked, same result :-) already learned a few things

**Comment by parijke** [comment] 2020-03-17 13:42
So I changed the line 
 "symfony/config": "^3.4 || ^4.0 || ^5.0", to allow it.... run the tests again, they run fine....

but, is it tested against 5.x then? I don't think so or I do not understand it. composer show:
symfony/config                                   v4.4.5

**Comment by VincentLanglet** [comment] 2020-03-17 13:53
> So I changed the line
> "symfony/config": "^3.4 || ^4.0 || ^5.0", to allow it.... run the tests again, they run fine....
> 
> but, is it tested against 5.x then? I don't think so or I do not understand it. composer show:
> symfony/config v4.4.5

I think you have to run `composer update` after allowing the v5 in order to install it.

**Comment by parijke** [comment] 2020-03-17 14:14
Sure of course.... so I did. And after that I saw 
`Updating symfony/config (v4.4.5 => v5.0.5): Loading from cache`

Then I ran the tests again, all passed and two deprecations

```
PHPUnit 8.5.0 by Sebastian Bergmann and contributors.

Testing Sonata Exporter Test Suite
................................................................. 65 / 98 ( 66%)
.................................                                 98 / 98 (100%)

Time: 1 second, Memory: 42.00 MB

OK (98 tests, 306 assertions)

Legacy deprecation notices (2)

```

**Comment by parijke** [comment] 2020-03-17 14:36
ok, I got all the symfony/* allowed to be 5 and all tests pass. What now?

**Comment by VincentLanglet** [comment] 2020-03-17 14:49
Create a PR

**Comment by parijke** [comment] 2020-03-17 14:50
Can you help me with that?

**Comment by VincentLanglet** [comment] 2020-03-17 14:52
```
git checkhout -b myNewBranch
git add theFileIChanged
git commit -m TheMessageOfMyCommit
git push
```

Then https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request

**Comment by parijke** [comment] 2020-03-17 14:54
I think I did....
https://github.com/sonata-project/exporter/pull/330

**Comment by parijke** [comment] 2020-03-17 15:07
So I think the steps are

1. Fork the repo
2. clone the exporter project
3. composer install
4. make sure you successfully run the tests
5. allow symfony/config 5
6. composer update
7. run the test again
8. fix the tests that are broken
9. repeat steps above with symfony/console, and so on.
10. commit the changes
11. create pull request

**Comment by greg0ire** [comment] 2020-03-17 18:03
Thanks for your contribution @parijke ! If you want to try your hand on other repositories, please check out the graph on this issue: https://github.com/sonata-project/dev-kit/issues/216 exporter was easy because it's a leaf node of the dependency graph. You might find other leaf node libraries that are not yet compatible with Symfony 5, and do your thing, that will help a lot!

**Comment by parijke** [comment] 2020-03-18 08:14
Yes I want really to help get it ready for symfony 5  (got time as well as I am locked down in Spain for at least two weeks). I looked at the issue/graph but it doesn't make sense to me (yet). Maybe it is easier to delegate some (easy) tasks to me that I can finish with a little help sometimes, like the exporter thing. I learned a few things along the way about runnings tests and the github workflow.  
Maybe it is better to discuss this further in slack as well?

**Comment by greg0ire** [comment] 2020-03-18 08:17
What I was proposing is that you try exactly what you did for the exporter, but for other libs. You can find the exporter on the graph, it's a leaf node (arrows come to it, but do not come out of it). There are some other leaf nodes on this graph, like for instance https://github.com/sonata-project/GoogleAuthenticator or https://github.com/sonata-project/SonataFormatterBundle. Can you look if those are sf5 compatible, and make them compatible if that's not the case?

**Comment by adriendarki** [comment] 2020-04-09 15:31
it is still impossible to install it on symfony 5 

``    "Your  equirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sonata-project/admin-bundle ^3.64 -> satisfiable by sonata-project/admin-bundle[3.64.0].
    - sonata-project/admin-bundle 3.64.0 requires symfony/asset ^4.3 -> no matching package found.
"  ``

**Comment by VincentLanglet** [comment] 2020-04-09 15:32
> it is still impossible to install it on symfony 5

Nobody say it was.

**Comment by adriendarki** [comment] 2020-04-09 15:37
> > it is still impossible to install it on symfony 5
> 
> Nobody said it was.

sorry my english is not perfect. I think addition of support symfony 5.0 will result in a compatible

**Comment by VincentLanglet** [comment] 2020-04-09 15:39
> sorry my english is not perfect. I think addition of support symfony 5.0 will result in a compatible

The support of symfony 5.0 is still not fully added. We are still working on it.
Some of the packages provided by sonata are compatible ; but not all.
Since the admin bundle is using a lot of them, it will certainly be the last bundle compatible with symfony 5.

If you want to make some PR to help us, don't hesitate ;)

**Comment by MichaelPerlbach** [comment] 2020-06-04 09:46
Any news on that matter?

**Comment by VincentLanglet** [comment] 2020-06-04 10:00
We're working on it, but that's not easy. You can help us if you want.

**Comment by MichaelPerlbach** [comment] 2020-06-04 11:41
I would be glad if I could be a useful help for you.
Thing is, I am relatively new to Symfony - and I know nothing about the inner workings of Sonata Admin. But if you have tasks I might be able to do within these boundary conditions tell me!

**Comment by wbloszyk** [comment] 2020-06-04 12:09
@MichaelPerlbach 
I think you can extract actions from CRUDController. 
- CRUDListAction
- CRUDEditAction
- CRUD ...
- ...

@VincentLanglet @core23 WDYT?

**Comment by VincentLanglet** [comment] 2020-06-04 18:01
Refactoring is always nice, but I don't see why this would help for Symfony 5 ?

@greg0ire Gave an exemple with sonata-exporter here https://github.com/sonata-project/SonataAdminBundle/issues/5788#issuecomment-599190473

And then ask to do the same for other bundle https://github.com/sonata-project/SonataAdminBundle/issues/5788#issuecomment-600484369.

If we want sonataAdmin to support Symfony 5, we needs that every sonataAdmin dependencies support Symfony 5. So start with the dependencies.

**Comment by wbloszyk** [comment] 2020-06-04 18:19
We can't support symfony5 when we use controller.

**Comment by VincentLanglet** [comment] 2020-06-04 18:21
Ok, you meant extending `AbstractController` instead

**Comment by wbloszyk** [comment] 2020-06-04 18:30
> Ok, you meant extending `AbstractController` instead

This too. I mean more split `CRUDController` to improve extending CRUD actions by user. We should not keep do big controller in next major. We probably can't add support for symfony5 in sonata 3.

**Comment by VincentLanglet** [comment] 2020-06-04 19:06
> I mean more split `CRUDController` to improve extending CRUD actions by user. We should not keep do big controller in next major.

I disagree. Splitting the CRUDController is not needed for Symfony 5.

What are the **minimal** changes needed to be symfony 5 compatible, this is only what we should focus on.

**Comment by jorrit** [comment] 2020-06-05 07:18
> If we want sonataAdmin to support Symfony 5, we needs that every sonataAdmin dependencies support Symfony 5. So start with the dependencies.

Is there an up to date overview of the specific changes that are needed?

**Comment by jorrit** [comment] 2020-06-12 13:32
Just to clarify: is it a goal to have Symfony 5 support in Symfony 3? Or is it a goal for Symfony 3?

**Comment by VincentLanglet** [comment] 2020-06-12 14:55
@wbloszyk Will be the best to answer this 😅

**Comment by wbloszyk** [comment] 2020-06-12 15:01
@VincentLanglet 
https://github.com/sonata-project/SonataBlockBundle/issues/700#issuecomment-643262523

**Comment by wbloszyk** [comment] 2020-06-12 15:20
@jorrit 
In SonataBlockBundle add support for:
- knplabs/knp-menu-bundle ^3.0
- symfony/* ^4.3 || ^5.0

In SonataIntlBundle add support for:
- knplabs/knp-menu-bundle ^3.0
- symfony/* ^4.3 || ^5.0

In SonataAdminBundle add support for:
- doctrine/common ^3.0
- symfony/* ^4.3 || ^5.0

This change will be probably enought to add this support in this bundles.

**Comment by jorrit** [comment] 2020-06-16 09:00
@wbloszyk : Do you mean version 3 of those three modules? Because SonataBlockBundle already has SF5 support but only in version 4.

**Comment by wbloszyk** [comment] 2020-06-16 09:03
Sonata 3 using BlockBundle 3. Add support in Sonata 3 for BlockBundle will be awsome too but much harder.

**Comment by jorrit** [comment] 2020-06-16 09:10
So if I understand it correctly, BlockBundle 3 also has to support Symfony 5?

**Comment by wbloszyk** [comment] 2020-06-16 09:13
All require dependencies have to support symfony 5 too.

**Comment by jorrit** [comment] 2020-06-18 08:48
On https://github.com/sonata-project/SonataAdminBundle/pull/5948#issuecomment-599140668 it was determined that SF 5 compatibility in Sonata 3 is not possible.

**Comment by neimheadh** [comment] 2020-06-22 09:56
Hello everyone.

I just forked the project to work on the Symfony 5 compatibility. I don't know a lot about the Sonata admin bundle background, but for the moment I just changed symfony dependencies to "^5.1", and the `composer install` worked. Of course I have some inheritance errors, I'm working on it, but it seems that the "sonata-project/admin-bundle" sub-dependencies has no problem with  SF 5.1.

As I see with the @jorrit comment, you seem to have blocking problems with knp-menus but.. The issue is closed so maybe not. Idk...

Do you have a clear vision of SF5-compatibility progress on your side?

**Comment by jorrit** [comment] 2020-06-22 10:09
@neimheadh : The issue was closed for the master branch which will one day be Sonata Admin v4 but I am trying to get a statement on whether SF5 support will ever be available for Sonata Admin v3.

**Comment by VincentLanglet** [comment] 2020-06-22 10:36
> On [#5948 (comment)](https://github.com/sonata-project/SonataAdminBundle/pull/5948#issuecomment-599140668) it was determined that SF 5 compatibility in Sonata 3 is not possible.

Only if you can avoid this BC-break.

We try to finish the v4, but it's not easy.

**Comment by neimheadh** [comment] 2020-06-22 12:38
> @neimheadh : The issue was closed for the master branch which will one day be Sonata Admin v4 but I am trying to get a statement on whether SF5 support will ever be available for Sonata Admin v3.

Yeah I see. Indeed I'm working on master branch. Are you interested I push my change on master when I'll be able to use Sonata (dev-master version) on my project?

**Comment by VincentLanglet** [comment] 2020-06-22 12:56
We are really interested by any kind of PR to help us to finish the v4 or to add the Symfony 5 (or twig 3) support.

The current `dev-master` branch can't be used. And that's a big issue, because we can't test manually any PR on the master branch.

The first step would be to fix this and allow to use both the `SonataAdmin` and `SonataDoctrineORMAdmin` dev-master branch together.
I think it's on the @wbloszyk plans, isn't it ?

**Comment by neimheadh** [comment] 2020-06-22 13:20
Yes, I also try to make SonataDoctrineORMAdmin dev-master work on SF.5.1. Btw I see that @SonataAdmin/standard_layout.html.twig needs @SonataCore/FlashMessage/render.html.twig and @SonataTwig/FlashMessage/render.html.twig.

Is it a reason for sonata-project/admin-bundle not having sonata-project/core-bundle & sonata-project/twig-extensions dependencies?

**Comment by VincentLanglet** [comment] 2020-06-22 13:27
> Yes, I also try to make SonataDoctrineORMAdmin dev-master work on SF.5.1. Btw I see that @SonataAdmin/standard_layout.html.twig needs @SonataCore/FlashMessage/render.html.twig and @SonataTwig/FlashMessage/render.html.twig.
> 
> Is it a reason for sonata-project/admin-bundle not having sonata-project/core-bundle & sonata-project/twig-extensions dependencies?

It does have `twig-extension` dependency.
A recent PR removed the Core dependency, I think, by the syntax, it requires @SonataCore/FlashMessage/render.html.twig OR @SonataTwig/FlashMessage/render.html.twig.

**Comment by wbloszyk** [comment] 2020-06-22 13:29
Yes, I'm working on it. 
`@SonataAdmin/standard_layout.html.twig` needs 
`@SonataCore/FlashMessage/render.html.twig` __OR__ `@SonataTwig/FlashMessage/render.html.twig`.

Now I'm working on replace CoreBundle by form- and twig- extensions 0.x. Then upgrade it to extensions 1.x. 
https://github.com/sonata-project/dev-kit/issues/697

To finish it i need improve FlashManager:
https://github.com/sonata-project/twig-extensions/issues/89
https://github.com/sonata-project/twig-extensions/pull/90

At the end support the same BlockBundle version is require to allow use Sonata 3 and Sonata 4 together.

**Comment by neimheadh** [comment] 2020-06-22 13:39
Yep my mistake, it is @SonataCore/FlashMessage/render.html.twig OR @SonataTwig/FlashMessage/render.html.twig.

So if I got it well @wbloszyk, the CoreBundle will be deprecated in the future in favor of SonataTwig (and some others)?

**Comment by wbloszyk** [comment] 2020-06-22 13:43
Correct: https://github.com/sonata-project/SonataCoreBundle#warning-this-bundle-is-deprecated

**Comment by neimheadh** [comment] 2020-06-22 15:25
I finally have a working instance on SF5.1. Here what I had to do :

https://github.com/sonata-project/SonataAdminBundle/compare/master...neimheadh:master
- Changed all sonata-project/admin-bundle symfony dependencies from ^4.3 to ^5.1
- Changed sonata-project/admin-bundle twig dependency from ^2.12.1 to ^3.0
- Changed sonata-project/admin-bundle sonata-project/twig-extensions dependency from ^0.1.1 || ^1.3 to 1.x-dev
- Fix sonata-project/admin-bundle inheritance.

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/compare/master...neimheadh:master
- Changed all sonata-project/doctrine-orm-admin-bundle symfony dependencies from ^4.3 to ^5.1
- Added ^3.0 to sonata-project/doctrine-orm-admin-bundle twig dependency
- Changed sonata-project/doctrine-orm-admin-bundle sonata-project/admin-bundle dependency to dev-master

- Required sonata-project/twig-extensions:1.x-dev on my project
- Required sonata-project/doctrine-extensions:1.x-dev on my project

And I'm good, with an empty Sonata project. I don't want to do the PR now as my dependencies changes are a little bit extreme, with no test for the moment of inheritance changes on SF4 and SF5.0. And I also don't know what are your workflow so... Feel free to tell me how to make my PR on your project if you're interested.

**Comment by neimheadh** [comment] 2020-06-28 09:09
Hello, it's me again.
Again a little change on AdminBundle fixing exception when I create a new admin on SF5.1 - just changed Symfony\Component\Translation\TranslatorInterface dependency to Symfony\Contracts\Translation\TranslatorInterface:
https://github.com/sonata-project/SonataAdminBundle/compare/master...neimheadh:master

**Comment by wbloszyk** [comment] 2020-09-02 10:11
Close this issue in favor for https://github.com/sonata-project/SonataAdminBundle/issues/6365

**Closed by wbloszyk** 2020-09-02 10:11 UTC
Labels: feature, help wanted
