### ISSUE TITLE
Windows composer install error

### ISSUE THREAD

**Issue by kroshp** [sonata-project/SonataAdminBundle#3073] opened 2015-06-24 09:55 UTC
An error occurred when installing from composer on windows:
Symfony/vendor/composer/c1a059ef/sonata-project-SonataAdminBundle-3fbeb00\Resources\public\vendor\x-editable\dist\jquery-editable\jquery-ui-datepicker\css\redmond\images/ui-bg_gloss-wave_55_5c9ccc_500x100.png): failed to open stream: Invalid argument

**Comment by Soullivaneuh** [comment] 2015-06-24 10:12
Which command did you run exactly?

Can you paste full trace of it?

**Comment by kroshp** [comment] 2015-07-03 10:56
Sorry for the late reply:
php composer.phar install --prefer-dist -vvv

**Comment by Soullivaneuh** [comment] 2015-07-03 10:57
> Can you paste full trace of it?

**Comment by kroshp** [comment] 2015-07-03 11:06
I ve just make a composer update and i don't have the problem anymore. May be the problem came from the sonata version.
Here is the trace of the composer update:
Updating dependencies (including require-dev)
  - Removing twig/twig (v1.18.0)
  - Installing twig/twig (v1.18.2)
    Downloading: 100%

  - Removing doctrine/collections (v1.2)
  - Installing doctrine/collections (v1.3.0)
    Downloading: 100%

  - Removing doctrine/cache (v1.4.0)
  - Installing doctrine/cache (v1.4.1)
    Downloading: 100%

  - Removing doctrine/annotations (v1.2.3)
  - Installing doctrine/annotations (v1.2.6)
    Downloading: 100%

  - Removing doctrine/common (v2.4.2)
  - Installing doctrine/common (v2.5.0)
    Downloading: 100%

  - Removing symfony/symfony (v2.5.10)
  - Installing symfony/symfony (v2.5.12)
    Downloading: 100%

  - Removing doctrine/instantiator (1.0.4)
  - Installing doctrine/instantiator (1.0.5)
    Downloading: 100%

  - Removing doctrine/orm (v2.4.7)
  - Installing doctrine/orm (v2.5.0)
    Downloading: 100%

  - Removing sensiolabs/security-checker (v2.0.1)
  - Installing sensiolabs/security-checker (v2.0.5)
    Loading from cache

  - Removing sensio/distribution-bundle (v3.0.19)
  - Installing sensio/distribution-bundle (v3.0.30)
    Downloading: 100%

  - Removing sensio/framework-extra-bundle (v3.0.6)
  - Installing sensio/framework-extra-bundle (v3.0.9)
    Downloading: 100%

  - Removing incenteev/composer-parameter-handler (v2.1.0)
  - Installing incenteev/composer-parameter-handler (v2.1.1)
    Downloading: 100%

  - Removing friendsofsymfony/user-bundle (v1.3.5)
  - Installing friendsofsymfony/user-bundle (v1.3.6)
    Downloading: 100%

  - Removing cocur/slugify (v1.1)
  - Installing cocur/slugify (v1.2)
    Downloading: 100%

  - Removing sonata-project/core-bundle (2.3.1)
  - Installing sonata-project/core-bundle (2.3.4)
    Downloading: 100%

  - Removing sonata-project/cache (1.0.5)
  - Installing sonata-project/cache (1.0.6)
    Downloading: 100%

  - Removing sonata-project/exporter (1.3.4)
  - Installing sonata-project/exporter (1.4.0)
    Downloading: 100%

  - Removing sonata-project/admin-bundle (2.3.2)
  - Installing sonata-project/admin-bundle (2.3.3)
    Downloading: 100%

  - Removing doctrine/doctrine-bundle (v1.4.0)
  - Installing doctrine/doctrine-bundle (v1.5.0)
    Downloading: 100%

  - Removing guzzlehttp/ringphp (1.0.7)
  - Installing guzzlehttp/ringphp (1.1.0)
    Downloading: 100%

  - Removing guzzlehttp/guzzle (5.2.0)
  - Installing guzzlehttp/guzzle (5.3.0)
    Downloading: 100%

  - Removing fabpot/goutte (v2.0.3)
  - Installing fabpot/goutte (v2.0.4)
    Downloading: 100%

  - Removing sebastian/version (1.0.4)
  - Installing sebastian/version (1.0.6)
    Downloading: 100%

  - Removing sebastian/environment (1.2.1)
  - Installing sebastian/environment (1.2.2)
    Downloading: 100%

  - Removing phpunit/php-text-template (1.2.0)
  - Installing phpunit/php-text-template (1.2.1)
    Downloading: 100%

  - Removing phpunit/php-token-stream (1.4.0)
  - Installing phpunit/php-token-stream (1.4.3)
    Downloading: 100%

  - Removing phpunit/php-code-coverage (2.0.15)
  - Installing phpunit/php-code-coverage (2.1.7)
    Downloading: 100%

  - Removing phpunit/php-timer (1.0.5)
  - Installing phpunit/php-timer (1.0.6)
    Downloading: 100%

  - Removing phpunit/phpunit-mock-objects (2.3.1)
  - Installing phpunit/phpunit-mock-objects (2.3.4)
    Downloading: 100%

  - Removing sebastian/diff (1.2.0)
  - Installing sebastian/diff (1.3.0)
    Downloading: 100%

  - Removing instaclick/php-webdriver (1.4.1)
  - Installing instaclick/php-webdriver (1.4.2)
    Downloading: 100%

  - Removing swiftmailer/swiftmailer (v5.4.0)
  - Installing swiftmailer/swiftmailer (v5.4.1)
    Downloading: 100%

  - Removing monolog/monolog (1.13.1)
  - Installing monolog/monolog (1.14.0)
    Downloading: 100%

  - Removing friendsofsymfony/rest-bundle (1.5.3)
  - Installing friendsofsymfony/rest-bundle (1.7.1)
    Downloading: 100%

  - Removing nelmio/api-doc-bundle (2.8.0)
  - Installing nelmio/api-doc-bundle (2.9.0)
    Downloading: 100%

  - Removing kriswallsmith/buzz (v0.13)
  - Installing kriswallsmith/buzz (v0.15)
    Downloading: 100%

  - Removing robloach/component-installer (0.0.12)
  - Installing robloach/component-installer (0.2.1)
    Downloading: 100%

  - Updating behat/mink-extension dev-master (9bff0ae => c7fb932)
    Checking out c7fb932533292567aa57bfbe4ec40f1490ae6d58

  - Updating behat/mink-goutte-driver dev-master (63a593c => cc5ce11)
    Checking out cc5ce119b5a8e06662f634b35967aff0b0c7dfdd

  - Updating a2lix/translation-form-bundle dev-master (a9d96ce => c19cc48)
    Checking out c19cc48fd2b09c48f48ac191ea399624b01db6e2

  - Updating lexik/currency-bundle dev-master (816c8c4 => 144b583)
    Checking out 144b583d2186c09eff89271959a2457ddbb023f5

  - Updating willdurand/geocoder-bundle dev-master (5aab66a => 5b93692)
    Checking out 5b93692795cecf9d38a68afdeeec5fa6cbcd1950

  - Updating liip/imagine-bundle dev-master (e58ba83 => 01fca44)
    Checking out 01fca44e61201c9feb7c4ace913ee6c8751dc37e

  - Updating doctrine/mongodb-odm dev-master (55443f6 => b1089b7)
    Checking out b1089b723df8ae2230694a3899941e05d560c41f

  - Updating doctrine/mongodb-odm-bundle dev-master (1ac417f => 9e98fd9)
    Checking out 9e98fd9def517c68c8b8db43333545faef9a94b6

  - Updating knplabs/doctrine-behaviors dev-master (7b61dfa => 5739903)
    Checking out 5739903cd05dbe1a77e364e20fbef1d9eb16b3e6

  - Updating hwi/oauth-bundle dev-master (a9f88f3 => d7caff8)
    Checking out d7caff8257d7b5807f2f56d03d7bddca6484265b

**Comment by Soullivaneuh** [comment] 2015-07-03 11:09
Ok. Closing this one as un-reproducable for the moment.

Feel free to reopen it if you get again this error.

**Comment by kroshp** [comment] 2015-07-03 11:09
Ok thanks.

**Closed by Soullivaneuh** 2015-07-03 11:09 UTC

**Comment by kroshp** [comment] 2015-07-03 21:42
I ve got again the error:

Here are the trace:

> php composer.phar install --prefer-dist -vvv:
------------------------------------
....
  - Installing sonata-project/admin-bundle (2.3.3)
Downloading https://api.github.com/repos/sonata-project/SonataAdminBundle/zipball/03db550ece14b3bf1dddf700f7e0570aaef9c6fe
    Downloading: 100%
Writing C:/Users/kroshp/AppData/Local/Composer/files/sonata-project/admin-bundle/03db550ece14b3bf1dddf700f7e0570aaef9c6fe.zip into cache
    Extracting archive

  - Installing sonata-project/admin-bundle (2.3.3)
Downloading https://api.github.com/repos/sonata-project/SonataAdminBundle/zipball/03db550ece14b3bf1dddf700f7e0570aaef9c6fe
    Downloading: 100%
Writing C:/Users/kroshp/AppData/Local/Composer/files/sonata-project/admin-bundle/03db550ece14b3bf1dddf700f7e0570aaef9c6fe.zip into cache
    Extracting archive

 [ErrorException]
 ZipArchive::extractTo(D:\Documents\Projets\sources\Symfony/vendor/composer/f702efc3/sonata-project-SonataAdminBundle-03db550\Resources\public\vendor\x-editable\dist\jquery-editable\jquery-ui-datepicker\css\redmond\images/ui-bg_flat_0_aaaaaa_40x100.png): failed to open stream: Invalid argument
------------------------------------


Exception trace:
 () at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Downloader/ZipDownloader.php:79
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 ZipArchive->extractTo() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Downloader/ZipDownloader.php:79
 Composer\Downloader\ZipDownloader->extract() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Downloader/ArchiveDownloader.php:44
 Composer\Downloader\ArchiveDownloader->download() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Downloader/DownloadManager.php:201
 Composer\Downloader\DownloadManager->download() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Installer/LibraryInstaller.php:156
 Composer\Installer\LibraryInstaller->installCode() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Installer/LibraryInstaller.php:87
 Composer\Installer\LibraryInstaller->install() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Installer/InstallationManager.php:152
 Composer\Installer\InstallationManager->install() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Installer.php:580
 Composer\Installer->doInstall() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Installer.php:230
 Composer\Installer->run() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Command/InstallCommand.php:131
 Composer\Command\InstallCommand->execute() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar://D:/Documents/Projets/sources/Symfony/composer.phar/bin/composer:43
 require() at D:\MesDocuments\MesProjets\cocorico-come-and-drive\sources\Symfony\composer.phar:25

**Comment by Soullivaneuh** [comment] 2015-07-03 23:10
Not sure if it's a composer or a sonata issue but your path is weird. You have both `/` and `\` on it.

cc @rande: Did you already see this kind of error?

**Comment by edouardtiret** [comment] 2015-10-28 13:33
@Soullivaneuh no... XD

**Comment by Okimbellum** [comment] 2016-11-22 19:01
I have same problem. I tried different versions (`^3.9`  `^3.8`  `3.x-dev`) different keys (`--prefer-source`  `--prefer-dist`  `--prefer-stable`) and all their combinations. Tried to install it in new project. Nothing helps.  Does not matter `install` or `require`. I get same result any time.
Composer cannot to open file `vendor/composer/841ba6bd/sonata-project-SonataAdminBundle-7008fa8\Resources\public\vendor\x-editable\dist\jquery-editable\jquery-ui-datepicker\css\redmond\images/ui-bg_flat_0_aaaaaa_40x100.png`
I cannot use bundle because some image not found. It is image only and it is sad. 
Is it possible to ignore missed images during installation?

P.S. My environment
- Apache 2.4.7
- PHP 5.5.6 (cli)
- Mysql 5.6.15
- Composer 1.3-dev
- Windows 10 Pro x64
- Git 2.9.2.windows

P.P.S.
Error log:
`composer require sonata-project/admin-bundle --prefer-source -vvv`

```
    Now trying to download from dist
  - Installing sonata-project/admin-bundle (3.x-dev 7008fa8)
Downloading https://api.github.com/repos/sonata-project/SonataAdminBundle/zipball/7008fa8ad3e3eb7ef09cb59d24facd025e43c619
    Downloading: Connecting...Following redirect (2) https://codeload.github.com/sonata-project/SonataAdminBundle/legacy.zip/7008fa8ad3e3eb7ef09cb59d24facd025e43c619
Downloading https://codeload.github.com/sonata-project/SonataAdminBundle/legacy.zip/7008fa8ad3e3eb7ef09cb59d24facd025e43c619
    Downloading: 100%
Writing C:/Users/mbaran/AppData/Local/Composer/files/sonata-project/admin-bundle/63c9eb0a8a08ee4ded3722c785dc48209b6f4040.zip into cache from C:\openserver\OpenServer\domains\intellias.ua.dev28\trunk\intellias\vendor/sonata-project/admin-bundle/de64d893dc70652e10695c9cf00da8bf
    Extracting archive

Installation failed, reverting ./composer.json to its original content.


  [ErrorException]
  ZipArchive::extractTo(C:\intellias28/vendor/composer/841ba6bd/sonata-project-SonataAdminBundle-7008fa8\Resources\public\vendor\x-editable\dist\jquery-editable\jquery-ui-datepicker\css\redmond\images/ui-bg_flat_0_aaaaaa_40x100.png): failed to open stream: No such file or directory

Exception trace:
 () at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Downloader/ZipDownloader.php:99
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 ZipArchive->extractTo() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Downloader/ZipDownloader.php:99
 Composer\Downloader\ZipDownloader->extract() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Downloader/ArchiveDownloader.php:43
 Composer\Downloader\ArchiveDownloader->download() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Downloader/ZipDownloader.php:65
 Composer\Downloader\ZipDownloader->download() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Downloader/DownloadManager.php:213
 Composer\Downloader\DownloadManager->download() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Installer/LibraryInstaller.php:186
 Composer\Installer\LibraryInstaller->installCode() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Installer/LibraryInstaller.php:90
 Composer\Installer\LibraryInstaller->install() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Installer/InstallationManager.php:173
 Composer\Installer\InstallationManager->install() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Installer.php:542
 Composer\Installer->doInstall() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Installer.php:216
 Composer\Installer->run() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Command/RequireCommand.php:177
 Composer\Command\RequireCommand->execute() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/vendor/symfony/console/Application.php:847
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Console/Application.php:227
 Composer\Console\Application->doRun() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar://C:/openserver/OpenServer/modules/php/PHP-5.5.6/composer.phar/bin/composer:52
 require() at C:\openserver\OpenServer\modules\php\PHP-5.5.6\composer.phar:25
```

**Comment by greg0ire** [comment] 2016-11-22 20:09
I think I have already seen this bug, it has to do with the length of the path,which is too long on Windows, sadly. Have a look at the composer issues.

**Comment by greg0ire** [comment] 2016-11-22 20:10
I think you could work around it by forcing composer to use the source instead of the dist

**Comment by Okimbellum** [comment] 2016-11-23 10:23
@greg0ire Do you mean "ZipArchive::extractTo() Full extraction path exceed MAXPATHLEN (260)"? It was my previos problem. I fixed it using mklink /j in cmd. But this error seems something else.

**Comment by greg0ire** [comment] 2016-11-23 10:32
```php
php -a
Interactive mode enabled

php > var_dump(strlen('C:\intellias28/vendor/composer/841ba6bd/sonata-project-SonataAdminBundle-7008fa8\Resources\public\vendor\x-editable\dist\jquery-editable\jquery-ui-datepicker\css\redmond\images/ui-bg_flat_0_aaaaaa_40x100.png'));
int(207)
```

You're right it's "only" 207 chars. But I think this really is an issue you should report to Composer (or even to whoever wrote ZipArchive).

**Comment by Okimbellum** [comment] 2016-11-23 10:34
ok. 
Thanks.

**Comment by dechadou** [comment] 2017-10-10 16:15
Im having the exact same problem on windows

`PS C:\work\aeg-live--bowery-ecosystem-rfp\source\backend> composer install --prefer-source
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "C:\ProgramData\ComposerSetup\bin\composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing sonata-project/admin-bundle (3.20.1)
    Cloning 10c27f6ee911c452ee67059bfdc1a1fca8953904
    10c27f6ee911c452ee67059bfdc1a1fca8953904 is gone (history was rewritten?)
    Failed to download sonata-project/admin-bundle from source: Failed to execute git checkout "10c27f6ee911c452ee67059bfdc1a1fca8953904" -- && git reset --hard "10c27f6ee911c452ee67059bfdc1a1fca8953904" --

HEAD is now at 10c27f6... 3.20.1
error: unable to create file Resources/public/vendor/x-editable/dist/jquery-editable/jquery-ui-datepicker/css/redmond/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png (No such file or directory)
error: unable to create file Resources/public/vendor/x-editable/dist/jquery-editable/jquery-ui-datepicker/css/redmond/images/ui-bg_inset-hard_100_f5f8f9_1x100.png (No such file or directory)
error: unable to create file Resources/public/vendor/x-editable/dist/jquery-editable/jquery-ui-datepicker/css/redmond/images/ui-bg_inset-hard_100_fcfdfd_1x100.png (No such file or directory)
fatal: Could not reset index file to revision '10c27f6ee911c452ee67059bfdc1a1fca8953904'.

    Now trying to download from dist
  - Installing sonata-project/admin-bundle (3.20.1)
    Downloading: 100%


  [ErrorException]
  ZipArchive::extractTo(C:\work\aeg-live--bowery-ecosystem-rfp\source\backend/vendor/composer/c2c7374a/sonata-project-SonataAdminBundle-10c27f6\Resources\public\vendor\jqueryui\
  themes\base\minified\images/ui-bg_highlight-soft_75_cccccc_1x100.png): failed to open stream: No such file or directory`

**Comment by greg0ire** [comment] 2017-10-10 16:18
That not the same issue at all. Update composer and try again.

**Comment by dechadou** [comment] 2017-10-10 16:21
It is the same ZipArchive error:

`PS C:\work\aeg-live--bowery-ecosystem-rfp\source\backend> composer self-update
Updating to version 1.5.2.
    Downloading: 100%
Use composer self-update --rollback to return to version 40c14709f79f9d7ea35ac969cfbd7f41beb525bb
PS C:\work\aeg-live--bowery-ecosystem-rfp\source\backend> composer install --prefer-source
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 66 installs, 0 updates, 0 removals
  - Installing sonata-project/admin-bundle (3.20.1): Cloning 10c27f6ee9
    10c27f6ee911c452ee67059bfdc1a1fca8953904 is gone (history was rewritten?)
    Failed to download sonata-project/admin-bundle from source: Failed to execute git checkout "10c27f6ee911c452ee67059bfdc1a1fca8953904" -- && git reset --hard "10c27f6ee911c452ee67059bfdc1a1fca8953904" --

HEAD is now at 10c27f6... 3.20.1
error: unable to create file Resources/public/vendor/x-editable/dist/jquery-editable/jquery-ui-datepicker/css/redmond/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png (No such file or directory)
error: unable to create file Resources/public/vendor/x-editable/dist/jquery-editable/jquery-ui-datepicker/css/redmond/images/ui-bg_inset-hard_100_f5f8f9_1x100.png (No such file or directory)
error: unable to create file Resources/public/vendor/x-editable/dist/jquery-editable/jquery-ui-datepicker/css/redmond/images/ui-bg_inset-hard_100_fcfdfd_1x100.png (No such file or directory)
fatal: Could not reset index file to revision '10c27f6ee911c452ee67059bfdc1a1fca8953904'.

    Now trying to download from dist
  - Installing sonata-project/admin-bundle (3.20.1): Downloading (100%)
    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems): ZipArchive::extractTo(C:\work\aeg-live--bowery-ecosystem-rfp\source\backend/vendor/composer/a3e9f877/sonata-project-SonataAdminBundle-10c27f6\Resources\public\vendor\jqueryui\themes\base\minified\images/ui-bg_highlight-soft_75_cccccc_1x100.png): failed to open stream: No such file or directory`

**Comment by greg0ire** [comment] 2017-10-10 16:24
This is different:

> history was rewritten?

And this is different

> The archive may contain identical file names with different capitalization

So now, not the same error message. It's the same function call, but it fails for a different reason =>  different bug.

**Comment by greg0ire** [comment] 2017-10-10 16:25
Also, please try the latest Sonata version.
