### ISSUE TITLE
Add possibility create custom list fields types that linked to templates and which checks options

### ISSUE THREAD

**Issue by Koc** [sonata-project/SonataAdminBundle#3503] opened 2015-12-22 13:59 UTC
There are a lot of list field types available in the `AbstractSonataAdminExtension` https://github.com/sonata-project/SonataAdminBundle/blob/master/DependencyInjection/AbstractSonataAdminExtension.php#L33 . But currently it is too hard add your own type, like `image`. Also would be nice provde some kind of validation: for example my own `image` type require pass option `image_pattern`.

**Comment by core23** [comment] 2016-08-13 06:27
Feel free to contribute and supply a PR for this.

**Comment by jordisala1991** [comment] 2018-04-10 22:15
https://sonata-project.org/bundles/doctrine-orm-admin/3-x/doc/reference/templates.html

There is an “easy” way to customize this. Why is on the persistence bundle? Good question.
Closing for now. As the issue is not there (even if we could do better).

Please provide an RFC of you think we can do it better on this matter, explaining how this could be achieved.

**Closed by jordisala1991** 2018-04-10 22:15 UTC
Labels: feature
