### ISSUE TITLE
Checkbox labels NOT showing with Bootstrap SF2.6 form theme

### ISSUE THREAD

**Issue by davidromani** [sonata-project/SonataAdminBundle#2630] opened 2014-12-18 15:31 UTC
Hello.

I enable this config with SF2.6 and Sonata Admin 2.3, then checkbox labels are not showing in forms.

```yaml
# app/config.yml
twig:
    form:
        resources:
            - "bootstrap_3_layout.html.twig"
```

**Comment by Axinet** [comment] 2015-01-01 22:12
I encountered the same problem today. 

It looks like the problem is 2-step:
1) block "checkbox_row" from "bootstrap_3_layout.html.twig" takes precedence over block "form_row" from "form_admin_fields.html.twig"
2) block "checkbox_label" from "bootstrap_3_layout.html.twig" takes precedence over block "form_label" from "form_admin_fields.html.twig"

To solve this problem I used additional/custom templates for sonata admin forms by adding to config:
````yml
sonata_doctrine_orm_admin:
    templates:
        form:
            - AppBundle:Admin:my_form_admin_fields.html.twig
````

and overridden problematic templates (appeding them to "form_admin_fields.html.twig" from sonata admin bundle whould be a possible work around for this problem, but maybe there are some better ones?)

````yml
{% extends 'SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig' %}

{% block checkbox_row -%}
    {{ block('form_row') }}
{%- endblock checkbox_row %}

{% block checkbox_label %}
    {{ block('form_label') }}
{% endblock checkbox_label %}
````

**Comment by davidromani** [comment] 2015-01-02 09:56
@Axinet it works :+1: thx

**Comment by CyrilleGuimezanes** [comment] 2015-01-15 13:23
Work for me too but the label is not on the checkbox line anymore

**Comment by kwn** [comment] 2015-02-25 17:25
Be careful. @Axinet workaround doesn't show error messages (if errors exist in checkbox field).

**Comment by ConneXNL** [comment] 2015-03-24 12:48
Also came accros this problem. For now I added 
{% form_theme form 'bootstrap_3_layout.html.twig' %}

in all my normal forms.

Is this supposed to be fixed in future versions though?

**Comment by metamaker** [comment] 2015-05-10 10:29
It works for me too. Any chance for a fix in the next release?

**Comment by webdevilopers** [comment] 2015-07-02 11:25
:+1:

**Comment by iBasit** [comment] 2016-02-16 09:21
+1

**Closed** 2016-03-08 12:59 UTC

**Comment by davidromani** [comment] 2016-03-10 10:23
Hello again, after update to this commit I think that this is **not** a good solution because we have 2 different scenes. We must consider when the form is embedded or not.

With @Axinet workaround you obtain this form templates (right for me):
<img width="963" alt="captura de pantalla 2016-03-10 a les 11 18 34" src="https://cloud.githubusercontent.com/assets/698779/13666542/512849bc-e6b2-11e5-9a82-e4e2cc9596b8.png">

But now I've got this forms, so I think that it's quite awful:
<img width="906" alt="captura de pantalla 2016-03-10 a les 11 12 22" src="https://cloud.githubusercontent.com/assets/698779/13666553/5a24c5d6-e6b2-11e5-9596-a7e856974886.png">

**Comment by davidromani** [comment] 2016-03-11 07:16
Hi @OskarStark, did you check my last msg?

**Comment by OskarStark** [comment] 2016-03-15 10:19
@davidromani i think we can, but imo the first step is done now and the label looks nicer

in case of the collections/embedded we need to add another fix.
@vincenttouzet can you check this please?

**Comment by vincenttouzet** [comment] 2016-03-19 19:58
I've created a new pull request to fix these bugs : https://github.com/sonata-project/SonataAdminBundle/pull/3672
