### ISSUE TITLE
Use reverse formatting for filters

### ISSUE THREAD

**Issue by Koc** [sonata-project/SonataAdminBundle#2157] opened 2014-05-22 08:31 UTC
Use case and steps to reproducing:
1. install SonataAdmin with SonataIntl
2. create admin class with id
3. id field using number formatting (detected automatically): `2047553` -> `2 047 553`
4. but filter by id doesn't works properly with formatted numbers. I should remove spaces by hand.

**Comment by core23** [comment] 2016-04-15 17:05
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @Koc

**Comment by jordisala1991** [comment] 2018-03-28 20:06
This issue is to old, without an answer after 2 years. Also it looks like this is an issue for SonataIntl instead.

Closing for now, if this issue is still relevant, please ping me to reopen and provide more information, or open a new issue on the SonataIntlBundle.

It would be nice to check this against latest versions of all SonataBundles.

**Closed by jordisala1991** 2018-03-28 20:06 UTC
