### ISSUE TITLE
Cannot select row on ajax list_select with only LIST role

### ISSUE THREAD

**Issue by kamilwalas** [sonata-project/SonataAdminBundle#2935] opened 2015-04-21 13:50 UTC
Two entities A and B linked with relation ManyToOne. User with roles to admin A and only list B cannot link A to B, because there is no way to click link for selected entity in popup after clicking button LIST.

In file SonataAdminBundle:CRUD:list__select.html.twig href for button 'Select' is generated in line 15 with code

```
    <a class="btn btn-default" href="#">
        <i class="glyphicon glyphicon-arrow-right"></i>
        {{ 'list_select'|trans({}, 'SonataAdminBundle') }}
    </a>
```

but in  SonataDoctrineORMAdminBundle/Resources/views/CRUD/edit_orm_many_association_script.html.twig in line 39 there is condition which excludes this link

```
// return if the link is an anchor inside the same page
if (this.nodeName == 'A' && (target.attr('href').length == 0 || target.attr('href')[0] == '#')) {
    Admin.log('[{{ id }}|field_dialog_form_list_link] element is an anchor, skipping action', this);
    return;
}
```

The result is that with popup window user can select entity with link generated by addIdentifier in admin class. But when user has only permission to list entities then there is no link only button generated by SonataAdminBundle:CRUD:list__select.html.twig which doesn't work.

**Comment by jeremy-bruns** [comment] 2015-05-11 12:58
+1

**Comment by core23** [comment] 2016-08-13 06:01
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by jordisala1991** [comment] 2018-03-24 16:54
Fixed in: https://github.com/sonata-project/SonataAdminBundle/pull/3887

Closing.

**Closed by jordisala1991** 2018-03-24 16:54 UTC
Labels: pending author
