### ISSUE TITLE
Date picker rendering odd if used in a fieldset

### ISSUE THREAD

**Issue by symball** [sonata-project/SonataAdminBundle#4453] opened 2017-04-16 13:10 UTC
#### Sonata packages

```sonata-project/admin-bundle                  3.16.0 The missing Symfony Admin Generator
sonata-project/block-bundle                  3.3.2  Symfony SonataBlockBundle
sonata-project/cache                         1.0.7  Cache library
sonata-project/core-bundle                   3.3.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle               2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-mongodb-admin-bundle 3.0.0  Symfony Sonata / Integrate Doctrine MongoDB ODM into the SonataAdminBundle
sonata-project/easy-extends-bundle           2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                      1.7.1  Lightweight Exporter library
```

#### Symfony packages

```symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/css-selector       v3.2.7  Symfony CssSelector Component
symfony/filesystem         v3.2.7  Symfony Filesystem Component
symfony/finder             v3.2.7  Symfony Finder Component
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v3.2.7  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.4  Symfony SwiftmailerBundle
symfony/symfony            v2.8.19 The Symfony PHP framework
```

#### PHP version

```
PHP 5.6.30 (cli) (built: Jan 20 2017 01:36:35)
```

## Subject

The date picker is not rendering properly if it is used within a fieldset definition; if I put it at the base level things work so it's not a case of improper setup.

screenshot 1
![spectacle j16319](https://cloud.githubusercontent.com/assets/10624537/25071381/fecff17e-22e7-11e7-8691-366570c46ead.png)

## Steps to reproduce
Create an admin with the following definition
```php
$formMapper
->with('First Column', array('class' => 'col-md-6')
   ->add('test column', 'text', array('mapped' => false))
->end()
->with('Second Column', array('class' => 'col-md-6')
   ->add('createdAt', 'sonata_type_datetime_picker', array('mapped' => false))
->end()
```

## Expected results

The datetime picker to render as it would in the following screenshot

![spectacle b16319](https://cloud.githubusercontent.com/assets/10624537/25071411/b931d168-22e8-11e7-8661-ae09e14f9c76.png)

## Actual results

The date time picker is being rendered as a series of select2 dropdowns instead of the the date picker

**Comment by symball** [comment] 2017-04-16 13:16
Further investigation of the issue has shown me that the render issue only occurs if I have set a custom format. I.E. If no other options are set, then it works.

**Comment by jordisala1991** [comment] 2018-03-28 19:51
Closing this, as the issue is not related to rendering a date picker inside a fieldset, but with the format.

Probably related to a malformed format or with invalid characters. Note that this format is different from the date format in PHP (in some cases, I don't know exactly which ones, but you should use the datetime picker format)

Take a look at this: http://eonasdan.github.io/bootstrap-datetimepicker/#custom-formats

If you still have this issue, please reopen it on CoreBundle since the datetimepicker is there.

**Closed by jordisala1991** 2018-03-28 19:51 UTC
