### ISSUE TITLE
List view combined value

### ISSUE THREAD

**Issue by gimler** [sonata-project/SonataAdminBundle#5055] opened 2018-04-04 18:25 UTC
I have two fields `firstname` and `lastname` and i will display it in one column `firstname, lastname`.

it works with
entity
```
    public function getName()
    {
        return sprintf('%s, %s ', $this->firstname, $this->lastname);
    }
``` 
admin
```
      $listMapper
            ->add('name', 'string', array('label' => 'Name', 'sortable' => 'firstname'))
```
the problem is that i will sort by firstname and lastname

so i try to override the query
```
    public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);
        $query->addSelect($query->getRootAliases()[0] . '.firstname AS name');

        return $query;
    }
```

but then i get the error.

## Expected results

```
sortable list column with values
```

## Actual results
```
An exception has been thrown during the rendering of a template ("Warning: Illegal offset type in isset or empty").
```

**Comment by jordisala1991** [comment] 2018-04-06 05:47
Duplicate of: https://github.com/sonata-project/SonataAdminBundle/issues/1077

Closing.

**Closed by jordisala1991** 2018-04-06 05:47 UTC
