### ISSUE TITLE
Unable to use sonata_type_model_autocomplete

### ISSUE THREAD

**Issue by JumpIfBelow** [sonata-project/SonataAdminBundle#4503] opened 2017-06-01 08:44 UTC
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.18.2 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.4  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.0  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2  Symfony SwiftmailerBundle
symfony/symfony            v3.3.0  The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.19 (cli) (built: May  9 2017 16:02:11) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

## Subject
While trying to use the `sonata_type_model_autocomplete`, the related AJAX query failed.
To be clear: the form is well generated, the listener, the route, everything works as intended.
When typing, the event is fired, so the AJAX request is send. But the obly thing I get is "Loading failed". If I use the toolbar to see what happened to the request, the HTTP status code is 500, and I have this exception: `Action "" could not be found in access mapping. Please make sure your action is defined into your admin class accessMapping property.`

I have seen some issues related to this and closed, like [this one](https://github.com/sonata-project/SonataAdminBundle/issues/4467) which is linked to [this one](https://github.com/sonata-project/SonataAdminBundle/pull/4469)

The given fix above is in my libraries, so it does not come to this. Actually, the fix was for filter, not for the second part create/edit. My bug appears on this second part.
I actually tried different version of `symfony` and `sonata-project` packages. None of them seems to work, from latest revision, some older, or even dev.
Moreover, I tried different configuration of the datagridMapper, but all leads me to the same error.

Of course all my entities are good, Doctrine does not see any issue. They works great with other parts, and everything works (*slowly*) if I just use the `entity` type instead of `sonata_type_model_autocomplete`.
## Steps to reproduce
I have this form mapper:
```php
$formMapper
// ...

                ->add(
                    'rent',
                    'sonata_type_model_autocomplete',
                    [
                        'minimum_input_length' => 1,
                        'property' => ['id'],
                        'to_string_callback' => function(Rent $_rent, $_property) {
                            return 'Réservation n°' . $_rent->getId();
                        },
                    ]
                )
// ...
;
```

So I have to enable to search on "id" property on the rent part. Which is the case:
```php
$datagridMapper
            ->add('id')
// ...
;
```
## Expected results
The route should return a valid JSON, that Select2 can use.

## Actual results
An HTTP 500 error, with the given trace:
```
InvalidArgumentException:
Action "" could not be found in access mapping. Please make sure your action is defined into your admin class accessMapping property.

  at vendor/sonata-project/admin-bundle/Admin/AbstractAdmin.php:2808
  at Sonata\AdminBundle\Admin\AbstractAdmin->checkAccess(null)
     (vendor/sonata-project/admin-bundle/Controller/HelperController.php:410)
  at Sonata\AdminBundle\Controller\HelperController->retrieveAutocompleteItemsAction(object(Request))
  at call_user_func_array(array(object(HelperController), 'retrieveAutocompleteItemsAction'), array(object(Request)))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:171)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:46)
```

**Comment by core23** [comment] 2017-06-01 14:43
Maybe this is related to https://github.com/sonata-project/SonataAdminBundle/pull/4448?

**Comment by JumpIfBelow** [comment] 2017-06-01 14:53
Thanks for your reply!
Unfortunately, it is not. It is one of the issue I find while searching for similar one (but cannot find it again while writing my own issue). I tried to add manually `'target_admin_access_action' => 'list'` on my code, but it leads me to the same issue.
I'm actually in super admin role, so I can actually see everything on the admin part.

It is a bit tricky to see what's wrong. Actually, I tried on another entity doing the same thing, and it works. I inifinity-checked my code but I don't know why it could crash like this on this issue. I tried to crash the working code, but haven't seen an error like that.

Cache is created with `bin/console cache:clear -e dev`, with no error of course.

**Comment by JumpIfBelow** [comment] 2017-06-02 07:58
I understand the issue here.
Still, I don't know how to classify this.

To be clear, my form has two states: creation and edition. To differenciate this, I use this line of code: `if($this->id($this->getSubject()))`. If the line returns true, we are in edition, otherwise it is creation.
The thing is: if the `sonata_type_model_autocomplete` is in both forms with different property type, it will crash.
For example, this code works:
```php
        if($this->id($this->getSubject())) {
            $formMapper
                ->add(
                    'rent',
                    'sonata_type_model_autocomplete',
                    [
                        'minimum_input_length' => 1,
                        'property' => ['id'],
                        'to_string_callback' => function(Rent $_rent, $_property) {
                            return 'Réservation n°' . $_rent->getId();
                        },
                    ]
                )
            ;
        } else {
        }
```
Setting the property rent in both forms works too (so outside of the test above), as this:
```php
        $formMapper
            ->add(
                'rent',
                'sonata_type_model_autocomplete',
                [
                    'minimum_input_length' => 1,
                    'property' => ['id'],
                    'to_string_callback' => function(Rent $_rent, $_property) {
                        return 'Réservation n°' . $_rent->getId();
                    },
                ]
            )
        ;

        if($this->id($this->getSubject())) {
        } else {
        }
```

The strange thing is, if I set the value differently in edition and creation, this leads me to the issue described above.

So this code will **crash**:
```php
        if($this->id($this->getSubject())) {
            $formMapper
                ->add(
                    'rent',
                    'sonata_type_model_autocomplete',
                    [
                        'minimum_input_length' => 1,
                        'property' => ['id'],
                        'to_string_callback' => function(Rent $_rent, $_property) {
                            return 'Réservation n°' . $_rent->getId();
                        },
                    ]
                )
            ;
        } else {
            $formMapper
                ->add('rent', 'sonata_type_model', ['property' => 'id'])
            ;
        }
```

I think there is an issue because if the first code works, this one should work too.

But it is not critical as this case is special and it was a mistake. I was migrating the code. No one should use different type for the same property on creation and edition.
I don't know if I'm clear enough on this issue, but I really think the bug is real, but not critical.

If you need more details to troubleshoot this, you can ask me more question about this.

**Comment by jordisala1991** [comment] 2018-04-05 21:24
This issue was about using different form types for edit and creation.

Given how this type works, it doesnt seem possible to do this ATM: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Controller/HelperController.php#L365

I will close this issue as I dont see a lot of interest of “fixing” this. IMO its not clear that this is a bug.

I think this issue could be rewriten because the problem is not well explained from the begining. Please feel free to open a new issue if you are still interested.

**Closed by jordisala1991** 2018-04-05 21:24 UTC

**Comment by simplegr** [comment] 2019-05-15 09:36
You can use something like this to avoid execution of `if($this->id($this->getSubject())) {` branch on autocomplete:

```
        $hasNotQueryParam = is_null($this->getRequest()->query->get('q'));

        if ($this->id($this->getSubject()) && $hasNotQueryParam) {
```
