### ISSUE TITLE
[DX] Automatically register required admin block

### ISSUE THREAD

**Issue by wouterj** [sonata-project/SonataAdminBundle#2340] opened 2014-08-23 08:11 UTC
It's nice that the bundle uses blocks for the admin, but it isn't a great experience to have to configure another bundle in order to make SonataAdminBundle working. It should work out of the box.

This means you have to find some automatic progress to do it. E.g. by using tags in the BlockBundle.

**Comment by core23** [comment] 2016-08-27 15:04
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by wouterj** [comment] 2016-08-28 09:40
still valid

**Comment by core23** [comment] 2016-08-28 11:18
Can you supply a PR for that @wouterj ?

**Comment by jordisala1991** [comment] 2018-03-17 18:55
This should probably be closed since sonata now works with flex by default. That means you can do: composer require `sonata-project/admin-bundle` and it will install and auto configure everything needed with flex.

Closing. If you think this issue is still valid, please ping me to reopen

**Closed by jordisala1991** 2018-03-17 18:55 UTC
