### ISSUE TITLE
Get $list property in Sonata\AdminBundle\Admin\AbstractAdmin

### ISSUE THREAD

**Issue by GGGGino** [sonata-project/SonataAdminBundle#4552] opened 2017-07-12 13:30 UTC
Hi, I want to override Sonata\AdminBundle\Admin\AbstractAdmin::buildList method but i can't because when i copy the method in the child class, it throws "Undefined property" $list.
In fact $list is a private property and the getList method call a buildList, crashing everything.

Is there another way to override, or there is a need to create a getter/change the visibility to the $list property?

Get the value with the ReflectionObject looks too much dirty
```php
$r = new ReflectionObject($adminObj);
$p = $r->getProperty('list');
$p->setAccessible(true);

var_dump($p->getValue($adminObj));
```

Here a piece of the AbstractAdmin class
```php
abstract class AbstractAdmin implements AdminInterface, DomainObjectInterface
{
    /**
     * The list collection.
     *
     * @var array
     */
    private $list;
   
    /**
     * {@inheritdoc}
     */
    public function getList()
    {
        $this->buildList();

        return $this->list;
    }

    /**
     * build the list FieldDescription array.
     */
    protected function buildList()
    {
        if ($this->list) {
            return;
        }

        $this->list = $this->getListBuilder()->getBaseList();

        $mapper = new ListMapper($this->getListBuilder(), $this->list, $this);

        if (count($this->getBatchActions()) > 0) {
            $fieldDescription = $this->getModelManager()->getNewFieldDescriptionInstance(
                $this->getClass(),
                'batch',
                array(
                    'label' => 'batch',
                    'code' => '_batch',
                    'sortable' => false,
                    'virtual_field' => true,
                )
            );

            $fieldDescription->setAdmin($this);
            $fieldDescription->setTemplate($this->getTemplate('batch'));

            $mapper->add($fieldDescription, 'batch');
        }

        $this->configureListFields($mapper);

        foreach ($this->getExtensions() as $extension) {
            $extension->configureListFields($mapper);
        }

        if ($this->hasRequest() && $this->getRequest()->isXmlHttpRequest()) {
            $fieldDescription = $this->getModelManager()->getNewFieldDescriptionInstance(
                $this->getClass(),
                'select',
                array(
                    'label' => false,
                    'code' => '_select',
                    'sortable' => false,
                    'virtual_field' => false,
                )
            );

            $fieldDescription->setAdmin($this);
            $fieldDescription->setTemplate($this->getTemplate('select'));

            $mapper->add($fieldDescription, 'select');
        }
    }
}
```

**Comment by OskarStark** [comment] 2017-07-12 13:33
Why do you want todo this?

**Comment by greg0ire** [comment] 2017-07-12 13:33
The API is closed on purpose, see http://fabien.potencier.org/pragmatism-over-theory-protected-vs-private.html

**Comment by jlamur** [comment] 2017-07-12 13:37
> Why do you want todo this?

I also needed to do this this because I wanted to change the `ListMapper` class. But I suppose there is a lot of other cases where this is needed.

I didn't found an other way than using Reflection.

**Comment by greg0ire** [comment] 2017-07-12 13:49
A solution with no reflection is to just copy the `$list` field and all methods that access it.

But the best thing would be to expose why you need to do it, and to contribute a custom extension point just for that. In your case @jlamur , that would be a `getListMapperClass()`, but that might not even the best solution, because we don't even know *why* you want to override this class in the first place.

**Comment by jlamur** [comment] 2017-07-12 13:56
@greg0ire It's not the point of this issue, but I needed to override it for nested tabs, nested groups, empty groups (`col-md-X` divs), etc..  that I implemented in my new `ListMapper`... So yes a `getListMapperClass()` method would have been great! 👍

**Comment by greg0ire** [comment] 2017-07-12 13:57
Ok, well... likewise, OP needs to explain what he is trying to achieve, because there might be another solution that could benefit to many other users.

**Comment by GGGGino** [comment] 2017-07-12 14:02
My need is to override the "ListMapper" in order to be able to show or not show columns depending the logged in user and the related entity(acl field access).
And I would like to check this in the ListMapper::add.

**Comment by jlamur** [comment] 2017-07-12 14:07
@GGGGino It should be doable by overriding the `ListBuilder` instead.

**Comment by greg0ire** [comment] 2017-07-12 14:07
Possible solution: introduce a private field `$listMapperClass` (let's avoid exposing yet another method if we don't need to), and add an optional argument to the abstract admin constructor. And of course use that field when creating the list mapper.

**Comment by greg0ire** [comment] 2017-07-12 14:09
Anyway, not a bug. Closing.

**Closed by greg0ire** 2017-07-12 14:09 UTC
