### ISSUE TITLE
Sonataadmin list field inline edit on empty fields

### ISSUE THREAD

**Issue by caramba1337** [sonata-project/SonataAdminBundle#2902] opened 2015-04-13 11:28 UTC
am playing around with SonataAdmin. I have a list of users in my backend and i want to make specific fields inline editable within the list.

`->add('email', 'string', array('editable' => true))`
Works well until there is an object without a value for email. So i am able to edit the email directly as long as the field email got a value. When it's empty i am not able to edit it from within the list.

**Comment by webdevilopers** [comment] 2015-04-21 07:24
Possible duplicate of https://github.com/sonata-project/SonataAdminBundle/issues/2881 @caramba1337 ?

**Comment by pulzarraider** [comment] 2015-05-06 23:35
Discussed in #2881. It should work in dev-master (upcoming 2.4). 
Thank you @caramba1337 for reporting the issue.

**Closed by pulzarraider** 2015-05-06 23:35 UTC
