### ISSUE TITLE
Add support for multiple themes

### ISSUE THREAD

**Issue by hason** [sonata-project/SonataAdminBundle#3210] opened 2015-08-31 12:59 UTC
I like an idea from Django framework https://www.djangopackages.com/grids/g/admin-styling. The first step would be a separation of AdminLTE theme to the new repository.

**Comment by pulzarraider** [comment] 2015-09-01 18:58
I agree. Sonata is now too much integrated with the default design (currently AdminLTE).
It would be great if the user could choose from multiple themes.

Closing because it's duplicate of #2066.

**Closed by pulzarraider** 2015-09-01 18:58 UTC
