### ISSUE TITLE
field with the name "children" in OneToMany "sonata_type_collection"

### ISSUE THREAD

**Issue by arffak** [sonata-project/SonataAdminBundle#2104] opened 2014-04-30 19:36 UTC
I have a class A that has a OneToMany relationship with Class B 
Class B has a field named "children" when you use "sonata_type_collection" with "edit" "inline" when you click on "add new" nothing appears! but if I change the name "children" with another name it works!

**Comment by webdevilopers** [comment] 2015-04-07 08:47
Duplicate of https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/34.

**Comment by arffak** [comment] 2015-04-07 08:51
@webdevilopers, No its not a duplicated issue, its different

**Comment by core23** [comment] 2016-08-13 05:35
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.

**Closed by core23** 2016-08-13 05:35 UTC
