### ISSUE TITLE
ClassNotFoundException: Attempted to load class "Formatter"

### ISSUE THREAD

**Issue by Luvelnet** [sonata-project/SonataAdminBundle#2194] opened 2014-06-18 10:54 UTC
Hi guys,

I'm trying create a new post (newsBundle) and throw this:

ClassNotFoundException: Attempted to load class "Formatter" from namespace "Symfony\Component\Validator\Constraints\Sonata\FormatterBundle\Validator\Constraints" in /xxxxx/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/AbstractLoader.php line 64. Do you need to "use" it from another namespace?

Could you help me?

Thanks

**Comment by core23** [comment] 2016-04-15 17:13
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @Luvelnet

**Comment by jordisala1991** [comment] 2018-01-31 06:49
This issue is not related to this bundle. Maybe related to NewsBundle but still very old to track and not a lot of info. Closing

**Closed by jordisala1991** 2018-01-31 06:49 UTC
