### ISSUE TITLE
Remove router deprecations

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5346] opened 2018-12-10 19:11 UTC
#### Sonata packages

```
sonata-project/admin-bundle              3.42.2             3.42.2             The missing Symfony Admin Generator
sonata-project/block-bundle              3.13.0             3.13.0             Symfony SonataBlockBundle
sonata-project/cache                     1.1.1              2.0.1              Cache library
sonata-project/cache-bundle              2.4.2              3.0.0              This bundle provides caching services
sonata-project/classification-bundle     3.7.1              3.7.1              Symfony SonataClassificationBundle
sonata-project/core-bundle               3.12.0             3.12.0             Symfony SonataCoreBundle
sonata-project/dashboard-bundle          dev-master 67752a4 dev-master 67752a4 Provides a Dashboard management through container and blo...
sonata-project/datagrid-bundle           2.4.0              2.4.0              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.2              1.1.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.3              3.6.3              Symfony Sonata / Integrate Doctrine ORM into the SonataAd...
sonata-project/easy-extends-bundle       2.5.0              2.5.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.9.1              1.9.1              Lightweight Exporter library
sonata-project/formatter-bundle          4.1.2              4.1.2              Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.5.0              2.5.0              Symfony SonataIntlBundle
sonata-project/media-bundle              3.16.3             3.16.3             Symfony SonataMediaBundle
sonata-project/news-bundle               3.7.0              3.7.0              Symfony SonataNewsBundle
sonata-project/notification-bundle       3.5.1              3.5.1              Symfony SonataNotificationBundle
sonata-project/page-bundle               3.9.1              3.9.1              This bundle provides a Site and Page management through c...
sonata-project/seo-bundle                2.6.2              2.6.2              Symfony SonataSeoBundle
sonata-project/timeline-bundle           3.3.1              3.3.1              Integrates SpyTimelineBundle into Sonata
sonata-project/user-bundle               4.2.3              4.2.3              Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/asset                 v4.2.1  v4.2.1  Symfony Asset Component
symfony/cache                 v4.2.1  v4.2.1  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                v4.2.1  v4.2.1  Symfony Config Component
symfony/console               v4.2.1  v4.2.1  Symfony Console Component
symfony/contracts             v1.0.2  v1.0.2  A set of abstractions extracted out of the Symfony components
symfony/css-selector          v4.2.1  v4.2.1  Symfony CssSelector Component
symfony/debug                 v4.2.1  v4.2.1  Symfony Debug Component
symfony/debug-bundle          v4.2.1  v4.2.1  Symfony DebugBundle
symfony/dependency-injection  v4.2.1  v4.2.1  Symfony DependencyInjection Component
symfony/doctrine-bridge       v4.2.1  v4.2.1  Symfony Doctrine Bridge
symfony/dom-crawler           v4.2.1  v4.2.1  Symfony DomCrawler Component
symfony/dotenv                v4.2.1  v4.2.1  Registers environment variables from a .env file
symfony/event-dispatcher      v4.2.1  v4.2.1  Symfony EventDispatcher Component
symfony/expression-language   v4.2.1  v4.2.1  Symfony ExpressionLanguage Component
symfony/filesystem            v4.2.1  v4.2.1  Symfony Filesystem Component
symfony/finder                v4.2.1  v4.2.1  Symfony Finder Component
symfony/flex                  v1.1.8  v1.1.8  Composer plugin for Symfony
symfony/form                  v4.2.1  v4.2.1  Symfony Form Component
symfony/framework-bundle      v4.2.1  v4.2.1  Symfony FrameworkBundle
symfony/http-foundation       v4.2.1  v4.2.1  Symfony HttpFoundation Component
symfony/http-kernel           v4.2.1  v4.2.1  Symfony HttpKernel Component
symfony/inflector             v4.2.1  v4.2.1  Symfony Inflector Component
symfony/intl                  v4.2.1  v4.2.1  A PHP replacement layer for the C intl extension that includes additional data from the IC...
symfony/maker-bundle          v1.9.0  v1.9.0  Symfony Maker helps you create empty commands, controllers, form classes, tests and more s...
symfony/monolog-bridge        v4.2.1  v4.2.1  Symfony Monolog Bridge
symfony/monolog-bundle        v3.3.1  v3.3.1  Symfony MonologBundle
symfony/options-resolver      v4.2.1  v4.2.1  Symfony OptionsResolver Component
symfony/polyfill-ctype        v1.10.0 v1.10.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu     v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring     v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72        v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process               v4.2.1  v4.2.1  Symfony Process Component
symfony/property-access       v4.2.1  v4.2.1  Symfony PropertyAccess Component
symfony/routing               v4.2.1  v4.2.1  Symfony Routing Component
symfony/security              v4.2.1  v4.2.1  Symfony Security Component
symfony/security-acl          v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle       v4.2.1  v4.2.1  Symfony SecurityBundle
symfony/stopwatch             v4.2.1  v4.2.1  Symfony Stopwatch Component
symfony/swiftmailer-bundle    v3.2.4  v3.2.4  Symfony SwiftmailerBundle
symfony/templating            v4.2.1  v4.2.1  Symfony Templating Component
symfony/translation           v4.2.1  v4.2.1  Symfony Translation Component
symfony/twig-bridge           v4.2.1  v4.2.1  Symfony Twig Bridge
symfony/twig-bundle           v4.2.1  v4.2.1  Symfony TwigBundle
symfony/validator             v4.2.1  v4.2.1  Symfony Validator Component
symfony/var-dumper            v4.2.1  v4.2.1  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter          v4.2.1  v4.2.1  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP...
symfony/web-profiler-bundle   v4.2.1  v4.2.1  Symfony WebProfilerBundle
symfony/webpack-encore-bundle v1.0.0  v1.0.0  Integration with your Symfony app & Webpack Encore!
symfony/yaml                  v4.2.1  v4.2.1  Symfony Yaml Component
```

#### PHP version

```
PHP 7.2.12 (cli) (built: Nov 16 2018 03:34:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.12, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
```

## Subject

Symfony deprecated the controller defintion with colons.

## Steps to reproduce

Just use this bundle.

## Expected results

No deprecation warnings

## Actual results

```
Referencing controllers with SonataAdminBundle:CRUD:list is deprecated since Symfony 4.1, use "Sonata\AdminBundle\Controller\CRUDController::listAction" instead.
```

**Comment by phansys** [comment] 2019-06-17 19:09
@core23, is this issue still valid?

**Comment by phansys** [comment] 2019-06-17 19:21
Duplicate of #5227.
#5228 should have this issue fixed.

**Closed** 2019-06-17 21:57 UTC
Labels: Easy Pick, pending author
