### ISSUE TITLE
Sonata_type_collection add button problem

### ISSUE THREAD

**Issue by rrabillo** [sonata-project/SonataAdminBundle#3225] opened 2015-09-07 10:16 UTC
Hello.

I have a problem with the sonata_type_collection field. 

It actually works well, i can add row, delete, and persist the entities. 

But the nested entities actually have input=file field. So when i add a new row without persisting/updating entity, this input is cleared. It seems that Sonata reload the whole form. Is there any way to prevent this behavior ? Thanks in advance.

```
protected function configureFormFields(FormMapper $formMapper)
{

    $formMapper
        ->add('title')
        ->add('axe')
        ->add('username')
        ->add('password','repeated', array('type' => 'text','options' => array('translation_domain' => 'FOSUserBundle'),
            'first_options' => array('label' => 'form.password'),
            'second_options' => array('label' => 'form.password_confirmation'),
            'invalid_message' => 'fos_user.password.mismatch'))
        ->add('imgs', 'sonata_type_collection',  array(
            'by_reference' => false
        ), array(
            'edit' => 'inline',
            'allow_delete' => true
        )) 
    ;
}

```

**Comment by rrabillo** [comment] 2015-09-08 10:52
I finally found a workaround. 

I used Symfony2 form.

Here is my solution: http://stackoverflow.com/a/32455824/4601512

**Comment by pulzarraider** [comment] 2015-09-19 06:06
Duplicate of #1628

**Closed** 2015-09-19 06:07 UTC
