### ISSUE TITLE
unique constraint with editable => true

### ISSUE THREAD

**Issue by metaer** [sonata-project/SonataAdminBundle#3717] opened 2016-04-12 11:24 UTC
When I try to set unique field value to another entity in form, it works ok:
screenshot http://dl2.joxi.net/drive/2016/04/12/0004/2633/289353/53/56376a55c2.jpg

But when I try to edit value in field list, it throws exception and I get 500 error:

> Uncaught PHP Exception Sonata\AdminBundle\Exception\ModelManagerException: "Failed to update object: Evaluation\CabinetBundle\Entity\RealExpert" at /home/user/PhpstormProjects/myProject/vendor/sonata-project/doctrine-orm-admin-bundle/Model/ModelManager.php line 158
> 
> "previous": {
>         "class": "Doctrine\DBAL\DBALException",
>         "message": "An exception occurred while executing 'UPDATE RealExpert SET login = ? WHERE id = ?' with params [\"jjj\", 2]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'jjj' for key 'UNIQ_E1BD4B8BAA08CB10'",

edit in list screenshot: http://joxi.ru/krDpRMOu0o0k7r.jpg

other validations (length for example) work good with editable => true and in form edit

my validation.yml:

``` yaml
Evaluation\CabinetBundle\Entity\RealExpert:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: login
            message: 'Такой логин р. эксперта уже заведен'
    properties:
        login:
            - Length:
                min: 1
                max: 100
                minMessage: Логин эксперта должен содержать от 1 до 100 символов
                maxMessage: Логин эксперта должен содержать от 1 до 100 символов
```

**Comment by Kreyo** [comment] 2016-04-13 07:52
It seems more like Doctrine or even database table issue to me. Try removing the UNIQUE key from the login database field (in sequel pro \ phpmyadmin \ wherever), I wonder if it works as a valid workaround for that issue?

**Comment by metaer** [comment] 2016-04-13 08:58
I've removed UNIQUE key from the login database field and got these:

1. When I edit in form I get unique constraint message: http://dl2.joxi.net/drive/2016/04/12/0004/2633/289353/53/56376a55c2.jpg
The same behavior as before removing unique key

2. When I edit in list, It allows to edit and I have two same values: http://dl1.joxi.net/drive/2016/04/13/0004/2633/289353/53/21fa8c7a62.jpg
Constraint from validation file does not work in this case

**Comment by greg0ire** [comment] 2016-04-13 22:14
@Kreyo : if I understand correctly, the problem is not about getting an SQL error, the problem is about not getting a nice validation error, saying the input value is already used.

**Comment by wronan** [comment] 2017-06-24 11:59
Looks like while using 'editable', 'validation_groups' are not taken into consideration.
I'm facing similar issue:  got a couple of conditional groups set up (in the controller, like `protected $formOptions = ['validation_groups' => [`ValidationGroupsPicker::class, 'someMethodDeterminingGroups']]`) which are working fine. But when I change a boolean flag value on the list (basically it's a 'enabled' field, marked as 'editable') `someMethodDeterminingGroups` is not triggered and thus extra groups are not used.
I'll try to find some time for investigation, it would be nice to have those restrictions working in all forms of entity 'edit'.

**Comment by jordisala1991** [comment] 2018-04-05 20:18
This looks related to #5026 

I agree with @wronan on the validation groups, because Ive got inline edit to work with validations, but I wasnt using validation groups.

Im closing this as a duplicate, because maybe with the newer issue someone will carry this.

If you think those issues are different, please ping me to reopen.

**Closed by jordisala1991** 2018-04-05 20:18 UTC
Labels: bug, unconfirmed
