### ISSUE TITLE
I can't access /admin with https://

### ISSUE THREAD

**Issue by Spomsoree** [sonata-project/SonataAdminBundle#4199] opened 2016-11-07 15:57 UTC
Hi

I'm getting redirected to 
http://

I tried to add `requires_channel: https` to the `^/admin/`path
Adding `schemes [https]`didn't help either.

As soon as I'm on the dashboard I can put https:// in front of the URL without getting redirected.

The same problem exists on demo.sonata-project.org

**Comment by greg0ire** [comment] 2016-11-07 16:32
Does `debug:router` show anything about this ?

**Comment by OskarStark** [comment] 2016-11-08 08:57
Could you solve your problem @Spomsoree ?

**Comment by Spomsoree** [comment] 2016-11-08 09:21
debug:router | grep /admin returns:
- sonata_user_admin_security_login                                    ANY        ANY      ANY    /admin/login 
                                                           
- sonata_user_admin_security_check                                    POST       ANY      ANY    /admin/login_check                                                       

- sonata_user_admin_security_logout                                   ANY        ANY      ANY    /admin/logout

- sonata_admin_redirect                                               ANY        ANY      ANY    /admin/             
                                                     
- sonata_admin_dashboard                                              ANY        ANY      ANY    /admin/dashboard

**Comment by greg0ire** [comment] 2016-11-08 09:22
The `sonata_admin_redirect ` route seems interesting. Maybe try `app/console debug:router sonata_admin_redirect  `

**Comment by Spomsoree** [comment] 2016-11-08 09:23
![image](https://cloud.githubusercontent.com/assets/14187981/20093499/53e81ff6-a59d-11e6-9186-b4472fe384be.png)

Is there a reason why this happens on the demo-page too?

**Comment by greg0ire** [comment] 2016-11-08 09:26
You need to learn how to copy/paste from a terminal and use markdown. Not sure if this route is responsible for this redirection after all… maybe have a look at your symfony logs to see if there is anything interesting.

**Comment by Spomsoree** [comment] 2016-11-08 10:34
I cannot find any hint on why I'm getting redirected.

The strange thing for me is that `/admin/login` works find, same for `/admin/dashboard`
The reason why I made this issue is the fact, that https://xxxxx.demo.sonata-project.org/admin also redirects to an unsecure connection.

Sorry about my use of markdown

**Comment by greg0ire** [comment] 2016-11-08 10:41
> I cannot find any hint on why I'm getting redirected.

Do you see two parts for the two requests in the sf logs? If not, the problems comes from your webserver.

**Comment by Spomsoree** [comment] 2016-11-08 11:22
<img width="1063" alt="screen shot 2016-11-08 at 12 19 49" src="https://cloud.githubusercontent.com/assets/14187981/20097263/dfc5d832-a5ad-11e6-9f98-772c3c55667f.png">

This is my request.

**Comment by greg0ire** [comment] 2016-11-08 12:37
I see no https request. The redirection from `admin/` to `admin` is done by the route we discussed earlier.

**Comment by greg0ire** [comment] 2016-11-08 13:01
Maybe show use your tls setup? Maybe you're using a proxy?

**Comment by Spomsoree** [comment] 2016-11-08 13:30
My first request was `https`, we host it on AWS, so there is definitely a proxy.
But thats not a problem on every other route.

I'll try to debug the route you told me.
Thanks

**Comment by greg0ire** [comment] 2016-11-08 13:31
Have you configure the trusted proxies?

**Comment by Spomsoree** [comment] 2016-11-08 13:33
No, I didn't. Will try this later.
Thanks

**Comment by blaues0cke** [comment] 2016-11-08 15:05
The connection using https is working on our systems, only the route `/admin` seems to have a special behavior. We can reproduce this in the demo environment on http://demo.sonata-project.org/ and even in every project that is using Sonata Admin, on aws, on localhost, everywhere. Should not be related to proxy settings since other urls (regardless whether behind `/admin` or in the "frontend") are working properly.

**Comment by greg0ire** [comment] 2016-11-08 15:21
> only the route /admin seems

Maybe b/c it is the only one that tries to forces https ?

> I tried to add requires_channel: https

**Comment by greg0ire** [comment] 2016-11-23 22:38
@Spomsoree @blaues0cke any news? It's been 15 days… closing this, but feel free to ask for a reopening if you still think this is a bug on our end.

**Closed by greg0ire** 2016-11-23 22:38 UTC

**Comment by blaues0cke** [comment] 2016-11-23 23:29
We workarounded this issue using a kernel event subscriber so far, but the basic issue/problem still exists.

**Comment by greg0ire** [comment] 2016-11-24 07:16
Did you check the things I asked you to check? Namely, is there an https requirement on the route, and did you configure trusted proxies?
