### ISSUE TITLE
Autocomplete property (Notice: Array to string conversion)

### ISSUE THREAD

**Issue by qbbr** [sonata-project/SonataAdminBundle#5350] opened 2018-12-13 04:25 UTC
An exception has been thrown during the rendering of a template ("Notice: Array to string conversion").

[sonata_type_model_autocomplete.html.twig#L289](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig#L289)

```jinja
form.vars.property
```

from [off doc](https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/form_types.html#sonata-adminbundle-form-type-modelautocompletetype):

> This value can be string or array of strings.

**Comment by OskarStark** [comment] 2018-12-13 07:02
Duplicate of https://github.com/sonata-project/SonataAdminBundle/issues/5339

**Closed by OskarStark** 2018-12-13 07:02 UTC
