### ISSUE TITLE
Event ignored in batch action

### ISSUE THREAD

**Issue by itemvirtual** [sonata-project/SonataAdminBundle#4694] opened 2017-10-11 11:36 UTC
Events from persistency aren't fired when you use a batch action, for example if you try to delete one or more items from list view. 

Anybody knows the reason why? I understand that those kinds of events must to be called in all persistency actions.

Anybody detects the same problem? And what can I do?

Thanks,
Fidel

**Comment by jlamur** [comment] 2017-10-11 11:44
Duplicate of #4485

**Closed by jlamur** 2017-10-11 11:44 UTC
