### ISSUE TITLE
Sonata type collection delete row triggers constraints validation

### ISSUE THREAD

**Issue by manuel-bitcraft** [sonata-project/SonataAdminBundle#4348] opened 2017-02-27 04:59 UTC
I have a problem with sonata admin, specifically in a type collection field. Here's the scenario:

I have an entity called "Group" with a one to many relationship to the entity "Member"

In sonata admin I set up the admin classes for the 2 entities.

In the "Group admin" i create a collection type with the Member entity this way

```php
->add('members', 'sonata_type_collection', [
    'by_reference'          => false,
    'label'                 => 'Members',
    'type_options'          => ['delete' => true],
    'btn_add'               => "Add Member",
    'required'              => false,
    'constraints'           => $validation['members'],
],
[
    'edit'              => 'inline',
    'inline'            => 'table'
])
```
The member entity has 4 fields, one of which is required.

```php
->add('firstName', TextType::class, [
    'label'         => 'First Name'
    'constraints'   => [
        new NotBlank(['message' => 'Please enter the name.']),
    ]
])
```
If I click the "Add Member" button in the edit view, it adds a new row as expected. At that point, if I change my mind and decide to delete the newly added record, without adding the name, on save it's returning a validation error telling me 'Please enter the name.' on the field.

Shouldn't the delete action have priority over validation?

**Comment by RomainSanchez** [comment] 2017-02-27 09:39
Same here

**Comment by greg0ire** [comment] 2017-02-27 09:54
Can one of you bisect that bug down to a particular commit?

**Comment by RomainSanchez** [comment] 2017-02-27 15:49
> Can one of you bisect that bug down to a particular commit?

It would be the introduction of sonata_type_collection inline edit i suppose since the problem is that an input with required attribute is inserted in the form and is not removed when the user changes his mind wich prevents submitting the form

I'll have a look but this looks more like a design problem than a bug

**Comment by RomainSanchez** [comment] 2017-02-27 15:51
Maybe this issue should move to DoctrineORMAdminBundle ?

**Comment by greg0ire** [comment] 2017-02-27 15:52
Maybe… I don't know.

**Comment by manuel-bitcraft** [comment] 2017-02-28 00:18
As RomainSanchez said, I think this always was the case. I can open a issue on the DoctrineORMAdminBundle if you think is better. Thanks

**Comment by greg0ire** [comment] 2017-02-28 07:06
> without adding the name

If you want to delete a row, there's a button for that right? You don't expect an empty value to be accepted, do you ? Did you use `allow_delete` or whatever the right option for this is?

**Comment by RomainSanchez** [comment] 2017-02-28 16:49
> If you want to delete a row, there's a button for that right?
It is a checkbox that needs the form to be submitted before the item is removed.So when you add an item and want to remove it (wich end users do all the time) checking the checkbox would need to remove the empty inputs from the dom

**Comment by greg0ire** [comment] 2017-02-28 16:52
> checking the checkbox would need to remove the empty inputs from the dom

Exactly. First thing to do on the js `submit()` event

**Comment by jordisala1991** [comment] 2017-02-28 16:56
With html5 validation enabled you will still get a message before submit, not sure if we can solve this changing only the order of actions in submit() in javascript

**Comment by greg0ire** [comment] 2017-02-28 17:00
[Indeed](http://stackoverflow.com/questions/15138329/catch-submit-before-html5-validation)

**Comment by jordisala1991** [comment] 2017-02-28 17:01
IMO the problem is, add is done in ajax, remove is done on reload... not sure if this has an easy fix tho.

**Comment by RomainSanchez** [comment] 2017-02-28 17:04
If it is a new entry you remove the inputs from the dom on click and if it is an existing one you reove from the dom and replace with a hidden input/hidden inputs that will "submit the deletion" or maybe trigger an ajax request to delete the item even before form submission

**Comment by greg0ire** [comment] 2017-02-28 17:04
Well if you remove the input immediately when checking the checkbox (or cliking a button), problem solved. Also, you could just make toggle `disable` on checking the checkbox

**Comment by RomainSanchez** [comment] 2017-02-28 17:07
> you could just make toggle disable on checking the checkbox

I'd say that is the way to go so things are consistent between deleting a freshly created entry and deleting an existing entry

**Comment by RomainSanchez** [comment] 2017-03-02 09:56
After giving it a shot several questions arose: 

1: disabling via javascript works fine but in wich template should the script be included?
2: Does the script need to handle the case where iCheck would be disabled ?
3: should the script itself live in AdminBundle or DoctrineORMBundle (I need to add classes to form elements in DoctrineORMBundle templates as well)

**Comment by greg0ire** [comment] 2017-03-02 10:13
1. the create/edit page should always have it IMO
2. no idea what iCheck is
3. I think it could benefit phpcr too, so AdminBundle… @dbu, thoughts?

**Comment by RomainSanchez** [comment] 2017-03-02 10:16
> no idea what iCheck is

ICheck is the js plugin used for checkboxes.

```
"sonata_admin" => array:9 [▼
    "name" => "phones"
    "admin" => ContactAdmin {#3294 ▶}
    "value" => PersistentCollection {#4036 ▶}
    "edit" => "inline"
    "inline" => "table"
    "field_description" => FieldDescription {#3775 ▶}
    "block_name" => false
    "options" => array:15 [▼
      "use_icheck" => true
```

**Comment by greg0ire** [comment] 2017-03-02 10:18
For 2, I'm unsure, I'd say it should work too…

**Comment by RomainSanchez** [comment] 2017-03-02 10:29
If iCheck is i need to listen to their `ifChanged` event instead of `change` but `window.SONATA_CONFIG` has the info so problem solved.

**Comment by dbu** [comment] 2017-03-02 10:39
inline editing is useful for the phpcr admin too, so if we can fix the infrastructure for that, please do it here in the base admin bundle

**Comment by braianj** [comment] 2019-05-14 13:15
Hi, is there I documentation on how to use it? Didn't find it

**Comment by MatTheCat** [comment] 2019-12-30 13:24
I cannot find any activity on this matter after #4441 got merged so I guess this issue should be reopened.

**Comment by kirya-dev** [comment] 2021-01-25 17:35
Im suggest solving in any issue: Before set data we delete fisrt. @VincentLanglet you are closed not this issue.
Problem solving here: 
https://github.com/sonata-project/SonataAdminBundle/issues/6391#issuecomment-709232369

**Comment by jordisala1991** [comment] 2023-04-10 08:11
I have followed @kirya-dev suggestions:

https://github.com/sonata-project/form-extensions/pull/414

Can someone confirm it works for their use case? cc / @VincentLanglet

**Closed** 2023-04-10 12:31 UTC
Labels: bug, keep
