### ISSUE TITLE
Improve functionality by split Admin -  concept for discussion

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataAdminBundle#6079] opened 2020-05-04 13:17 UTC
## Feature Request

I very often use admin to generate CRUD for adminstrator. Write some configuration and all just work excelent. It is awsome!!! I have also project where CRUD is require in employee panel. There i must write it myself. While help with contribiute sonata-project I learn structures and got some IDEA.

#### At first what is Admin? - a comprehensive set of tools for the administrative panel
- show generator
- form generator
- list generator (with filters)
- exporter list (look at https://github.com/sonata-project/SonataAdminBundle/issues/5854#issuecomment-618113138)
- access layer
- menu structure
- others

#### My IDEA
- split admin to atomic service by functionality
- current AbstractAdmin should be support in 4.x and drop in 5.x

#### What we get?
- no more huge Admin class
- encapsulation functionality, easy to contribute
- awsome tools to generate CRUD (not only admin)
- posibillity to use admin fom types in own panels/CRUD based on list/edit service

#### It is only concept. I can expand if you are intrested. 

We should end current work too.

**Comment by VincentLanglet** [comment] 2020-05-04 19:48
> #### My IDEA
> * split admin to atomic service by functionality
> * current AbstractAdmin should be support in 4.x and drop in 5.x

You can take a look at https://github.com/sonata-project/SonataAdminBundle/issues/3947
 
> #### It is only concept. I can expand if you are intrested.
> We should end current work too.

Yes, I would be already happy if we achieve to release Sonata 4.0 with a Symfony 5 and Twig 3 compatibility this year 😄

**Comment by core23** [comment] 2020-05-05 09:56
I really like the idea :+1:  but when I look back to all big changes we could accomplish since the release of 3.0.0 ([released around 2016](https://github.com/sonata-project/SonataAdminBundle/releases/tag/3.0.0)) the chances to do this are getting lower and lower. We still have some bigger problems we need to solve first.

IMHO we should not accept any more bigger changes for the next major release and start finishing. After the release we should discuss what to do next.

**Comment by VincentLanglet** [comment] 2020-05-05 09:57
Yes I agree, this should not be in the 4.0.

**Comment by core23** [comment] 2020-05-05 09:58
Can we agree to feature freeze the 4.x / master branch please.

cc @sonata-project/contributors

**Comment by greg0ire** [comment] 2020-05-05 21:32
This is definitely not going to be in 4.0 . To make everyone happy, we should try not to wait too much before releasing 5.0. Maybe setting an arbitrary date in the future like exactly 1 year after 4.0 would help.

**Comment by wbloszyk** [comment] 2020-05-05 21:53
Probably we can inject low level service to admin and use it like current Admin API. Drop it in 5.0. We can model IT befor release 4.0 and decide what to do.

**Comment by VincentLanglet** [comment] 2020-05-05 23:21
> Can we agree to feature freeze the 4.x / master branch please.
> 
> cc @sonata-project/contributors

I think there is still a lot of changes in the 4.x TODO-list:
- Dropping CoreBundle
- Symfony 5 compatibility https://github.com/sonata-project/SonataAdminBundle/issues/5788
- Twig 3 compatibility https://github.com/sonata-project/SonataAdminBundle/pull/5973
- Removing all the NEXT_MAJOR code
- Closing API https://github.com/sonata-project/SonataAdminBundle/issues/5791
- Maybe using webpack encore https://github.com/sonata-project/SonataAdminBundle/pull/5461
- Maybe LTE update https://github.com/sonata-project/SonataAdminBundle/pull/5989
- Some BC-break (adding exception or fixing bugs)

I can't say how much time is needed for that so I have trouble to say "We won't add any features on 3.x during a lot of months". Or maybe I mis-understood what you mean @core23 ?

**Comment by greg0ire** [comment] 2020-05-06 06:28
I don't think we should stop adding any features at any point. IMO we should have a list such as yours, have it be immutable and when every box is checked, we release. I'd remove the 2 Maybe from your list. If someone manages to do them before the other they can go in the release, but otherwise, let's not block this.

**Comment by wbloszyk** [comment] 2020-05-06 07:42
Droping CoreBundle is almost done.
I have sandbox with symfony4 and bootstrap4. We can improve this templates and add in sonata 3 to support bootstrap 3 and 4.

**Comment by VincentLanglet** [comment] 2020-05-06 10:05
> I have sandbox with symfony4 and bootstrap4. We can improve this templates and add in sonata 3 to support bootstrap 3 and 4.

Nice ! Does font-awesome 5 is coming with this changes too ?

**Comment by wbloszyk** [comment] 2020-05-06 10:19
I dont remember. This is new feature, we can add it too or even support many version. Lets merge `sandbox symfony4 and flex` then we can add feature branches for some templates like bootstrap3, 4 ... 
Sandbox include all bundles, symfony4 allow use `templates` directory to override all bundles templetes in one directory. After accept branch we can just move it to bundle resources.

**Comment by core23** [comment] 2020-05-07 07:16
> I can't say how much time is needed for that so I have trouble to say "We won't add any features on 3.x during a lot of months". Or maybe I mis-understood what you mean @core23 ?

I meant, that we should not introduce any new fancy features for the master branch. We should not introduce any more BC breaks for the major update. This will move the release in the farther future.
We should refocus which feature we want for the next major and which we could finish soon

**Comment by wbloszyk** [comment] 2020-05-07 08:13
I think this feature can be BC. We can add this feature to AbstractAdmin without change API and make BC-break in 5. In some version od admin 4.x we will have two way to use admin.

**Comment by VincentLanglet** [comment] 2021-02-22 21:05
I think we can close this as it's a duplicate of https://github.com/sonata-project/SonataAdminBundle/issues/3947
I'll recommend you to post your idea in the other issue instead @wbloszyk.

**Closed by VincentLanglet** 2021-02-22 21:05 UTC
Labels: feature, keep
