### ISSUE TITLE
Admin definition with no tabs and no closing tab causes exception

### ISSUE THREAD

**Issue by EdwardIII** [sonata-project/SonataAdminBundle#2721] opened 2015-02-14 16:06 UTC
When I tried to add the SeoBundle I kept seeing this error:

```
You should close previous group with end() before adding new tab
```

It seemed to be because my admin definition with no tabs needed to close an implicit tab:

https://gist.github.com/EdwardIII/8d9f36b482db9be5ae47 (works when adding ->close() to the end).

This seems a little confusing?

Redirected here by @dbu from https://github.com/symfony-cmf/SeoBundle/issues/211

**Comment by dbu** [comment] 2015-02-14 16:20
imho, the formMapper `with()` calls should work in a stateless manner, that is when i start with $formMapper again, all previous groups are explicitly closed. 

the current behaviour is particulary nasty with the implicit default group, as there is no `with` but there still needs to be an `end` when admin extensions are used.

**Comment by WouterJ** [comment] 2015-02-14 22:23
Imo, the tree implementation should be revisted and be transformed to something the Symony Config component is using. I'm happy to work on that if others agree.

**Comment by greg0ire** [comment] 2016-07-25 09:17
> the tree implementation should be revisted and be transformed to something the Symony Config component is using.

@wouterj : this is quite old but if it is still relevant and you still feel up to working on that, can you elaborate on how these differ ?

**Comment by wouterj** [comment] 2016-08-03 14:12
@greg0ire the biggest difference is that the Sonata tree implementation is statefull, while the config structure is stateless. To give an example:

```php
// Sonata
$mapper
    ->with('group1') // sets $mapper->currentGroup to 'group1' and returns $this
    ->end() // sets $mapper->currentGroup to null and returns $this
;

// Symfony Config
$root
    ->children()
        ->arrayNode('group1') // creates new ArrayNodeDefinition instance, appends it to the $children property and returns it
        ->end() // returns parent
    ->end()
;
```

**Comment by greg0ire** [comment] 2016-08-03 14:24
Took me a good minute but I think I understand, and indeed, this is quite nasty… :+1: for this . By the way, if I understand correctly, this will not imply changing the API of the mapper and should be BC, right?

**Comment by core23** [comment] 2016-08-07 13:55
Maybe we can solve this with the following (not tested):

```php
    public function defineFormBuilder(FormBuilderInterface $formBuilder)
    {
        $mapper = new FormMapper($this->getFormContractor(), $formBuilder, $this);

        $this->configureFormFields($mapper);

        $mapper->end();

        foreach ($this->getExtensions() as $extension) {
            $extension->configureFormFields($mapper);
        }

        $this->attachInlineValidator();
    }

```

**Comment by wouterj** [comment] 2016-08-07 14:37
@greg0ire The API will be the same. However, there is a big BC break as the statefullness (and thus behaviour) changes significantly. E.g. the following code wouldn't work anymore:
```php
$mapper->with('group1');
$mapper->add(...);
$mapper->end();
```
This is quite common when if statements where used for dynamic `add()` calls for instance.

I'm not sure yet how to make it BC.

**Comment by greg0ire** [comment] 2016-08-07 18:05
Oh indeed! I recall reading about an `if` function to help maintain the chaining. IMO, the bc break can't be handled nicely, because you cannot detect chaining and throw a depreciation warning if it misses. It means this should be developed directly on master, and that an upgrade note should be provided with it.

**Comment by wouterj** [comment] 2016-08-08 09:50
I think you can detect chaining:

 * If `->add()` is called *without* calling `->with()`, everything will be added to the default group and chaining and non-chaining behave the same
 * If `->with()` is called, start assuming the dev uses the new API. If `->add()` is called directly on the current instance, the non-chaining old-API is used. Trigger deprecation.
 * Multiple `->with()` calls work just the same.

**Comment by greg0ire** [comment] 2016-08-08 10:12
Oh yes, that could work indeed I think.

> I recall reading about an if function

I found [something similar](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Mapper/BaseGroupedMapper.php#L154) (`ifTrue` and `ifFalse`, actually), which means chaining should be possible in all situations :+1:

**Comment by jordisala1991** [comment] 2018-04-05 20:44
Closing as duplicate of #3524

I didnt understood the issue because is it a big confusing, I guess it is about using tabs without groups.

If the two issues are not related, please ping me to reopen.

**Closed by jordisala1991** 2018-04-05 20:44 UTC
