### ISSUE TITLE
DataGridFilter Autocomplete

### ISSUE THREAD

**Issue by MHaendel** [sonata-project/SonataAdminBundle#3078] opened 2015-06-29 15:28 UTC
Hey,

when I try to use the `doctrine_orm_model_autocomplete` filter Symfony 500s:

`No attached service to type named doctrine_orm_model_autocomplete`

``` php
->add('account', 'doctrine_orm_model_autocomplete', array(), null, array(
    'property'=>'user.username',
))
```

**Comment by Soullivaneuh** [comment] 2015-06-29 15:46
Did you enable the doctrine-orm-admin bundle on your `appKernel` class?

**Comment by MHaendel** [comment] 2015-06-29 15:47
```
"sonata-project/admin-bundle": "2.4.*@dev",
"sonata-project/doctrine-orm-admin-bundle": "2.4.*@dev",
```

```php
new Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle(),
new Sonata\AdminBundle\SonataAdminBundle(),
```

**Comment by Soullivaneuh** [comment] 2015-06-29 15:52
Could you paste you Admin class?

**Comment by MHaendel** [comment] 2015-06-29 15:53
Sure!

```php
<?php
namespace EdelNetzwerk\CashyBundle\Admin;

use Sonata\AdminBundle\Admin\Admin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use EdelNetzwerk\ApiBundle\Entity\Client;
use EdelNetzwerk\BankingBundle\Entity\Transaction;

class TransactionAdmin extends Admin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('account', 'sonata_type_model_list', array())
            ->add('event', 'sonata_type_model_list', array())
            ->add('state', 'choice', array(
                'choices' => Transaction::getStateList()
            ))
            ->add('createdAt')
            ->add('amount')
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('account', 'doctrine_orm_model_autocomplete', array(), null, array(
                'property'=>'username',
            ))
            ->add('event')
            ->add('createdAt')
            ->add('amount')
            ->add('state', 'doctrine_orm_string', array(), 'choice', array('choices' => Transaction::getStateList()))

        ;
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('id')
            ->add('account')
            ->add('event')
            ->add('amount')
            ->add('state', 'choice', array('choices' => Transaction::getStateList()))
            ->add('createdAt')
            ->add('_action', 'actions', array(
                'actions' => array(
                    'edit' => [],
                    'delete' => []
                )
            ))
        ;
    }
}
```

**Comment by Soullivaneuh** [comment] 2015-06-29 15:59
Don't know. @rande any idea?

@MHaendel could you please paste result of `composer info -i | grep sonata`?

**Comment by MHaendel** [comment] 2015-06-29 16:01
Seems to be a strange bug then :-1: 

```
$ composer info -i | grep sonata
sonata-project/admin-bundle              dev-master 18a76b7
sonata-project/block-bundle              2.3.1
sonata-project/cache                     1.0.6
sonata-project/cache-bundle              2.2.4
sonata-project/core-bundle               2.3.4
sonata-project/datagrid-bundle           dev-master f3be409
sonata-project/doctrine-extensions       1.0.2
sonata-project/doctrine-orm-admin-bundle dev-master 071236b
sonata-project/easy-extends-bundle       2.1.9
sonata-project/exporter                  1.3.4
sonata-project/notification-bundle       2.3.2
sonata-project/page-bundle               dev-master 80ee500
sonata-project/seo-bundle                2.0.0
```

**Comment by malutanpetronel** [comment] 2015-09-15 07:00
I also do get a 
No attached service to type named `sonata_type_model_autocomplete` in a sonata admin class

**Comment by lucasgranberg** [comment] 2015-11-16 11:14
I have the same problem. I debugged the types array in filter factory and it looks like this:

```
[doctrine_orm_boolean] => sonata.admin.orm.filter.type.boolean
[doctrine_orm_callback] => sonata.admin.orm.filter.type.callback
[doctrine_orm_choice] => sonata.admin.orm.filter.type.choice
[doctrine_orm_model] => sonata.admin.orm.filter.type.model
[doctrine_orm_model_autocomplete] => sonata.admin.orm.filter.type.model_autocomplete
[doctrine_orm_string] => sonata.admin.orm.filter.type.string
[doctrine_orm_number] => sonata.admin.orm.filter.type.number
[doctrine_orm_date] => sonata.admin.orm.filter.type.date
[doctrine_orm_date_range] => sonata.admin.orm.filter.type.date_range
[doctrine_orm_datetime] => sonata.admin.orm.filter.type.datetime
[doctrine_orm_time] => sonata.admin.orm.filter.type.time
[doctrine_orm_datetime_range] => sonata.admin.orm.filter.type.datetime_range
[doctrine_orm_class] => sonata.admin.orm.filter.type.class
```

As you can see it is called ```doctrine_orm_model_autocomplete``` so something has changed somewhere. I suspect its not in sonata admin but in doctrine-orm-admin-bundle.

**Comment by daifabde** [comment] 2016-05-09 10:09
I also get the same error with
        "sonata-project/admin-bundle": "2.3.*",
        "sonata-project/doctrine-orm-admin-bundle": "2.3.*",

**Comment by Soullivaneuh** [comment] 2016-05-09 10:15
@MHaendel @daifabde 2.x versions of admin-bundle are not maintained anymore.

Please upgrade to 3.x (previously 2.4.x) and tell me if the issue is still here.

**Comment by jon92** [comment] 2016-06-13 14:35
I've got 
`
"sonata-project/admin-bundle": "3.x-dev",
 "sonata-project/doctrine-orm-admin-bundle": "dev-master"
`
and the bug is still here. 
I managed to get it work on formMapper but it seems impossible with datagridMapper to have autocomplete enabled on filters.

**Comment by pulzarraider** [comment] 2017-05-01 23:14
Closing this issue, because it's related to SonataAdmin 2.x versions  and in 3.x versions the autocomplete form type is working ok.

@MHaendel @malutanpetronel @lucasgranberg @daifabde please report any problems you found in the new issue.

**Closed** 2017-05-01 23:14 UTC
