### ISSUE TITLE
KNP Menu 2.3 deprecations

### ISSUE THREAD

**Issue by KDederichs** [sonata-project/SonataAdminBundle#4790] opened 2017-11-23 11:02 UTC
## Subject

After updating the SonataAdminBundle installed the knp-menu in version 2.3 which deprecated some things (see below) which will cause unit tests to break.

## Steps to reproduce

Install knp-menu >= 2.3 and run a unit test.

## Expected results

No deprecation warnings

## Actual results
`The Knp\Menu\Matcher\Matcher::addVoter() method is deprecated since version 2.3 and will be removed in 3.0. Pass voters in the constructor instead:`

`Not passing a RequestStack as the first argument for "Knp\Menu\Matcher\Voter\RouteVoter" constructor is deprecated since version 2.3 and won't be possible in 3.0:`

`The Knp\Menu\Matcher\Voter\RouteVoter::setRequest() method is deprecated since version 2.3 and will be removed in 3.0. Pass a RequestStack in the constructor instead:`

**Comment by OskarStark** [comment] 2017-11-23 11:10
>  which will cause unit tests to break.

the should not break your unit tests. How do you run your tests?

**Comment by greg0ire** [comment] 2017-11-23 11:11
probably in strict mode. But it should be fixed anyway, so the issue is valid.

**Comment by Hanmac** [comment] 2017-11-23 11:13
i have seen this warnings in debug mode too
i thought that they are an issue on the menu bundle, and not sonata itself

**Comment by OskarStark** [comment] 2017-11-23 11:13
> But it should be fixed anyway, so the issue is valid.

yes, sure

**Comment by greg0ire** [comment] 2017-11-23 11:14
@Hanmac to be sure, you'd have to provide a stack trace.

**Comment by OskarStark** [comment] 2017-11-23 11:15
@greg0ire not sure if we can fix it on our side, could not finde `addVoter` in admin-bundle

**Comment by Hanmac** [comment] 2017-11-23 11:16
@greg0ire I am currently not at work this week
You can see it if opening the sonata admin via dev mode and then checkout the deprecations

**Comment by greg0ire** [comment] 2017-11-23 11:18
getting a stack trace can be done by running the test suite with `SYMFONY_DEPRECATIONS_HELPER=/part of the error message/`. Please do that for every deprecation.

**Comment by greg0ire** [comment] 2017-11-23 11:18
@OskarStark it does sound like it's the fault of the bundle then

**Comment by KDederichs** [comment] 2017-11-23 11:50
Route voter stack trace:
https://pastebin.com/7TPDWkir

addVoter stack trace:
https://pastebin.com/dkEudK6m

setRequest stack trace:
https://pastebin.com/2LTY42jL

Put them on pastebin for the sake of readability

**Comment by greg0ire** [comment] 2017-11-23 12:05
Thanks!

**Comment by Hanmac** [comment] 2017-11-23 15:05
@OskarStark you should wrap them into code 
Otherwise it create link to issues

**Comment by TorbenLundsgaard** [comment] 2017-11-24 10:23
The problem is in the KnpMenuBundle https://github.com/KnpLabs/KnpMenuBundle/pull/358

**Comment by greg0ire** [comment] 2017-11-29 18:10
Closing then

**Closed by greg0ire** 2017-11-29 18:10 UTC
Labels: bug
