### ISSUE TITLE
List View: Join by attribute and constant with createQuery()

### ISSUE THREAD

**Issue by chrisp1001** [sonata-project/SonataAdminBundle#3981] opened 2016-07-01 11:36 UTC
### Environment

Symfony 2.7
#### Symfony packages

``` bash
$ composer show symfony/*
symfony/assetic-bundle                   v2.6.1  Integrates Assetic into Symfony2
symfony/monolog-bundle                   v2.7.1  Symfony MonologBundle
symfony/swiftmailer-bundle               v2.3.8  Symfony SwiftmailerBundle
symfony/symfony                          v2.7.1  The Symfony PHP framework
```
#### Sonata packages

``` bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.3.2   The missing Symfony Admin Generator
sonata-project/block-bundle              3.0.0   Symfony SonataBlockBundle
sonata-project/cache                     1.0.7   Cache library
sonata-project/core-bundle               3.0.0   Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.0.0   Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.4.1   Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1   Symfony SonataFormatterBundle

```
#### PHP version

``` bash
$ php -v
PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```
## Subject

As it seems that it is not possible to join a table by an attribute as well as a constant, so I needed to find a workaround. I tried to add a join by hand in createQuery function of my admin class like this:

``` php
    protected function configureListFields(ListMapper $listMapper)
    {       
        $listMapper->addIdentifier('offersId', 'integer') // of ProductsOffers Entity
            ->addIdentifier('productsName') // of ProductsDescription Entity
            ->add('_action', 'actions', array(
                    'actions' => array(
                        'edit' => array(),
                    )
            ));

    }

    public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);

        $query->addSelect('p')->from('AppBundle:ProductsDescription', 'p')
                ->andWhere($query->getRootAlias().'.productsId = p.productsId') // join by attribute
                ->andWhere('p.languageId = 2'); // join by constant

        return $query;
    }
```

Note: The ProductsDescription Entity has a compount primary key of productsId and languageId:

``` php
    class ProductsOffers
    {
    /**
     * @var integer
     *
     * @ORM\Column(name="products_id", type="integer", nullable=true)
     */
    private $productsId;

      .....
    }


    class ProductsDescription
    {
    /**
     * @var string
     *
     * @ORM\Column(name="products_name", type="string", length=255, nullable=false)
     */
    private $productsName;

    /**
     * @var integer
     *
     * @ORM\Column(name="products_id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="NONE")
     */
    private $productsId;

    /**
     * @var integer
     *
     * @ORM\Column(name="language_id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="NONE")
     */
    private $languageId;

    ......
    }
```

## Expected results

I would expect that there would be shown a productsName in every dataset in the list view.
## Actual results

However every productsDescription as well as every productsOffers entity gets an own line in the list view. Furthermore every productsName is only shown once. If there are more productsOffers.productsId that reference one and the same entity (one to many) in productsOffers, the productsName is only shown for the first entity of productsDescription which results in:

![screenshot - 01 07 2016 - 13 31 19](https://cloud.githubusercontent.com/assets/14017864/16520431/54dbfd42-3f90-11e6-965a-3277b49324cb.png)

For offersId 173, 172, 171 should be shown a productsName as well but is not as one of the entities above them already showed the productsName of the entity 173, 172, 171 is linked to as well.

Furthermore one result dataset should be shown in one line not two.

**Comment by Soullivaneuh** [comment] 2016-07-01 11:41
Please complete correctly the issue template (sonata and Symfony packages).

Also update to the last stable version of all the concerned. sonata bundles.

**Comment by chrisp1001** [comment] 2016-07-01 12:06
Sorry, added now.

**Comment by Soullivaneuh** [comment] 2016-07-01 12:12
Your sonata dependencies are not up to date. For example, admin-bundle last version is 3.3.2, not 3.1.0.

Please update and tel us if the issue is still here.

**Comment by chrisp1001** [comment] 2016-07-01 12:36
Updated (see first post) and cache cleared, but still the same behaviour.

**Comment by Soullivaneuh** [comment] 2016-07-01 12:41
I said sonata dependenc**ies**. :-)

sonata-project/doctrine-orm-admin-bundle is not up to date too and this bundle is highly concerned.

**Comment by chrisp1001** [comment] 2016-07-01 12:52
Oh dear, sorry, I am new to Symfony and Sonata.

I just tried to edit my first post however it just says 'undefined' in the textbox now, so I am posting the package information here:

```
sonata-project/admin-bundle              3.3.2   The missing Symfony Admin Generator
sonata-project/block-bundle              3.0.1   Symfony SonataBlockBundle
sonata-project/cache                     1.0.7   Cache library
sonata-project/core-bundle               3.0.3   Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.0.4   Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.5.0   Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1   Symfony SonataFormatterBundle
```

Unfortunately the behaviour is still the same.

**Comment by rccc** [comment] 2016-07-04 10:25
Hello,

Maybe my answer is not pertinent but when i have to add a join table in the _createQuery_ method i use this :

```
        $query->addSelect('c');
        $query->leftJoin(sprintf('%s.commission',$query->getRootAlias()), 'c');
```

**Comment by chrisp1001** [comment] 2016-07-04 13:40
Hi @rccc,

this is just an other method of performing a join, so should not make any difference. I can see the query in the debug as well and all looks good except the List View.

**Comment by rccc** [comment] 2016-07-06 08:05
Hello,

I understand.

So i imagine you have run the sql query by yourself so that you can confirm results are well joined.

Because i can't see what could be the problem inside the list loop.


++

**Comment by jordisala1991** [comment] 2018-04-17 21:33
This issue is really specific, and a bit old. There was a proposed workaround. But there was no more information provided.

Closing for now. If you still have this issie, please ping me to reopen

**Closed by jordisala1991** 2018-04-17 21:33 UTC
Labels: bug, unconfirmed
