### ISSUE TITLE
[Design issue] Hard to distinguish disabled unchecked checkbox

### ISSUE THREAD

**Issue by homersimpsons** [sonata-project/SonataAdminBundle#4932] opened 2018-02-05 08:22 UTC
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
# sonata-project/admin-bundle              3.31.0 3.31.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.11.0 3.11.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.9.0  3.9.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.4.1  3.4.1  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
sonata-project/translation-bundle        2.3.0  2.3.0  SonataTranslationBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
# Put the result here.
```
(Symfony 3.4.4)

#### PHP version

```
$ php -v
# PHP 7.1.11-0ubuntu0.17.10.1 (cli) (built: Nov  1 2017 16:30:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11-0ubuntu0.17.10.1, Copyright (c) 1999-2017, by Zend Technologies
```

## Subject

Disabled unchecked checkbox are rendered as normal checkbox (except for the cursor pointer)

## Steps to reproduce

Declare a `CheckboxType` in your form, be sure its boolean value is `false` and set `'disabled' => true,`

## Expected results

Checkbox should be gray colored (just like a checked disabled checkbox) and pointer should be default.

## Actual results

Pointer is default (maybe it could be `not-allowed`)
But its background is white, just lile a normal (not disabledd) checkbox

**Comment by jordisala1991** [comment] 2018-03-18 11:54
I tried to reproduce your issue, and found this:

*Disabled*
![captura de pantalla 2018-03-18 a las 12 51 22](https://user-images.githubusercontent.com/1137485/37565534-4ddb7bc8-2aab-11e8-91af-9a8c445306cc.png)

*Enabled*
![captura de pantalla 2018-03-18 a las 12 51 37](https://user-images.githubusercontent.com/1137485/37565532-4c43cf7c-2aab-11e8-8acb-eba59b0c7818.png)


There is a difference when you have the 2 screenshots (different color on the border of the checkbox), but I agree with you that it is hard to know when a single checkbox is disabled.

We are using this library to control how we render checkboxes and radio buttons: http://icheck.fronteed.com/

So this issue is most likely to belong there.
I did a fast search on that library, and it seems abandoned or not maintained since 2-3 years. (But it still works great for our use case)

https://github.com/fronteed/icheck/issues/318
https://github.com/fronteed/icheck/issues/378

There are several issues about it (probably more).

Closing this as it is not related to Sonata, but to the library we are using.

If you know another library that handles this better, maybe you can do another issue with an RFC to change icheck for another thing. Probably it will mean BC breaks and will target master instead of stable, but if it is great, we can swap them.

**Closed by jordisala1991** 2018-03-18 11:54 UTC

**Comment by jordisala1991** [comment] 2018-03-18 11:58
If the @sonata-project/contributors consider we can add some styles to improve this a little bit, we can reopen.

But IMO adding styles to "fix" another library, does not sound super great
