### ISSUE TITLE
Imbricated sonata_type_collection

### ISSUE THREAD

**Issue by Birmania** [sonata-project/SonataAdminBundle#262] opened 2011-08-30 13:57 UTC
I have a sonata_type_collection in a form and one of the column of it is a sonata_type_collection (Imbricated table).

When I load the page it seem to work but when I try to add a row to the second sonata_type_collection, it said me :

Fatal error: Call to a member function getName() on a non-object in /......./vendor/bundles/Sonata/AdminBundle/AdminHelper.php on line 96

Thanks

**Comment by webdevilopers** [comment] 2015-03-27 11:42
:+1: 

Possible duplicate of
- https://github.com/sonata-project/SonataAdminBundle/issues/1228
- https://github.com/sonata-project/SonataAdminBundle/issues/1327

PR:
- https://github.com/sonata-project/SonataAdminBundle/pull/1971

**Comment by chalasr** [comment] 2016-03-05 10:06
Fixed by PR #3553 .

Same for those possible duplicates

- #262 
- #1228 
- #1327

**Closed** 2016-07-15 18:48 UTC
