### ISSUE TITLE
List collection doesn't update after save

### ISSUE THREAD

**Issue by romaricp** [sonata-project/SonataAdminBundle#4513] opened 2017-06-09 13:11 UTC
#### Symfony & Sonata  packages

```bash
$ composer show symfony/*
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "friendsofsymfony/jsrouting-bundle": "^1.6",
        "incenteev/composer-parameter-handler": "^2.0",
        "nelmio/api-doc-bundle": "^2.13",
        "nelmio/cors-bundle": "^1.5",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^3.0.2",
        "sonata-project/admin-bundle": "^3.18",
        "sonata-project/doctrine-orm-admin-bundle": "^3.1",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.3.*",
        "twig/twig": "^1.0"
```

#### PHP version
```bash
$ php -v
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

```

## Subject
List collection doesn't update after insert

## Steps to reproduce
I have just 2 tables : 
### Keyword
```php
    # APP/CoreBundle/Entity/Keyword.php
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
      * @var integer
      *
      * @ORM\ManyToOne(targetEntity="APP\CoreBundle\Entity\Scope", inversedBy="keywords")
      */
    private $scope;
```

### Scope
``` php 
    # APP/CoreBundle/Entity/Scope.php
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="APP\CoreBundle\Entity\Keyword", mappedBy="scope")
     */
    private $keywords;
```

I have install Sonatra-admin-bundle and everything work well except one think, when I had a new entry Keyword, I can add directly a new Scope via Ajax. For this fonctionality I use in my controller : 

``` php 
# APP/CoreBundle/Admin/KeywordAdmin.php
class KeywordAdmin extends AbstractAdmin
{

    //protected function configureShowFields(ShowMapper $showMapper){
   //...

    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->with('Mots-clés', array('class' => 'col-md-9',))
                        ->add('name', 'text', array('label' => 'Nom'))
                    ->end()
                    ->with('Gamme', array('class' => 'col-md-3'))
                        ->add('scope', 'sonata_type_model', array(
                            'class' => 'APP\CoreBundle\Entity\Scope',
                            'property' => 'name',
                            'label' => 'Gamme',
                            //'allow_add'=> true,
                        ))
                    ->end();
    }

    //protected function configureDatagridFilters(DatagridMapper $datagridMapper){
    //...
```

## Expected results & Actual results
When I had a new Scope directly from the Keyword's form, I got the Scope's form via a modal window. 
So I save my new Scope, the modal will close and I got once again the Keyword's form with the list of Scope avalaible. But this is the problem : **the new Scope is not in the list** !

## Sreenshot of my issue
![admin creer 1](https://user-images.githubusercontent.com/2545417/26976785-a373e890-4d25-11e7-9f9d-f2b65d141b9a.png)

![admin creer 2](https://user-images.githubusercontent.com/2545417/26976796-b52fb744-4d25-11e7-9d4d-50c3c2b431d9.png)

![admin creer](https://user-images.githubusercontent.com/2545417/26976757-85410dbc-4d25-11e7-9b82-e410b386180c.png)

![admin creer 3](https://user-images.githubusercontent.com/2545417/26976826-d648d5c8-4d25-11e7-8f00-8ebb0a373b96.png)

**Comment by jordisala1991** [comment] 2018-03-27 20:47
I just tried it today, and I didnt had any issues with model type. Things that could happen:

- element not created because some error
- not using FQCN for the form type
- class is not needed for the sonata model type

Im closing this one for now as I cannot reproduce your issue with the information you provided. If you still having this issue, it would be nice if you could provide some small app with a reproducible example of the issue.

**Closed by jordisala1991** 2018-03-27 20:47 UTC
