### ISSUE TITLE
Advanced filters type switched with translations

### ISSUE THREAD

**Issue by zajca** [sonata-project/SonataAdminBundle#3688] opened 2016-03-29 12:38 UTC
When advanced filter is used. Type is shown in select2 not translated constraint (which is than send in form). As far as I found only working conditions appears on datepicker.

tested on latest master and symfony 3.0.3 and mongodb-admin

here is screenshot:
![Screenshot](http://i.imgur.com/sHGHRDe.png)

resulting form: (you can see missing translation in types like 'filter[title][type]' where should be value)

```
filter[title][type]:label_type_yes
filter[title][value]:xx
filter[placeType][type]:
filter[placeType][value]:
filter[tags][type]:nerovná se
filter[tags][value][]:0
filter[address__city][type]:label_type_no
filter[address__city][value]:xx
filter[email][type]:label_type_no
filter[email][value]:xxx
filter[startTime][type]:3
filter[startTime][value]:11. 3. 2016 14:30:14
filter[endTime][type]:
filter[endTime][value]:
filter[_page]:1
filter[_sort_by]:id
filter[_sort_order]:ASC
filter[_per_page]:32
```

**Comment by greg0ire** [comment] 2016-04-04 09:01
I have a hard type understanding your post, in particular the part about "constraints". Could you proof-read it and try to clarify the problem. Also, are you sure this is the right bundle (maybe it's a mongodb bundle problem)

**Comment by zajca** [comment] 2016-04-06 14:01
Sry, I used wrong word. Condition is better :) 

I'm not sure if this is mongo-admin or sonata-admin issue. Could be problem in filter implementation on mongo-admin.

But problem is 'simple' filter type translation is send in request and user see filter type value. So it's upside down.

**Comment by greg0ire** [comment] 2016-04-06 14:09
Oh I see. This is definitely a bug. Look for `choices_as_values` in the symfony documentation to understand the problem, and then please submit a PR (or check if the problem is not already fixed in master).

**Comment by jordisala1991** [comment] 2018-01-31 19:10
If any this is a problem on MongoDbAdmin if any. Since the user is using Sf 3 he should provide choices flipped. Maybe thats the problem. Closing

**Closed by jordisala1991** 2018-01-31 19:10 UTC
