### ISSUE TITLE
Wrong results in Admin Search feature when a 'createQuery' definition is used

### ISSUE THREAD

**Issue by gprioux** [sonata-project/SonataAdminBundle#4074] opened 2016-08-16 14:18 UTC
#### Sonata packages

sonata-project/admin-bundle              3.3.0  The missing Symfony Admin Generator
sonata-project/block-bundle              3.0.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.0.2  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.0.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.4.1  Lightweight Exporter library
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/user-bundle               3.0.1  Symfony SonataUserBundle`

#### Symfony packages
symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.2.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.2.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v2.8.7  The Symfony PHP framework

#### PHP version
PHP 5.6.2 (cli) (built: Oct 20 2014 16:21:27) 

## Subject
Wrong results in Admin Search feature when a 'createQuery' definition is used

## Steps to reproduce
The admin class is associated to a subset of the entity list using the 'createQuery'  :

    public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);
        $query
            ->innerJoin($query->getRootAlias()[0].'.category','cat', 'WITH', $query->expr()->orX(
                $query->expr()->eq('cat.systemName', ':fullcat'),
                $query->expr()->eq('cat.systemName', ':corpcat')))
            ->where($query->getRootAliases()[0] . '.startdate IS NULL')
            ->andWhere($query->getRootAliases()[0] . '.cancelled = 0')
            ->setParameter('fullcat', 'Full')
            ->setParameter('corpcat', 'Corporate');
        return $query;
    }

The DatagridFilter definition used by the Search feature is defined as follow :

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
        ->add('user.username')
        ->add('user.lastname')
        ->add('user.email')
        ->add('category')
        ->add('amount')
        ->add('categoryfee')
        ->add('naturesubscription')
        ;
    }

## Expected results

The Admin Search feature should take into account the condition defined within the 'createQuery' AND the condition built with the searched words

## Actual results

In the query launched by the Search feature, both conditions in the WHERE statement are linked using an OR keyword instead of the expected AND keyword :

SELECT count(DISTINCT m0_.id) AS sclr_0 FROM Membership m0_ INNER JOIN MembershipCategory m1_ ON m0_.category_id = m1_.id AND (m1_.systemName = ? OR m1_.systemName = ?) LEFT JOIN User u2_ ON m0_.Member_id = u2_.id LEFT JOIN CategoryFees c3_ ON m0_.categoryfee = c3_.id WHERE (m0_.startdate IS NULL AND m0_.cancelled = 0) **OR** u2_.username LIKE ? OR u2_.lastname LIKE ? OR u2_.email LIKE ? ["Full","Corporate","%toto%","%toto%","%toto%"]

As a result, all statements of the list are returned, instead of the subset of searched one (the result of the createQuery definition is identical to the result of the Search feature, whatever the searched word is)

**Comment by greg0ire** [comment] 2016-08-16 14:24
Is this a duplicate of #3368 ?

**Comment by gprioux** [comment] 2016-08-16 14:32
yes ! it seems that we've met the same problem
Sorry but I didn't find this one when I've looked for potential duplicate of my problem...

**Comment by greg0ire** [comment] 2016-08-16 14:33
No problem :)

**Closed by greg0ire** 2016-08-16 14:33 UTC
